default_common_size_imanges = [
    {'name': 'Small', 'name_esp': 'Pequeño', 'is_active': True,},
    {'name': 'Extra Small', 'name_esp': 'Extra Pequeño', 'is_active': True,},
    {'name': 'Normal', 'name_esp': 'Normal', 'is_active': True,},
    {'name': 'Large', 'name_esp': 'Grande', 'is_active': True,},
    {'name': 'Extra Large', 'name_esp': 'Extra Grande', 'is_active': True,},
]

default_common_qualities =[
    {'name': 'N/A', 'description': 'No Aplica.', 'is_active': True,},
    {'name': 'VHS', 'description': 'Calidad de video VHS.', 'is_active': True,},
    {'name': 'DVD', 'description': 'Calidad de video DVD.', 'is_active': True,},
    {'name': 'HDTV', 'description': 'Calidad de video HDTV.', 'is_active': True,},
    {'name': 'WEB', 'description': 'Calidad de video en línea (WEB).', 'is_active': True,},
    {'name': 'BD', 'description': 'Calidad de video Blu-ray (BD).', 'is_active': True,},
    {'name': 'C.C', 'description': 'Con Censura.', 'is_active': True,},
    {'name': 'S.C', 'description': 'Sin Censura', 'is_active': True,},
]

default_common_formats = [
    {'name': 'N/A', 'for_video': True, 'for_music': True, 'for_image': True, 'for_document': True, 'for_other': True, 'is_active': True,},
    {'name': 'AVI', 'for_video': True, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'MP4', 'for_video': True, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'MKV', 'for_video': True, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'MP3', 'for_video': False, 'for_music': True, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'WMA', 'for_video': False, 'for_music': True, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'FLAC', 'for_video': False, 'for_music': True, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'M4A', 'for_video': False, 'for_music': True, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'WEBP', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'JPG', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'JPEG', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'PNG', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'BMP', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'GIF', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'TIFF', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'TIF', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'SVG', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'RPGMVP', 'for_video': False, 'for_music': False, 'for_image': True, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'FLV', 'for_video': True, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'MOV', 'for_video': True, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'WEBM', 'for_video': True, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'WMV', 'for_video': True, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'AAC', 'for_video': False, 'for_music': True, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'OGG', 'for_video': False, 'for_music': True, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'WAV', 'for_video': False, 'for_music': True, 'for_image': False, 'for_document': False, 'for_other': False, 'is_active': True,},
    {'name': 'WOFF', 'for_video': False, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': True, 'is_active': True,},
    {'name': 'OTF', 'for_video': False, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': True, 'is_active': True,},
    {'name': 'TTF', 'for_video': False, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': True, 'is_active': True,},
    {'name': 'TTC', 'for_video': False, 'for_music': False, 'for_image': False, 'for_document': False, 'for_other': True, 'is_active': True,},
]

default_common_websites = [
    {'name': 'No Aplica', 'acronym': 'N/A', 'URL': 'https://dummy_web.com', 'is_active': True,},
    {'name': 'Anime4mega', 'acronym': 'A4M', 'URL': 'https://anime4mega.net/', 'is_active': True,},
    {'name': 'AniMegaFirex', 'acronym': 'AMFX', 'URL': 'https://www.animegafirex.com/', 'is_active': True,},
    {'name': 'AnimeHDL', 'acronym': 'AHDL', 'URL': 'https://animehdl.net/', 'is_active': True,},
    {'name': 'AnimeMF', 'acronym': 'AMF', 'URL': 'https://animemf.club/', 'is_active': True,},
    {'name': 'AnimeSD', 'acronym': 'ASD', 'URL': 'https://dummy_web_1.com', 'is_active': True,},
    {'name': 'APTX-Fansub', 'acronym': 'APTX', 'URL': 'https://apotoxinfansub.com/', 'is_active': True,},
    {'name': 'Az-Animex', 'acronym': 'AZA', 'URL': 'https://www.az-animex.com/', 'is_active': True,},
    {'name': 'ColitaHentai', 'acronym': 'CH', 'URL': 'https://colitahentai.su/', 'is_active': True,},
    {'name': 'CrisAnime', 'acronym': 'CA', 'URL': 'https://crisanimex.com/', 'is_active': True,},
    {'name': 'Daemon Hentai', 'acronym': 'DH', 'URL': 'https://www.daemon-hentai.com/', 'is_active': True,},
    {'name': 'Descarga-Animex', 'acronym': 'DA', 'URL': 'https://www.descarga-animex.net/', 'is_active': True,},
    {'name': 'DkAnime', 'acronym': 'DKA', 'URL': 'https://www.dkanime.online/', 'is_active': True,},
    {'name': 'Dw-Anime', 'acronym': 'DWA', 'URL': 'https://dummy_web_2.com', 'is_active': True,},
    {'name': 'Fukou-Da', 'acronym': 'FD', 'URL': 'https://fukou-da.net/', 'is_active': True,},
    {'name': 'Hentai-LA', 'acronym': 'HLA', 'URL': 'https://www4.hentaila.com/', 'is_active': True,},
    {'name': 'HyperAnimeBurst', 'acronym': 'HAB', 'URL': 'https://hyperanimeburst.blogspot.com/', 'is_active': True,},
    {'name': 'IvAnime', 'acronym': 'IVA', 'URL': 'https://www.ivanime.com/', 'is_active': True,},
    {'name': 'Japan-PAW', 'acronym': 'JPAW', 'URL': 'https://japan-paw.net/', 'is_active': True,},
    {'name': 'NinjinAnime', 'acronym': 'NA', 'URL': 'https://ninjinanime.com/', 'is_active': True,},
    {'name': 'RedLineSP', 'acronym': 'RLSP', 'URL': 'http://redlinesp.org/newrlsp/', 'is_active': True,},
    {'name': 'Reic-Zero', 'acronym': 'RZ', 'URL': 'https://reiczero.blogspot.com/', 'is_active': True,},
    {'name': 'SHentaiEsp', 'acronym': 'SHE', 'URL': 'https://shentaiesp.asia/', 'is_active': True,},
    {'name': 'SoAnime', 'acronym': 'SA', 'URL': 'https://www.soanimesitehd.com/', 'is_active': True,},
    {'name': 'TuAnimeLigero', 'acronym': 'TAL', 'URL': 'https://tuanimeligero.net/', 'is_active': True,},
    {'name': 'Tu-AnimesxD', 'acronym': 'TXD', 'URL': 'https://dummy_web_3.com', 'is_active': True,},
    {'name': 'Varias', 'acronym': 'VRS', 'URL': 'https://dummy_web_4.com', 'is_active': True,},
    {'name': 'YouAnime', 'acronym': 'YA', 'URL': 'https://younime.net/', 'is_active': True,},
    {'name': 'pokemonAnimePorMega', 'acronym': 'PAM', 'URL': 'https://pokemonanimepormega.blogspot.com/', 'is_active': True,},
    {'name': 'VortexAnime', 'acronym': 'VA', 'URL': 'http://animevortex0.blogspot.com/', 'is_active': True,},
]

default_common_countries = [
    {'name': 'The United Kingdom of Great Britain and Northern Ireland', 'name_esp': 'Reino Unido de Gran Bretaña e Irlanda del Norte', 'code': 'GBR', 'numeric_code': '826', 'is_active': True,},
    {'name': 'Saint Helena, Ascension and Tristan da Cunha', 'name_esp': 'Santa Elena, Ascensión y Tristán de Acuña ', 'code': 'SHN', 'numeric_code': '654', 'is_active': True,},
    {'name': 'South Georgia and the South Sandwich Islands', 'name_esp': 'Islas Georgia del Sur y Sandwich del Sur ', 'code': 'SGS', 'numeric_code': '239', 'is_active': True,},
    {'name': 'The Democratic People\'s Republic of Korea', 'name_esp': 'La República Popular Democrática de Corea', 'code': 'PRK', 'numeric_code': '408', 'is_active': True,},
    {'name': 'The Territory of Cocos (Keeling) Islands', 'name_esp': 'El Territorio de las Islas Cocos (Keeling)', 'code': 'CCK', 'numeric_code': '166', 'is_active': True,},
    {'name': 'The United States Minor Outlying Islands', 'name_esp': 'Islas menores alejadas de los Estados Unidos', 'code': 'UMI', 'numeric_code': '581', 'is_active': True,},
    {'name': 'The Democratic Republic of the Congo', 'name_esp': 'República Democrática del Congo', 'code': 'COD', 'numeric_code': '180', 'is_active': True,},
    {'name': 'The Lao People\'s Democratic Republic', 'name_esp': 'República Democrática Popular Lao', 'code': 'LAO', 'numeric_code': '418', 'is_active': True,},
    {'name': 'The British Indian Ocean Territory', 'name_esp': 'Territorio Británico del Océano Índico', 'code': 'IOT', 'numeric_code': '86', 'is_active': True,},
    {'name': 'Heard Island and McDonald Islands', 'name_esp': 'Islas Heard y McDonald', 'code': 'HMD', 'numeric_code': '334', 'is_active': True,},
    {'name': 'Bonaire, Sint Eustatius and Saba', 'name_esp': 'Bonaire, San Eustaquio y Saba', 'code': 'BES', 'numeric_code': '535', 'is_active': True,},
    {'name': 'Saint Vincent and the Grenadines', 'name_esp': 'San Vicente y las Granadinas', 'code': 'VCT', 'numeric_code': '670', 'is_active': True,},
    {'name': 'Bolivarian Republic of Venezuela', 'name_esp': 'República Bolivariana de Venezuela', 'code': 'VEN', 'numeric_code': '862', 'is_active': True,},
    {'name': 'The French Southern Territories', 'name_esp': 'Tierras Australes y Antárticas Francesas', 'code': 'ATF', 'numeric_code': '260', 'is_active': True,},
    {'name': 'The United Republic of Tanzania', 'name_esp': 'República Unida de Tanzania', 'code': 'TZA', 'numeric_code': '834', 'is_active': True,},
    {'name': 'Plurinational State of Bolivia', 'name_esp': 'Estado Plurinacional de Bolivia', 'code': 'BOL', 'numeric_code': '68', 'is_active': True,},
    {'name': 'Federated States of Micronesia', 'name_esp': 'Estados Federados de Micronesia', 'code': 'FSM', 'numeric_code': '583', 'is_active': True,},
    {'name': 'The Central African Republic', 'name_esp': 'República Centroafricana', 'code': 'CAF', 'numeric_code': '140', 'is_active': True,},
    {'name': 'The Northern Mariana Islands', 'name_esp': 'Islas Marianas del Norte', 'code': 'MNP', 'numeric_code': '580', 'is_active': True,},
    {'name': 'The Turks and Caicos Islands', 'name_esp': 'Islas Turcas y Caicos', 'code': 'TCA', 'numeric_code': '796', 'is_active': True,},
    {'name': 'The United States of America', 'name_esp': 'Estados Unidos de América', 'code': 'USA', 'numeric_code': '840', 'is_active': True,},
    {'name': 'Kingdom of the Netherlands', 'name_esp': 'Reino de los Países Bajos', 'code': 'NLD', 'numeric_code': '528', 'is_active': True,},
    {'name': 'Saint Martin (French part)', 'name_esp': 'San Martín (parte francesa)', 'code': 'MAF', 'numeric_code': '663', 'is_active': True,},
    {'name': 'Taiwan (Province of China)', 'name_esp': 'Taiwán (Provincia de China)', 'code': 'TWN', 'numeric_code': '158', 'is_active': True,},
    {'name': 'Saint Pierre and Miquelon', 'name_esp': 'San Pedro y Miquelón', 'code': 'SPM', 'numeric_code': '666', 'is_active': True,},
    {'name': 'Sint Maarten (Dutch part)', 'name_esp': 'Sint Maarten (parte neerlandesa)', 'code': 'SXM', 'numeric_code': '534', 'is_active': True,},
    {'name': 'Islamic Republic of Iran', 'name_esp': 'República Islámica de Irán', 'code': 'IRN', 'numeric_code': '364', 'is_active': True,},
    {'name': 'The Syrian Arab Republic', 'name_esp': 'República Árabe Siria', 'code': 'SYR', 'numeric_code': '760', 'is_active': True,},
    {'name': 'the United Arab Emirates', 'name_esp': 'Emiratos Árabes Unidos', 'code': 'ARE', 'numeric_code': '784', 'is_active': True,},
    {'name': 'Virgin Islands (British)', 'name_esp': 'Islas Vírgenes Británicas', 'code': 'VGB', 'numeric_code': '92', 'is_active': True,},
    {'name': 'the Republic of Moldova', 'name_esp': 'la República de Moldavia', 'code': 'MDA', 'numeric_code': '498', 'is_active': True,},
    {'name': 'Bosnia and Herzegovina', 'name_esp': 'Bosnia y Herzegovin', 'code': 'BIH', 'numeric_code': '70', 'is_active': True,},
    {'name': 'The Dominican Republic', 'name_esp': 'República Dominicana', 'code': 'DOM', 'numeric_code': '214', 'is_active': True,},
    {'name': 'The Russian Federation', 'name_esp': 'Federación de Rusia', 'code': 'RUS', 'numeric_code': '643', 'is_active': True,},
    {'name': 'Svalbard and Jan Mayen', 'name_esp': 'Svalbard y Jan Mayen', 'code': 'SJM', 'numeric_code': '744', 'is_active': True,},
    {'name': 'The Republic of Korea', 'name_esp': 'La República de Corea', 'code': 'KOR', 'numeric_code': '410', 'is_active': True,},
    {'name': 'Saint Kitts and Nevis', 'name_esp': 'San Cristóbal y Nieves', 'code': 'KNA', 'numeric_code': '659', 'is_active': True,},
    {'name': 'Sao Tome and Principe', 'name_esp': 'Santo Tomé y Príncipe', 'code': 'STP', 'numeric_code': '678', 'is_active': True,},
    {'name': 'Virgin Islands (U.S.)', 'name_esp': 'Islas Vírgenes de los Estados Unidos ', 'code': 'VIR', 'numeric_code': '850', 'is_active': True,},
    {'name': 'The Falkland Islands', 'name_esp': 'Islas Malvinas', 'code': 'FLK', 'numeric_code': '238', 'is_active': True,},
    {'name': 'The Marshall Islands', 'name_esp': 'Islas Marshall', 'code': 'MHL', 'numeric_code': '584', 'is_active': True,},
    {'name': 'Antigua and Barbuda', 'name_esp': 'Antigua y Barbuda', 'code': 'ATG', 'numeric_code': '28', 'is_active': True,},
    {'name': 'Trinidad and Tobago', 'name_esp': 'Trinidad y Tobago', 'code': 'TTO', 'numeric_code': '780', 'is_active': True,},
    {'name': 'The Cayman Islands', 'name_esp': 'Islas Caimán', 'code': 'CYM', 'numeric_code': '136', 'is_active': True,},
    {'name': 'State of Palestine', 'name_esp': 'Estado de Palestina', 'code': 'PSE', 'numeric_code': '275', 'is_active': True,},
    {'name': 'Brunei Darussalam', 'name_esp': 'Brunéi Darusalam', 'code': 'BRN', 'numeric_code': '96', 'is_active': True,},
    {'name': 'Equatorial Guinea', 'name_esp': 'Guinea Ecuatorial', 'code': 'GNQ', 'numeric_code': '226', 'is_active': True,},
    {'name': 'The Faroe Islands', 'name_esp': 'Islas Feroe', 'code': 'FRO', 'numeric_code': '234', 'is_active': True,},
    {'name': 'Wallis and Futuna', 'name_esp': 'Wallis y Futuna', 'code': 'WLF', 'numeric_code': '876', 'is_active': True,},
    {'name': 'Christmas Island', 'name_esp': 'Isla de Navidad', 'code': 'CXR', 'numeric_code': '162', 'is_active': True,},
    {'name': 'The Cook Islands', 'name_esp': 'Islas Cook', 'code': 'COK', 'numeric_code': '184', 'is_active': True,},
    {'name': 'French Polynesia', 'name_esp': 'Polinesia Francesa', 'code': 'PYF', 'numeric_code': '258', 'is_active': True,},
    {'name': 'Papua New Guinea', 'name_esp': 'Papúa Nueva Guinea', 'code': 'PNG', 'numeric_code': '598', 'is_active': True,},
    {'name': 'Saint Barthélemy', 'name_esp': 'San Bartolomé', 'code': 'BLM', 'numeric_code': '652', 'is_active': True,},
    {'name': 'North Macedonia', 'name_esp': 'Macedonia del Norte', 'code': 'MKD', 'numeric_code': '807', 'is_active': True,},
    {'name': 'The Philippines', 'name_esp': 'Las Filipinas', 'code': 'PHL', 'numeric_code': '608', 'is_active': True,},
    {'name': 'Solomon Islands', 'name_esp': 'Islas Salomón', 'code': 'SLB', 'numeric_code': '90', 'is_active': True,},
    {'name': 'American Samoa', 'name_esp': 'Samoa Americana', 'code': 'ASM', 'numeric_code': '16', 'is_active': True,},
    {'name': 'Norfolk Island', 'name_esp': 'Isla Norfolk', 'code': 'NFK', 'numeric_code': '574', 'is_active': True,},
    {'name': 'Western Sahara', 'name_esp': 'Sahara Occidental*', 'code': 'ESH', 'numeric_code': '732', 'is_active': True,},
    {'name': 'Bouvet Island', 'name_esp': 'Isla Bouvet', 'code': 'BVT', 'numeric_code': '74', 'is_active': True,},
    {'name': 'Côte d\'Ivoire', 'name_esp': 'Costa de Marfil', 'code': 'CIV', 'numeric_code': '384', 'is_active': True,},
    {'name': 'French Guiana', 'name_esp': 'Guayana Francesa', 'code': 'GUF', 'numeric_code': '254', 'is_active': True,},
    {'name': 'Guinea-Bissau', 'name_esp': 'Guinea-Bisáu', 'code': 'GNB', 'numeric_code': '624', 'is_active': True,},
    {'name': 'Liechtenstein', 'name_esp': 'Liechtenstein', 'code': 'LIE', 'numeric_code': '438', 'is_active': True,},
    {'name': 'New Caledonia', 'name_esp': 'Nueva Caledonia', 'code': 'NCL', 'numeric_code': '540', 'is_active': True,},
    {'name': 'Åland Islands', 'name_esp': 'Islas Åland', 'code': 'ALA', 'numeric_code': '248', 'is_active': True,},
    {'name': 'Burkina Faso', 'name_esp': 'Burkina Faso', 'code': 'BFA', 'numeric_code': '854', 'is_active': True,},
    {'name': 'The Holy See', 'name_esp': 'La Santa Sede (El Vaticano)', 'code': 'VAT', 'numeric_code': '336', 'is_active': True,},
    {'name': 'Saudi Arabia', 'name_esp': 'Arabia Saudita', 'code': 'SAU', 'numeric_code': '682', 'is_active': True,},
    {'name': 'Sierra Leone', 'name_esp': 'Sierra Leona', 'code': 'SLE', 'numeric_code': '694', 'is_active': True,},
    {'name': 'South Africa', 'name_esp': 'Sudáfrica', 'code': 'ZAF', 'numeric_code': '710', 'is_active': True,},
    {'name': 'Turkmenistan', 'name_esp': 'Turkmenistán', 'code': 'TKM', 'numeric_code': '795', 'is_active': True,},
    {'name': 'Afghanistan', 'name_esp': 'Afganistán', 'code': 'AFG', 'numeric_code': '4', 'is_active': True,},
    {'name': 'The Bahamas', 'name_esp': 'Las Bahamas', 'code': 'BHS', 'numeric_code': '44', 'is_active': True,},
    {'name': 'The Comoros', 'name_esp': 'Comoras', 'code': 'COM', 'numeric_code': '174', 'is_active': True,},
    {'name': 'El Salvador', 'name_esp': 'El Salvador', 'code': 'SLV', 'numeric_code': '222', 'is_active': True,},
    {'name': 'Isle of Man', 'name_esp': 'Isla de Man', 'code': 'IMN', 'numeric_code': '833', 'is_active': True,},
    {'name': 'New Zealand', 'name_esp': 'Nueva Zelanda', 'code': 'NZL', 'numeric_code': '554', 'is_active': True,},
    {'name': 'Niger (the)', 'name_esp': 'Níger', 'code': 'NER', 'numeric_code': '562', 'is_active': True,},
    {'name': 'Puerto Rico', 'name_esp': 'Puerto Rico', 'code': 'PRI', 'numeric_code': '630', 'is_active': True,},
    {'name': 'Saint Lucia', 'name_esp': 'Santa Lucía', 'code': 'LCA', 'numeric_code': '662', 'is_active': True,},
    {'name': 'South Sudan', 'name_esp': 'Sudán del Sur', 'code': 'SSD', 'numeric_code': '728', 'is_active': True,},
    {'name': 'Switzerland', 'name_esp': 'Suiza', 'code': 'CHE', 'numeric_code': '756', 'is_active': True,},
    {'name': 'Timor-Leste', 'name_esp': 'Timor Oriental', 'code': 'TLS', 'numeric_code': '626', 'is_active': True,},
    {'name': 'Antarctica', 'name_esp': 'Antártida', 'code': 'ATA', 'numeric_code': '10', 'is_active': True,},
    {'name': 'Azerbaijan', 'name_esp': 'Azerbaiyán', 'code': 'AZE', 'numeric_code': '31', 'is_active': True,},
    {'name': 'Bangladesh', 'name_esp': 'Bangladés', 'code': 'BGD', 'numeric_code': '50', 'is_active': True,},
    {'name': 'Cabo Verde', 'name_esp': 'Cabo Verde', 'code': 'CPV', 'numeric_code': '132', 'is_active': True,},
    {'name': 'Costa Rica', 'name_esp': 'Costa Rica', 'code': 'CRI', 'numeric_code': '188', 'is_active': True,},
    {'name': 'The Gambia', 'name_esp': 'Gambia', 'code': 'GMB', 'numeric_code': '270', 'is_active': True,},
    {'name': 'Guadeloupe', 'name_esp': 'Guadalupe', 'code': 'GLP', 'numeric_code': '312', 'is_active': True,},
    {'name': 'Kazakhstan', 'name_esp': 'Kazajistán', 'code': 'KAZ', 'numeric_code': '398', 'is_active': True,},
    {'name': 'Kyrgyzstan', 'name_esp': 'Kirguistán', 'code': 'KGZ', 'numeric_code': '417', 'is_active': True,},
    {'name': 'Luxembourg', 'name_esp': 'Luxemburgo', 'code': 'LUX', 'numeric_code': '442', 'is_active': True,},
    {'name': 'Madagascar', 'name_esp': 'Madagascar', 'code': 'MDG', 'numeric_code': '450', 'is_active': True,},
    {'name': 'Martinique', 'name_esp': 'Martinica', 'code': 'MTQ', 'numeric_code': '474', 'is_active': True,},
    {'name': 'Mauritania', 'name_esp': 'Mauritania', 'code': 'MRT', 'numeric_code': '478', 'is_active': True,},
    {'name': 'Montenegro', 'name_esp': 'Montenegro', 'code': 'MNE', 'numeric_code': '499', 'is_active': True,},
    {'name': 'Montserrat', 'name_esp': 'Montserrat', 'code': 'MSR', 'numeric_code': '500', 'is_active': True,},
    {'name': 'Mozambique', 'name_esp': 'Mozambique', 'code': 'MOZ', 'numeric_code': '508', 'is_active': True,},
    {'name': 'San Marino', 'name_esp': 'San Marino', 'code': 'SMR', 'numeric_code': '674', 'is_active': True,},
    {'name': 'Seychelles', 'name_esp': 'Seychelles', 'code': 'SYC', 'numeric_code': '690', 'is_active': True,},
    {'name': 'Tajikistan', 'name_esp': 'Tayikistán', 'code': 'TJK', 'numeric_code': '762', 'is_active': True,},
    {'name': 'Uzbekistan', 'name_esp': 'Uzbekistán', 'code': 'UZB', 'numeric_code': '860', 'is_active': True,},
    {'name': 'Argentina', 'name_esp': 'Argentina', 'code': 'ARG', 'numeric_code': '32', 'is_active': True,},
    {'name': 'Australia', 'name_esp': 'Australia', 'code': 'AUS', 'numeric_code': '36', 'is_active': True,},
    {'name': 'the Congo', 'name_esp': 'Congo', 'code': 'COG', 'numeric_code': '178', 'is_active': True,},
    {'name': 'Gibraltar', 'name_esp': 'Gibraltar', 'code': 'GIB', 'numeric_code': '292', 'is_active': True,},
    {'name': 'Greenland', 'name_esp': 'Groenlandia', 'code': 'GRL', 'numeric_code': '304', 'is_active': True,},
    {'name': 'Guatemala', 'name_esp': 'Guatemala', 'code': 'GTM', 'numeric_code': '320', 'is_active': True,},
    {'name': 'Hong Kong', 'name_esp': 'Hong Kong', 'code': 'HKG', 'numeric_code': '344', 'is_active': True,},
    {'name': 'Indonesia', 'name_esp': 'Indonesia', 'code': 'IDN', 'numeric_code': '360', 'is_active': True,},
    {'name': 'Lithuania', 'name_esp': 'Lituania', 'code': 'LTU', 'numeric_code': '440', 'is_active': True,},
    {'name': 'Mauritius', 'name_esp': 'Mauricio', 'code': 'MUS', 'numeric_code': '480', 'is_active': True,},
    {'name': 'Nicaragua', 'name_esp': 'Nicaragua', 'code': 'NIC', 'numeric_code': '558', 'is_active': True,},
    {'name': 'Singapore', 'name_esp': 'Singapur', 'code': 'SGP', 'numeric_code': '702', 'is_active': True,},
    {'name': 'Sri Lanka', 'name_esp': 'Sri Lanka', 'code': 'LKA', 'numeric_code': '144', 'is_active': True,},
    {'name': 'the Sudan', 'name_esp': 'Sudán', 'code': 'SDN', 'numeric_code': '729', 'is_active': True,},
    {'name': 'Anguilla', 'name_esp': 'Anguila', 'code': 'AIA', 'numeric_code': '660', 'is_active': True,},
    {'name': 'Barbados', 'name_esp': 'Barbados', 'code': 'BRB', 'numeric_code': '52', 'is_active': True,},
    {'name': 'Botswana', 'name_esp': 'Botsuana', 'code': 'BWA', 'numeric_code': '72', 'is_active': True,},
    {'name': 'Bulgaria', 'name_esp': 'Bulgaria', 'code': 'BGR', 'numeric_code': '100', 'is_active': True,},
    {'name': 'Cambodia', 'name_esp': 'Camboya', 'code': 'KHM', 'numeric_code': '116', 'is_active': True,},
    {'name': 'Cameroon', 'name_esp': 'Camerún', 'code': 'CMR', 'numeric_code': '120', 'is_active': True,},
    {'name': 'Colombia', 'name_esp': 'Colombia', 'code': 'COL', 'numeric_code': '170', 'is_active': True,},
    {'name': 'Djibouti', 'name_esp': 'Yibuti', 'code': 'DJI', 'numeric_code': '262', 'is_active': True,},
    {'name': 'Dominica', 'name_esp': 'Dominica', 'code': 'DMA', 'numeric_code': '212', 'is_active': True,},
    {'name': 'Eswatini', 'name_esp': 'Esuatini', 'code': 'SWZ', 'numeric_code': '748', 'is_active': True,},
    {'name': 'Ethiopia', 'name_esp': 'Etiopía', 'code': 'ETH', 'numeric_code': '231', 'is_active': True,},
    {'name': 'Guernsey', 'name_esp': 'Guernsey', 'code': 'GGY', 'numeric_code': '831', 'is_active': True,},
    {'name': 'Honduras', 'name_esp': 'Honduras', 'code': 'HND', 'numeric_code': '340', 'is_active': True,},
    {'name': 'Kiribati', 'name_esp': 'Kiribati', 'code': 'KIR', 'numeric_code': '296', 'is_active': True,},
    {'name': 'Malaysia', 'name_esp': 'Malasia', 'code': 'MYS', 'numeric_code': '458', 'is_active': True,},
    {'name': 'Maldives', 'name_esp': 'Maldivas', 'code': 'MDV', 'numeric_code': '462', 'is_active': True,},
    {'name': 'Mongolia', 'name_esp': 'Mongolia', 'code': 'MNG', 'numeric_code': '496', 'is_active': True,},
    {'name': 'Pakistan', 'name_esp': 'Pakistán', 'code': 'PAK', 'numeric_code': '586', 'is_active': True,},
    {'name': 'Paraguay', 'name_esp': 'Paraguay', 'code': 'PRY', 'numeric_code': '600', 'is_active': True,},
    {'name': 'Pitcairn', 'name_esp': 'Pitcairn', 'code': 'PCN', 'numeric_code': '612', 'is_active': True,},
    {'name': 'Portugal', 'name_esp': 'Portugal', 'code': 'PRT', 'numeric_code': '620', 'is_active': True,},
    {'name': 'Slovakia', 'name_esp': 'Eslovaquia', 'code': 'SVK', 'numeric_code': '703', 'is_active': True,},
    {'name': 'Slovenia', 'name_esp': 'Eslovenia', 'code': 'SVN', 'numeric_code': '705', 'is_active': True,},
    {'name': 'Suriname', 'name_esp': 'Surinam', 'code': 'SUR', 'numeric_code': '740', 'is_active': True,},
    {'name': 'Thailand', 'name_esp': 'Tailandia', 'code': 'THA', 'numeric_code': '764', 'is_active': True,},
    {'name': 'Viet Nam', 'name_esp': 'Vietnam', 'code': 'VNM', 'numeric_code': '704', 'is_active': True,},
    {'name': 'Zimbabwe', 'name_esp': 'Zimbabue ', 'code': 'ZWE', 'numeric_code': '716', 'is_active': True,},
    {'name': 'Albania', 'name_esp': 'Albania', 'code': 'ALB', 'numeric_code': '8', 'is_active': True,},
    {'name': 'Algeria', 'name_esp': 'Argelia', 'code': 'DZA', 'numeric_code': '12', 'is_active': True,},
    {'name': 'Andorra', 'name_esp': 'Andorra', 'code': 'AND', 'numeric_code': '20', 'is_active': True,},
    {'name': 'Armenia', 'name_esp': 'Armenia', 'code': 'ARM', 'numeric_code': '51', 'is_active': True,},
    {'name': 'Austria', 'name_esp': 'Austria', 'code': 'AUT', 'numeric_code': '40', 'is_active': True,},
    {'name': 'Bahrain', 'name_esp': 'Baréin', 'code': 'BHR', 'numeric_code': '48', 'is_active': True,},
    {'name': 'Belarus', 'name_esp': 'Bielorrusia', 'code': 'BLR', 'numeric_code': '112', 'is_active': True,},
    {'name': 'Belgium', 'name_esp': 'Bélgica', 'code': 'BEL', 'numeric_code': '56', 'is_active': True,},
    {'name': 'Bermuda', 'name_esp': 'Bermudas', 'code': 'BMU', 'numeric_code': '60', 'is_active': True,},
    {'name': 'Burundi', 'name_esp': 'Burundi', 'code': 'BDI', 'numeric_code': '108', 'is_active': True,},
    {'name': 'Croatia', 'name_esp': 'Croacia', 'code': 'HRV', 'numeric_code': '191', 'is_active': True,},
    {'name': 'Curaçao', 'name_esp': 'Curazao', 'code': 'CUW', 'numeric_code': '531', 'is_active': True,},
    {'name': 'Czechia', 'name_esp': 'Chequia', 'code': 'CZE', 'numeric_code': '203', 'is_active': True,},
    {'name': 'Denmark', 'name_esp': 'Dinamarca', 'code': 'DNK', 'numeric_code': '208', 'is_active': True,},
    {'name': 'Ecuador', 'name_esp': 'Ecuador', 'code': 'ECU', 'numeric_code': '218', 'is_active': True,},
    {'name': 'Eritrea', 'name_esp': 'Eritrea', 'code': 'ERI', 'numeric_code': '232', 'is_active': True,},
    {'name': 'Estonia', 'name_esp': 'Estonia', 'code': 'EST', 'numeric_code': '233', 'is_active': True,},
    {'name': 'Finland', 'name_esp': 'Finlandia', 'code': 'FIN', 'numeric_code': '246', 'is_active': True,},
    {'name': 'Georgia', 'name_esp': 'Georgia', 'code': 'GEO', 'numeric_code': '268', 'is_active': True,},
    {'name': 'Germany', 'name_esp': 'Alemania', 'code': 'DEU', 'numeric_code': '276', 'is_active': True,},
    {'name': 'Grenada', 'name_esp': 'Granada', 'code': 'GRD', 'numeric_code': '308', 'is_active': True,},
    {'name': 'Hungary', 'name_esp': 'Hungría', 'code': 'HUN', 'numeric_code': '348', 'is_active': True,},
    {'name': 'Iceland', 'name_esp': 'Islandia', 'code': 'ISL', 'numeric_code': '352', 'is_active': True,},
    {'name': 'Ireland', 'name_esp': 'Irlanda', 'code': 'IRL', 'numeric_code': '372', 'is_active': True,},
    {'name': 'Jamaica', 'name_esp': 'Jamaica', 'code': 'JAM', 'numeric_code': '388', 'is_active': True,},
    {'name': 'Lebanon', 'name_esp': 'Líbano', 'code': 'LBN', 'numeric_code': '422', 'is_active': True,},
    {'name': 'Lesotho', 'name_esp': 'Lesoto', 'code': 'LSO', 'numeric_code': '426', 'is_active': True,},
    {'name': 'Liberia', 'name_esp': 'Liberia', 'code': 'LBR', 'numeric_code': '430', 'is_active': True,},
    {'name': 'Mayotte', 'name_esp': 'Mayotte', 'code': 'MYT', 'numeric_code': '175', 'is_active': True,},
    {'name': 'Morocco', 'name_esp': 'Marruecos', 'code': 'MAR', 'numeric_code': '504', 'is_active': True,},
    {'name': 'Myanmar', 'name_esp': 'Myanmar (Birmania)', 'code': 'MMR', 'numeric_code': '104', 'is_active': True,},
    {'name': 'Namibia', 'name_esp': 'Namibia', 'code': 'NAM', 'numeric_code': '516', 'is_active': True,},
    {'name': 'Nigeria', 'name_esp': 'Nigeria', 'code': 'NGA', 'numeric_code': '566', 'is_active': True,},
    {'name': 'Romania', 'name_esp': 'Rumania', 'code': 'ROU', 'numeric_code': '642', 'is_active': True,},
    {'name': 'Réunion', 'name_esp': 'Reunión', 'code': 'REU', 'numeric_code': '638', 'is_active': True,},
    {'name': 'Senegal', 'name_esp': 'Senegal', 'code': 'SEN', 'numeric_code': '686', 'is_active': True,},
    {'name': 'Somalia', 'name_esp': 'Somalia', 'code': 'SOM', 'numeric_code': '706', 'is_active': True,},
    {'name': 'Tokelau', 'name_esp': 'Tokelau', 'code': 'TKL', 'numeric_code': '772', 'is_active': True,},
    {'name': 'Tunisia', 'name_esp': 'Túnez', 'code': 'TUN', 'numeric_code': '788', 'is_active': True,},
    {'name': 'Türkiye', 'name_esp': 'Turquía', 'code': 'TUR', 'numeric_code': '792', 'is_active': True,},
    {'name': 'Ukraine', 'name_esp': 'Ucrania', 'code': 'UKR', 'numeric_code': '804', 'is_active': True,},
    {'name': 'Uruguay', 'name_esp': 'Uruguay', 'code': 'URY', 'numeric_code': '858', 'is_active': True,},
    {'name': 'Vanuatu', 'name_esp': 'Vanuatu', 'code': 'VUT', 'numeric_code': '548', 'is_active': True,},
    {'name': 'Angola', 'name_esp': 'Angola', 'code': 'AGO', 'numeric_code': '24', 'is_active': True,},
    {'name': 'Belize', 'name_esp': 'Belice', 'code': 'BLZ', 'numeric_code': '84', 'is_active': True,},
    {'name': 'Bhutan', 'name_esp': 'Bután', 'code': 'BTN', 'numeric_code': '64', 'is_active': True,},
    {'name': 'Brazil', 'name_esp': 'Brasil', 'code': 'BRA', 'numeric_code': '76', 'is_active': True,},
    {'name': 'Canada', 'name_esp': 'Canadá', 'code': 'CAN', 'numeric_code': '124', 'is_active': True,},
    {'name': 'Cyprus', 'name_esp': 'Chipre', 'code': 'CYP', 'numeric_code': '196', 'is_active': True,},
    {'name': 'France', 'name_esp': 'Francia', 'code': 'FRA', 'numeric_code': '250', 'is_active': True,},
    {'name': 'Greece', 'name_esp': 'Grecia', 'code': 'GRC', 'numeric_code': '300', 'is_active': True,},
    {'name': 'Guinea', 'name_esp': 'Guinea', 'code': 'GIN', 'numeric_code': '324', 'is_active': True,},
    {'name': 'Guyana', 'name_esp': 'Guyana', 'code': 'GUY', 'numeric_code': '328', 'is_active': True,},
    {'name': 'Israel', 'name_esp': 'Israel', 'code': 'ISR', 'numeric_code': '376', 'is_active': True,},
    {'name': 'Jersey', 'name_esp': 'Jersey', 'code': 'JEY', 'numeric_code': '832', 'is_active': True,},
    {'name': 'Jordan', 'name_esp': 'Jordania', 'code': 'JOR', 'numeric_code': '400', 'is_active': True,},
    {'name': 'Kuwait', 'name_esp': 'Kuwait', 'code': 'KWT', 'numeric_code': '414', 'is_active': True,},
    {'name': 'Latvia', 'name_esp': 'Letonia', 'code': 'LVA', 'numeric_code': '428', 'is_active': True,},
    {'name': 'Malawi', 'name_esp': 'Malaui', 'code': 'MWI', 'numeric_code': '454', 'is_active': True,},
    {'name': 'Mexico', 'name_esp': 'México', 'code': 'MEX', 'numeric_code': '484', 'is_active': True,},
    {'name': 'Monaco', 'name_esp': 'Mónaco', 'code': 'MCO', 'numeric_code': '492', 'is_active': True,},
    {'name': 'Norway', 'name_esp': 'Noruega', 'code': 'NOR', 'numeric_code': '578', 'is_active': True,},
    {'name': 'Panama', 'name_esp': 'Panamá', 'code': 'PAN', 'numeric_code': '591', 'is_active': True,},
    {'name': 'Poland', 'name_esp': 'Polonia', 'code': 'POL', 'numeric_code': '616', 'is_active': True,},
    {'name': 'Rwanda', 'name_esp': 'Ruanda', 'code': 'RWA', 'numeric_code': '646', 'is_active': True,},
    {'name': 'Serbia', 'name_esp': 'Serbia', 'code': 'SRB', 'numeric_code': '688', 'is_active': True,},
    {'name': 'Sweden', 'name_esp': 'Suecia', 'code': 'SWE', 'numeric_code': '752', 'is_active': True,},
    {'name': 'Tuvalu', 'name_esp': 'Tuvalu', 'code': 'TUV', 'numeric_code': '798', 'is_active': True,},
    {'name': 'Uganda', 'name_esp': 'Uganda', 'code': 'UGA', 'numeric_code': '800', 'is_active': True,},
    {'name': 'Zambia', 'name_esp': 'Zambia', 'code': 'ZMB', 'numeric_code': '894', 'is_active': True,},
    {'name': 'Aruba', 'name_esp': 'Aruba', 'code': 'ABW', 'numeric_code': '533', 'is_active': True,},
    {'name': 'Benin', 'name_esp': 'Benín', 'code': 'BEN', 'numeric_code': '204', 'is_active': True,},
    {'name': 'Chile', 'name_esp': 'Chile', 'code': 'CHL', 'numeric_code': '152', 'is_active': True,},
    {'name': 'China', 'name_esp': 'China', 'code': 'CHN', 'numeric_code': '156', 'is_active': True,},
    {'name': 'Egypt', 'name_esp': 'Egipto', 'code': 'EGY', 'numeric_code': '818', 'is_active': True,},
    {'name': 'Gabon', 'name_esp': 'Gabón', 'code': 'GAB', 'numeric_code': '266', 'is_active': True,},
    {'name': 'Ghana', 'name_esp': 'Ghana', 'code': 'GHA', 'numeric_code': '288', 'is_active': True,},
    {'name': 'Haiti', 'name_esp': 'Haití', 'code': 'HTI', 'numeric_code': '332', 'is_active': True,},
    {'name': 'India', 'name_esp': 'India', 'code': 'IND', 'numeric_code': '356', 'is_active': True,},
    {'name': 'Italy', 'name_esp': 'Italia', 'code': 'ITA', 'numeric_code': '380', 'is_active': True,},
    {'name': 'Japan', 'name_esp': 'Japón', 'code': 'JPN', 'numeric_code': '392', 'is_active': True,},
    {'name': 'Kenya', 'name_esp': 'Kenia', 'code': 'KEN', 'numeric_code': '404', 'is_active': True,},
    {'name': 'Libya', 'name_esp': 'Libia', 'code': 'LBY', 'numeric_code': '434', 'is_active': True,},
    {'name': 'Macao', 'name_esp': 'Macao', 'code': 'MAC', 'numeric_code': '446', 'is_active': True,},
    {'name': 'Malta', 'name_esp': 'Malta', 'code': 'MLT', 'numeric_code': '470', 'is_active': True,},
    {'name': 'Nauru', 'name_esp': 'Nauru', 'code': 'NRU', 'numeric_code': '520', 'is_active': True,},
    {'name': 'Nepal', 'name_esp': 'Nepal', 'code': 'NPL', 'numeric_code': '524', 'is_active': True,},
    {'name': 'Palau', 'name_esp': 'Palaos', 'code': 'PLW', 'numeric_code': '585', 'is_active': True,},
    {'name': 'Qatar', 'name_esp': 'Catar', 'code': 'QAT', 'numeric_code': '634', 'is_active': True,},
    {'name': 'Samoa', 'name_esp': 'Samoa', 'code': 'WSM', 'numeric_code': '882', 'is_active': True,},
    {'name': 'Spain', 'name_esp': 'España', 'code': 'ESP', 'numeric_code': '724', 'is_active': True,},
    {'name': 'Tonga', 'name_esp': 'Tonga ', 'code': 'TON', 'numeric_code': '776', 'is_active': True,},
    {'name': 'Yemen', 'name_esp': 'Yemen', 'code': 'YEM', 'numeric_code': '887', 'is_active': True,},
    {'name': 'Chad', 'name_esp': 'Chad', 'code': 'TCD', 'numeric_code': '148', 'is_active': True,},
    {'name': 'Cuba', 'name_esp': 'Cuba', 'code': 'CUB', 'numeric_code': '192', 'is_active': True,},
    {'name': 'Fiji', 'name_esp': 'Fiyi', 'code': 'FJI', 'numeric_code': '242', 'is_active': True,},
    {'name': 'Guam', 'name_esp': 'Guam', 'code': 'GUM', 'numeric_code': '316', 'is_active': True,},
    {'name': 'Iraq', 'name_esp': 'Irak', 'code': 'IRQ', 'numeric_code': '368', 'is_active': True,},
    {'name': 'Mali', 'name_esp': 'Malí', 'code': 'MLI', 'numeric_code': '466', 'is_active': True,},
    {'name': 'Niue', 'name_esp': 'Niue', 'code': 'NIU', 'numeric_code': '570', 'is_active': True,},
    {'name': 'Oman', 'name_esp': 'Omán', 'code': 'OMN', 'numeric_code': '512', 'is_active': True,},
    {'name': 'Peru', 'name_esp': 'Perú', 'code': 'PER', 'numeric_code': '604', 'is_active': True,},
    {'name': 'Togo', 'name_esp': 'Togo', 'code': 'TGO', 'numeric_code': '768', 'is_active': True,},
]

default_common_languages = [
    {'name': 'Default', 'name_esp': 'Defecto', 'acronym': 'DEF', 'is_active': True,},
    {'name': 'Synonym', 'name_esp': 'Sinónimo', 'acronym': 'SYN', 'is_active': True,},
    {'name': 'Afar', 'name_esp': 'Afar', 'acronym': 'AAR', 'is_active': False,},
    {'name': 'Abkhazian', 'name_esp': 'Abjasio', 'acronym': 'ABK', 'is_active': False,},
    {'name': 'Achinese', 'name_esp': 'Achinés', 'acronym': 'ACE', 'is_active': False,},
    {'name': 'Acoli', 'name_esp': 'Acoli', 'acronym': 'ACH', 'is_active': False,},
    {'name': 'Adangme', 'name_esp': 'Adangme', 'acronym': 'ADA', 'is_active': False,},
    {'name': 'Adyghe; Adygei', 'name_esp': 'Adigué', 'acronym': 'ADY', 'is_active': False,},
    {'name': 'Afro-Asiatic languages', 'name_esp': 'Lenguas afroasiáticas', 'acronym': 'AFA', 'is_active': False,},
    {'name': 'Afrihili', 'name_esp': 'Afrihili', 'acronym': 'AFH', 'is_active': False,},
    {'name': 'Afrikaans', 'name_esp': 'Afrikaans', 'acronym': 'AFR', 'is_active': False,},
    {'name': 'Ainu', 'name_esp': 'Ainu', 'acronym': 'AIN', 'is_active': False,},
    {'name': 'Akan', 'name_esp': 'Akan', 'acronym': 'AKA', 'is_active': False,},
    {'name': 'Akkadian', 'name_esp': 'Acadio', 'acronym': 'AKK', 'is_active': False,},
    {'name': 'Albanian', 'name_esp': 'Albanés', 'acronym': 'ALB', 'is_active': False,},
    {'name': 'Aleut', 'name_esp': 'Aleutiano', 'acronym': 'ALE', 'is_active': False,},
    {'name': 'Algonquian languages', 'name_esp': 'Lenguas algonquinas', 'acronym': 'ALG', 'is_active': False,},
    {'name': 'Southern Altai', 'name_esp': 'Altái meridional', 'acronym': 'ALT', 'is_active': False,},
    {'name': 'Amharic', 'name_esp': 'Amhárico', 'acronym': 'AMH', 'is_active': False,},
    {'name': 'English, Old (ca.450-1100)', 'name_esp': 'Inglés antiguo (ca. 450-1100)', 'acronym': 'ANG', 'is_active': True,},
    {'name': 'Angika', 'name_esp': 'Angika', 'acronym': 'ANP', 'is_active': False,},
    {'name': 'Apache languages', 'name_esp': 'Lenguas apache', 'acronym': 'APA', 'is_active': False,},
    {'name': 'Arabic', 'name_esp': 'Árabe', 'acronym': 'ARA', 'is_active': False,},
    {'name': 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)', 'name_esp': 'Arameo oficial (700-300 a.C.); Arameo imperial (700-300 a.C.)', 'acronym': 'ARC', 'is_active': False,},
    {'name': 'Aragonese', 'name_esp': 'Aragonés', 'acronym': 'ARG', 'is_active': False,},
    {'name': 'Armenian', 'name_esp': 'Armenio', 'acronym': 'ARM', 'is_active': False,},
    {'name': 'Mapudungun; Mapuche', 'name_esp': 'Mapudungun; Mapuche', 'acronym': 'ARN', 'is_active': False,},
    {'name': 'Arapaho', 'name_esp': 'Arapaho', 'acronym': 'ARP', 'is_active': False,},
    {'name': 'Artificial languages', 'name_esp': 'Lenguas artificiales', 'acronym': 'ART', 'is_active': False,},
    {'name': 'Arawak', 'name_esp': 'Arahuaco', 'acronym': 'ARW', 'is_active': False,},
    {'name': 'Assamese', 'name_esp': 'Asamés', 'acronym': 'ASM', 'is_active': False,},
    {'name': 'Asturian; Bable; Leonese; Asturleonese', 'name_esp': 'Asturiano; Bable; Leonés; Asturleonés', 'acronym': 'AST', 'is_active': False,},
    {'name': 'Athapascan languages', 'name_esp': 'Lenguas atabascanas', 'acronym': 'ATH', 'is_active': False,},
    {'name': 'Australian languages', 'name_esp': 'Lenguas australianas', 'acronym': 'AUS', 'is_active': False,},
    {'name': 'Avaric', 'name_esp': 'Ávaro', 'acronym': 'AVA', 'is_active': False,},
    {'name': 'Avestan', 'name_esp': 'Avesta', 'acronym': 'AVE', 'is_active': False,},
    {'name': 'Awadhi', 'name_esp': 'Awadhi', 'acronym': 'AWA', 'is_active': False,},
    {'name': 'Aymara', 'name_esp': 'Aimara', 'acronym': 'AYM', 'is_active': False,},
    {'name': 'Azerbaijani', 'name_esp': 'Azerbaiyano', 'acronym': 'AZE', 'is_active': False,},
    {'name': 'Banda languages', 'name_esp': 'Lenguas banda', 'acronym': 'BAD', 'is_active': False,},
    {'name': 'Bamileke languages', 'name_esp': 'Lenguas bamileke', 'acronym': 'BAI', 'is_active': False,},
    {'name': 'Bashkir', 'name_esp': 'Baskir', 'acronym': 'BAK', 'is_active': False,},
    {'name': 'Baluchi', 'name_esp': 'Baluchi', 'acronym': 'BAL', 'is_active': False,},
    {'name': 'Bambara', 'name_esp': 'Bambara', 'acronym': 'BAM', 'is_active': False,},
    {'name': 'Balinese', 'name_esp': 'Balinés', 'acronym': 'BAN', 'is_active': False,},
    {'name': 'Basque', 'name_esp': 'Vasco', 'acronym': 'BAQ', 'is_active': False,},
    {'name': 'Basa', 'name_esp': 'Basa', 'acronym': 'BAS', 'is_active': False,},
    {'name': 'Baltic languages', 'name_esp': 'Lenguas bálticas', 'acronym': 'BAT', 'is_active': False,},
    {'name': 'Beja; Bedawiyet', 'name_esp': 'Baya', 'acronym': 'BEJ', 'is_active': False,},
    {'name': 'Belarusian', 'name_esp': 'Bielorruso', 'acronym': 'BEL', 'is_active': False,},
    {'name': 'Bemba', 'name_esp': 'Bemba', 'acronym': 'BEM', 'is_active': False,},
    {'name': 'Bengali', 'name_esp': 'Bengalí', 'acronym': 'BEN', 'is_active': False,},
    {'name': 'Berber languages', 'name_esp': 'Lenguas bereberes', 'acronym': 'BER', 'is_active': False,},
    {'name': 'Bhojpuri', 'name_esp': 'Bhojpuri', 'acronym': 'BHO', 'is_active': False,},
    {'name': 'Bihari languages', 'name_esp': 'Lenguas bihari', 'acronym': 'BIH', 'is_active': False,},
    {'name': 'Bikol', 'name_esp': 'Bicolano', 'acronym': 'BIK', 'is_active': False,},
    {'name': 'Bini; Edo', 'name_esp': 'Bini; Edo', 'acronym': 'BIN', 'is_active': False,},
    {'name': 'Bislama', 'name_esp': 'Bislama', 'acronym': 'BIS', 'is_active': False,},
    {'name': 'Siksika', 'name_esp': 'Siksika', 'acronym': 'BLA', 'is_active': False,},
    {'name': 'Bantu languages', 'name_esp': 'Lenguas bantú', 'acronym': 'BNT', 'is_active': False,},
    {'name': 'Tibetan', 'name_esp': 'Tibetano', 'acronym': 'BOD', 'is_active': False,},
    {'name': 'Bosnian', 'name_esp': 'Bosnio', 'acronym': 'BOS', 'is_active': False,},
    {'name': 'Braj', 'name_esp': 'Braj', 'acronym': 'BRA', 'is_active': False,},
    {'name': 'Breton', 'name_esp': 'Bretón', 'acronym': 'BRE', 'is_active': False,},
    {'name': 'Batak languages', 'name_esp': 'Lenguas batak', 'acronym': 'BTK', 'is_active': False,},
    {'name': 'Buriat', 'name_esp': 'Buriato', 'acronym': 'BUA', 'is_active': False,},
    {'name': 'Buginese', 'name_esp': 'Buguinés', 'acronym': 'BUG', 'is_active': False,},
    {'name': 'Bulgarian', 'name_esp': 'Búlgaro', 'acronym': 'BUL', 'is_active': False,},
    {'name': 'Burmese', 'name_esp': 'Birmano', 'acronym': 'BUR', 'is_active': False,},
    {'name': 'Blin; Bilin', 'name_esp': 'Blin; Bilin', 'acronym': 'BYN', 'is_active': False,},
    {'name': 'Caddo', 'name_esp': 'Caddo', 'acronym': 'CAD', 'is_active': False,},
    {'name': 'Central American Indian languages', 'name_esp': 'Lenguas indígenas de Centroamérica', 'acronym': 'CAI', 'is_active': False,},
    {'name': 'Galibi Carib', 'name_esp': 'Caribe galibi', 'acronym': 'CAR', 'is_active': False,},
    {'name': 'Catalan; Valencian', 'name_esp': 'Catalán; Valenciano', 'acronym': 'CAT', 'is_active': False,},
    {'name': 'Caucasian languages', 'name_esp': 'Lenguas caucásicas', 'acronym': 'CAU', 'is_active': False,},
    {'name': 'Cebuano', 'name_esp': 'Cebuano', 'acronym': 'CEB', 'is_active': False,},
    {'name': 'Celtic languages', 'name_esp': 'Lenguas celtas', 'acronym': 'CEL', 'is_active': False,},
    {'name': 'Czech', 'name_esp': 'Checo', 'acronym': 'CES', 'is_active': False,},
    {'name': 'Chamorro', 'name_esp': 'Chamorro', 'acronym': 'CHA', 'is_active': False,},
    {'name': 'Chibcha', 'name_esp': 'Chibcha', 'acronym': 'CHB', 'is_active': False,},
    {'name': 'Chechen', 'name_esp': 'Checheno', 'acronym': 'CHE', 'is_active': False,},
    {'name': 'Chagatai', 'name_esp': 'Chagatái', 'acronym': 'CHG', 'is_active': False,},
    {'name': 'Chinese', 'name_esp': 'Chino', 'acronym': 'CHI', 'is_active': False,},
    {'name': 'Chuukese', 'name_esp': 'Chuukés', 'acronym': 'CHK', 'is_active': False,},
    {'name': 'Mari', 'name_esp': 'Mari', 'acronym': 'CHM', 'is_active': False,},
    {'name': 'Chinook jargon', 'name_esp': 'Jerga chinuk', 'acronym': 'CHN', 'is_active': False,},
    {'name': 'Choctaw', 'name_esp': 'Choctaw', 'acronym': 'CHO', 'is_active': False,},
    {'name': 'Chipewyan; Dene Suline', 'name_esp': 'Chipewyan; Dene Suline', 'acronym': 'CHP', 'is_active': False,},
    {'name': 'Cherokee', 'name_esp': 'Cherokee', 'acronym': 'CHR', 'is_active': False,},
    {'name': 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'name_esp': 'Eslavo eclesiástico antiguo; Antiguo eslavo eclesiástico; Eslavo eclesiástico; Antiguo búlgaro; Antiguo eslavo', 'acronym': 'CHU', 'is_active': False,},
    {'name': 'Chuvash', 'name_esp': 'Chuvasio', 'acronym': 'CHV', 'is_active': False,},
    {'name': 'Cheyenne', 'name_esp': 'Cheyenne', 'acronym': 'CHY', 'is_active': False,},
    {'name': 'Chamic languages', 'name_esp': 'Lenguas chámicas', 'acronym': 'CMC', 'is_active': False,},
    {'name': 'Montenegrin', 'name_esp': 'Montenegrino', 'acronym': 'CNR', 'is_active': False,},
    {'name': 'Coptic', 'name_esp': 'Copto', 'acronym': 'COP', 'is_active': False,},
    {'name': 'Cornish', 'name_esp': 'Córnico', 'acronym': 'COR', 'is_active': False,},
    {'name': 'Corsican', 'name_esp': 'Corso', 'acronym': 'COS', 'is_active': False,},
    {'name': 'Creoles and pidgins, English based', 'name_esp': 'Criollos y pidgins basados en el inglés', 'acronym': 'CPE', 'is_active': False,},
    {'name': 'Creoles and pidgins, French-based', 'name_esp': 'cpf - Criollos y pidgins basados en el francés', 'acronym': 'CPF', 'is_active': False,},
    {'name': 'Creoles and pidgins, Portuguese-based', 'name_esp': 'Criollos y pidgins basados en el portugués', 'acronym': 'CPP', 'is_active': False,},
    {'name': 'Cree', 'name_esp': 'Cree', 'acronym': 'CRE', 'is_active': False,},
    {'name': 'Crimean Tatar; Crimean Turkish', 'name_esp': 'Tártaro de Crimea; Turco de Crimea', 'acronym': 'CRH', 'is_active': False,},
    {'name': 'Creoles and pidgins', 'name_esp': 'Criollos y pidgins', 'acronym': 'CRP', 'is_active': False,},
    {'name': 'Kashubian', 'name_esp': 'Casubio', 'acronym': 'CSB', 'is_active': False,},
    {'name': 'Cushitic languages', 'name_esp': 'Lenguas cusitas', 'acronym': 'CUS', 'is_active': False,},
    {'name': 'Welsh', 'name_esp': 'Galés', 'acronym': 'CYM', 'is_active': False,},
    {'name': 'Czech', 'name_esp': 'Checo', 'acronym': 'CZE', 'is_active': False,},
    {'name': 'Dakota', 'name_esp': 'Dakota', 'acronym': 'DAK', 'is_active': False,},
    {'name': 'Danish', 'name_esp': 'Danés', 'acronym': 'DAN', 'is_active': False,},
    {'name': 'Dargwa', 'name_esp': 'Dargwa', 'acronym': 'DAR', 'is_active': False,},
    {'name': 'Land Dayak languages', 'name_esp': 'Lenguas dayak terrestres', 'acronym': 'DAY', 'is_active': False,},
    {'name': 'Delaware', 'name_esp': 'Delaware', 'acronym': 'DEL', 'is_active': False,},
    {'name': 'Slave (Athapascan)', 'name_esp': 'Slave (atabascano)', 'acronym': 'DEN', 'is_active': False,},
    {'name': 'German', 'name_esp': 'Alemán', 'acronym': 'DEU', 'is_active': False,},
    {'name': 'Tlicho; Dogrib', 'name_esp': 'Tlicho; Dogrib', 'acronym': 'DGR', 'is_active': False,},
    {'name': 'Dinka', 'name_esp': 'Dinka', 'acronym': 'DIN', 'is_active': False,},
    {'name': 'Divehi; Dhivehi; Maldivian', 'name_esp': 'Dhivehi; Maldivo', 'acronym': 'DIV', 'is_active': False,},
    {'name': 'Dogri (macrolanguage)', 'name_esp': 'Dogri (macrolengua)', 'acronym': 'DOI', 'is_active': False,},
    {'name': 'Dravidian languages', 'name_esp': 'Lenguas drávidas', 'acronym': 'DRA', 'is_active': False,},
    {'name': 'Lower Sorbian', 'name_esp': 'Sorabo inferior', 'acronym': 'DSB', 'is_active': False,},
    {'name': 'Duala', 'name_esp': 'Duala', 'acronym': 'DUA', 'is_active': False,},
    {'name': 'Dutch, Middle (ca.1050-1350)', 'name_esp': 'Neerlandés medio (ca. 1050-1350)', 'acronym': 'DUM', 'is_active': False,},
    {'name': 'Dutch; Flemish', 'name_esp': 'Neerlandés; Flamenco', 'acronym': 'DUT', 'is_active': False,},
    {'name': 'Dyula', 'name_esp': 'Dyula', 'acronym': 'DYU', 'is_active': False,},
    {'name': 'Dzongkha', 'name_esp': 'Dzongkha', 'acronym': 'DZO', 'is_active': False,},
    {'name': 'Efik', 'name_esp': 'Efik', 'acronym': 'EFI', 'is_active': False,},
    {'name': 'Egyptian (Ancient)', 'name_esp': 'Egipcio (antiguo)', 'acronym': 'EGY', 'is_active': False,},
    {'name': 'Ekajuk', 'name_esp': 'Ekajuk', 'acronym': 'EKA', 'is_active': False,},
    {'name': 'Greek, Modern (1453-)', 'name_esp': 'Griego moderno (1453-)', 'acronym': 'ELL', 'is_active': False,},
    {'name': 'Elamite', 'name_esp': 'Elamita', 'acronym': 'ELX', 'is_active': False,},
    {'name': 'English', 'name_esp': 'Inglés', 'acronym': 'ENG', 'is_active': True,},
    {'name': 'English, Middle (1100-1500)', 'name_esp': 'Inglés medio (1100-1500)', 'acronym': 'ENM', 'is_active': True,},
    {'name': 'Esperanto', 'name_esp': 'Esperanto', 'acronym': 'EPO', 'is_active': False,},
    {'name': 'Estonian', 'name_esp': 'Estonio', 'acronym': 'EST', 'is_active': False,},
    {'name': 'Basque', 'name_esp': 'Vasco', 'acronym': 'EUS', 'is_active': False,},
    {'name': 'Ewe', 'name_esp': 'Ewe', 'acronym': 'EWE', 'is_active': False,},
    {'name': 'Ewondo', 'name_esp': 'Ewondo', 'acronym': 'EWO', 'is_active': False,},
    {'name': 'Fang', 'name_esp': 'Fang', 'acronym': 'FAN', 'is_active': False,},
    {'name': 'Faroese', 'name_esp': 'Faroés', 'acronym': 'FAO', 'is_active': False,},
    {'name': 'Persian', 'name_esp': 'Persa', 'acronym': 'FAS', 'is_active': False,},
    {'name': 'Fanti', 'name_esp': 'Fanti', 'acronym': 'FAT', 'is_active': False,},
    {'name': 'Fijian', 'name_esp': 'Fiyiano', 'acronym': 'FIJ', 'is_active': False,},
    {'name': 'Filipino; Pilipino', 'name_esp': 'Filipino; Pilipino', 'acronym': 'FIL', 'is_active': False,},
    {'name': 'Finnish', 'name_esp': 'Finlandés', 'acronym': 'FIN', 'is_active': False,},
    {'name': 'Finno-Ugrian languages', 'name_esp': 'Lenguas fino-ugrias', 'acronym': 'FIU', 'is_active': False,},
    {'name': 'Fon', 'name_esp': 'Fon', 'acronym': 'FON', 'is_active': False,},
    {'name': 'French', 'name_esp': 'Francés', 'acronym': 'FRA', 'is_active': True,},
    {'name': 'French', 'name_esp': 'Francés', 'acronym': 'FRE', 'is_active': True,},
    {'name': 'French, Middle (ca.1400-1600)', 'name_esp': 'Francés medio (ca. 1400-1600)', 'acronym': 'FRM', 'is_active': False,},
    {'name': 'French, Old (842-ca.1400)', 'name_esp': 'Francés antiguo (842-ca. 1400)', 'acronym': 'FRO', 'is_active': False,},
    {'name': 'Northern Frisian', 'name_esp': 'Frisón septentrional', 'acronym': 'FRR', 'is_active': False,},
    {'name': 'Eastern Frisian', 'name_esp': 'Frisón oriental', 'acronym': 'FRS', 'is_active': False,},
    {'name': 'Western Frisian', 'name_esp': 'Frisón occidental', 'acronym': 'FRY', 'is_active': False,},
    {'name': 'Fulah', 'name_esp': 'Fulani', 'acronym': 'FUL', 'is_active': False,},
    {'name': 'Friulian', 'name_esp': 'Friulano', 'acronym': 'FUR', 'is_active': False,},
    {'name': 'Ga', 'name_esp': 'Ga', 'acronym': 'GAA', 'is_active': False,},
    {'name': 'Gayo', 'name_esp': 'Gayo', 'acronym': 'GAY', 'is_active': False,},
    {'name': 'Gbaya', 'name_esp': 'Gbaya', 'acronym': 'GBA', 'is_active': False,},
    {'name': 'Germanic languages', 'name_esp': 'Lenguas germánicas', 'acronym': 'GEM', 'is_active': False,},
    {'name': 'Georgian', 'name_esp': 'Georgiano', 'acronym': 'GEO', 'is_active': False,},
    {'name': 'German', 'name_esp': 'Alemán', 'acronym': 'GER', 'is_active': True,},
    {'name': 'Geez', 'name_esp': 'Ge\'ez', 'acronym': 'GEZ', 'is_active': False,},
    {'name': 'Gilbertese', 'name_esp': 'Gilbertés', 'acronym': 'GIL', 'is_active': False,},
    {'name': 'Gaelic; Scottish Gaelic', 'name_esp': 'Gaélico escocés', 'acronym': 'GLA', 'is_active': False,},
    {'name': 'Irish', 'name_esp': 'Irlandés', 'acronym': 'GLE', 'is_active': False,},
    {'name': 'Galician', 'name_esp': 'Gallego', 'acronym': 'GLG', 'is_active': False,},
    {'name': 'Manx', 'name_esp': 'Manés', 'acronym': 'GLV', 'is_active': False,},
    {'name': 'German, Middle High (ca.1050-1500)', 'name_esp': 'Alto alemán medio (ca. 1050-1500)', 'acronym': 'GMH', 'is_active': False,},
    {'name': 'German, Old High (ca.750-1050)', 'name_esp': 'Alto alemán antiguo (ca. 750-1050', 'acronym': 'GOH', 'is_active': False,},
    {'name': 'Gondi', 'name_esp': 'Gondi', 'acronym': 'GON', 'is_active': False,},
    {'name': 'Gorontalo', 'name_esp': 'Gorontalo', 'acronym': 'GOR', 'is_active': False,},
    {'name': 'Gothic', 'name_esp': 'Gótico', 'acronym': 'GOT', 'is_active': False,},
    {'name': 'Grebo', 'name_esp': 'Grebo', 'acronym': 'GRB', 'is_active': False,},
    {'name': 'Greek, Ancient (to 1453)', 'name_esp': 'Griego antiguo (hasta 1453)', 'acronym': 'GRC', 'is_active': False,},
    {'name': 'Greek, Modern (1453-)', 'name_esp': 'Griego moderno (1453-)', 'acronym': 'GRE', 'is_active': False,},
    {'name': 'Guarani', 'name_esp': 'Guaraní', 'acronym': 'GRN', 'is_active': False,},
    {'name': 'Swiss German; Alemannic; Alsatian', 'name_esp': 'Alemán suizo; Alemánico; Alsaciano', 'acronym': 'GSW', 'is_active': False,},
    {'name': 'Gujarati', 'name_esp': 'Gujarati', 'acronym': 'GUJ', 'is_active': False,},
    {'name': 'Gwich\'in', 'name_esp': 'Gwich\'in', 'acronym': 'GWI', 'is_active': False,},
    {'name': 'Haida', 'name_esp': 'Haida', 'acronym': 'HAI', 'is_active': False,},
    {'name': 'Haitian; Haitian Creole', 'name_esp': 'Haitiano; Criollo haitiano', 'acronym': 'HAT', 'is_active': False,},
    {'name': 'Hausa', 'name_esp': 'Hausa', 'acronym': 'HAU', 'is_active': False,},
    {'name': 'Hawaiian', 'name_esp': 'Hawaiano', 'acronym': 'HAW', 'is_active': False,},
    {'name': 'Hebrew', 'name_esp': 'Hebreo', 'acronym': 'HEB', 'is_active': False,},
    {'name': 'Herero', 'name_esp': 'Herero', 'acronym': 'HER', 'is_active': False,},
    {'name': 'Hiligaynon', 'name_esp': 'Hiligaynon', 'acronym': 'HIL', 'is_active': False,},
    {'name': 'Himachali languages; Western Pahari languages', 'name_esp': 'Lenguas himachalí; Lenguas pahari occidentales', 'acronym': 'HIM', 'is_active': False,},
    {'name': 'Hindi', 'name_esp': 'Hindi', 'acronym': 'HIN', 'is_active': False,},
    {'name': 'Hittite', 'name_esp': 'Hitita', 'acronym': 'HIT', 'is_active': False,},
    {'name': 'Hmong; Mong', 'name_esp': 'Hmong; Mong', 'acronym': 'HMN', 'is_active': False,},
    {'name': 'Hiri Motu', 'name_esp': 'Hiri motu', 'acronym': 'HMO', 'is_active': False,},
    {'name': 'Croatian', 'name_esp': 'Croata', 'acronym': 'HRV', 'is_active': False,},
    {'name': 'Upper Sorbian', 'name_esp': 'Sorabo superior', 'acronym': 'HSB', 'is_active': False,},
    {'name': 'Hungarian', 'name_esp': 'Húngaro', 'acronym': 'HUN', 'is_active': False,},
    {'name': 'Hupa', 'name_esp': 'Hupa', 'acronym': 'HUP', 'is_active': False,},
    {'name': 'Armenian', 'name_esp': 'Armenio', 'acronym': 'HYE', 'is_active': False,},
    {'name': 'Iban', 'name_esp': 'Iban', 'acronym': 'IBA', 'is_active': False,},
    {'name': 'Igbo', 'name_esp': 'Igbo', 'acronym': 'IBO', 'is_active': False,},
    {'name': 'Icelandic', 'name_esp': 'Islandés', 'acronym': 'ICE', 'is_active': False,},
    {'name': 'Ido', 'name_esp': 'Ido', 'acronym': 'IDO', 'is_active': False,},
    {'name': 'Sichuan Yi; Nuosu', 'name_esp': 'Yi de Sichuan; Nuosu', 'acronym': 'III', 'is_active': False,},
    {'name': 'Ijo languages', 'name_esp': 'Lenguas ijo', 'acronym': 'IJO', 'is_active': False,},
    {'name': 'Inuktitut', 'name_esp': 'Inuktitut', 'acronym': 'IKU', 'is_active': False,},
    {'name': 'Interlingue; Occidental', 'name_esp': 'Interlingue; Occidental', 'acronym': 'ILE', 'is_active': False,},
    {'name': 'Iloko', 'name_esp': 'Ilocano', 'acronym': 'ILO', 'is_active': False,},
    {'name': 'Interlingua (International Auxiliary Language Association)', 'name_esp': 'Interlingua (Asociación de Lengua Auxiliar Internacional)', 'acronym': 'INA', 'is_active': False,},
    {'name': 'Indic languages', 'name_esp': 'Lenguas índicas', 'acronym': 'INC', 'is_active': False,},
    {'name': 'Indonesian', 'name_esp': 'Indonesio', 'acronym': 'IND', 'is_active': False,},
    {'name': 'Indo-European languages', 'name_esp': 'Lenguas indoeuropeas', 'acronym': 'INE', 'is_active': False,},
    {'name': 'Ingush', 'name_esp': 'Ingush', 'acronym': 'INH', 'is_active': False,},
    {'name': 'Inupiaq', 'name_esp': 'Inupiaq', 'acronym': 'IPK', 'is_active': False,},
    {'name': 'Iranian languages', 'name_esp': 'Lenguas iranias', 'acronym': 'IRA', 'is_active': False,},
    {'name': 'Iroquoian languages', 'name_esp': 'Lenguas iroquesas', 'acronym': 'IRO', 'is_active': False,},
    {'name': 'Icelandic', 'name_esp': 'Islandés', 'acronym': 'ISL', 'is_active': False,},
    {'name': 'Italian', 'name_esp': 'Italiano', 'acronym': 'ITA', 'is_active': True,},
    {'name': 'Javanese', 'name_esp': 'Javanés', 'acronym': 'JAV', 'is_active': False,},
    {'name': 'Lojban', 'name_esp': 'Lojban', 'acronym': 'JBO', 'is_active': False,},
    {'name': 'Japanese', 'name_esp': 'Japonés', 'acronym': 'JPN', 'is_active': True,},
    {'name': 'Judeo-Persian', 'name_esp': 'Judeo-persa', 'acronym': 'JPR', 'is_active': False,},
    {'name': 'Judeo-Arabic', 'name_esp': 'Judeo-árabe', 'acronym': 'JRB', 'is_active': False,},
    {'name': 'Kara-Kalpak', 'name_esp': 'Karakalpako', 'acronym': 'KAA', 'is_active': False,},
    {'name': 'Kabyle', 'name_esp': 'Cabilio', 'acronym': 'KAB', 'is_active': False,},
    {'name': 'Kachin; Jingpho', 'name_esp': 'Kachin; Jingpho', 'acronym': 'KAC', 'is_active': False,},
    {'name': 'Kalaallisut; Greenlandic', 'name_esp': 'Kalaallisut; Groenlandés', 'acronym': 'KAL', 'is_active': False,},
    {'name': 'Kamba', 'name_esp': 'Kamba', 'acronym': 'KAM', 'is_active': False,},
    {'name': 'Kannada', 'name_esp': 'Canarés', 'acronym': 'KAN', 'is_active': False,},
    {'name': 'Karen languages', 'name_esp': 'Lenguas karen', 'acronym': 'KAR', 'is_active': False,},
    {'name': 'Kashmiri', 'name_esp': 'Cachemiro', 'acronym': 'KAS', 'is_active': False,},
    {'name': 'Georgian', 'name_esp': 'Georgiano', 'acronym': 'KAT', 'is_active': False,},
    {'name': 'Kanuri', 'name_esp': 'Kanuri', 'acronym': 'KAU', 'is_active': False,},
    {'name': 'Kawi', 'name_esp': 'Kawi', 'acronym': 'KAW', 'is_active': False,},
    {'name': 'Kazakh', 'name_esp': 'Kazajo', 'acronym': 'KAZ', 'is_active': False,},
    {'name': 'Kabardian', 'name_esp': 'Cabardino', 'acronym': 'KBD', 'is_active': False,},
    {'name': 'Khasi', 'name_esp': 'Khasi', 'acronym': 'KHA', 'is_active': False,},
    {'name': 'Khoisan languages', 'name_esp': 'Lenguas khoisán', 'acronym': 'KHI', 'is_active': False,},
    {'name': 'Central Khmer', 'name_esp': 'Jemer central', 'acronym': 'KHM', 'is_active': False,},
    {'name': 'Khotanese; Sakan', 'name_esp': 'Jotanés; Saca', 'acronym': 'KHO', 'is_active': False,},
    {'name': 'Kikuyu; Gikuyu', 'name_esp': 'Kikuyu; Gikuyu', 'acronym': 'KIK', 'is_active': False,},
    {'name': 'Kinyarwanda', 'name_esp': 'Kinyarwanda', 'acronym': 'KIN', 'is_active': False,},
    {'name': 'Kirghiz; Kyrgyz', 'name_esp': 'Kirguís', 'acronym': 'KIR', 'is_active': False,},
    {'name': 'Kimbundu', 'name_esp': 'Kimbundu', 'acronym': 'KMB', 'is_active': False,},
    {'name': 'Konkani (macrolanguage)', 'name_esp': 'Konkaní (macrolengua)', 'acronym': 'KOK', 'is_active': False,},
    {'name': 'Komi', 'name_esp': 'Komi', 'acronym': 'KOM', 'is_active': False,},
    {'name': 'Kongo', 'name_esp': 'Kongo', 'acronym': 'KON', 'is_active': False,},
    {'name': 'Korean', 'name_esp': 'Coreano', 'acronym': 'KOR', 'is_active': False,},
    {'name': 'Kosraean', 'name_esp': 'Kosraeano', 'acronym': 'KOS', 'is_active': False,},
    {'name': 'Kpelle', 'name_esp': 'Kpelle', 'acronym': 'KPE', 'is_active': False,},
    {'name': 'Karachay-Balkar', 'name_esp': 'Karachayo-bálkaro', 'acronym': 'KRC', 'is_active': False,},
    {'name': 'Karelian', 'name_esp': 'Carelio', 'acronym': 'KRL', 'is_active': False,},
    {'name': 'Kru languages', 'name_esp': 'Lenguas kru', 'acronym': 'KRO', 'is_active': False,},
    {'name': 'Kurukh', 'name_esp': 'Kurukh', 'acronym': 'KRU', 'is_active': False,},
    {'name': 'Kuanyama; Kwanyama', 'name_esp': 'Kuanyama; Kwanyama', 'acronym': 'KUA', 'is_active': False,},
    {'name': 'Kumyk', 'name_esp': 'Kumyko', 'acronym': 'KUM', 'is_active': False,},
    {'name': 'Kurdish', 'name_esp': 'Kurdo', 'acronym': 'KUR', 'is_active': False,},
    {'name': 'Kutenai', 'name_esp': 'Kutenai', 'acronym': 'KUT', 'is_active': False,},
    {'name': 'Ladino', 'name_esp': 'Ladino', 'acronym': 'LAD', 'is_active': False,},
    {'name': 'Lahnda', 'name_esp': 'Lahnda', 'acronym': 'LAH', 'is_active': False,},
    {'name': 'Lamba', 'name_esp': 'Lamba', 'acronym': 'LAM', 'is_active': False,},
    {'name': 'Lao', 'name_esp': 'Lao', 'acronym': 'LAO', 'is_active': False,},
    {'name': 'Latin', 'name_esp': 'Latín', 'acronym': 'LAT', 'is_active': False,},
    {'name': 'Latvian', 'name_esp': 'Letón', 'acronym': 'LAV', 'is_active': False,},
    {'name': 'Lezghian', 'name_esp': 'Lezguio', 'acronym': 'LEZ', 'is_active': False,},
    {'name': 'Limburgan; Limburger; Limburgish', 'name_esp': 'Limburgo; Limburger; Limburgués', 'acronym': 'LIM', 'is_active': False,},
    {'name': 'Lingala', 'name_esp': 'Lingala', 'acronym': 'LIN', 'is_active': False,},
    {'name': 'Lithuanian', 'name_esp': 'Lituano', 'acronym': 'LIT', 'is_active': False,},
    {'name': 'Mongo', 'name_esp': 'Mongo', 'acronym': 'LOL', 'is_active': False,},
    {'name': 'Lozi', 'name_esp': 'Lozi', 'acronym': 'LOZ', 'is_active': False,},
    {'name': 'Luxembourgish; Letzeburgesch', 'name_esp': 'Luxemburgués', 'acronym': 'LTZ', 'is_active': False,},
    {'name': 'Luba-Lulua', 'name_esp': 'Luba-lulua', 'acronym': 'LUA', 'is_active': False,},
    {'name': 'Luba-Katanga', 'name_esp': 'Luba-katanga', 'acronym': 'LUB', 'is_active': False,},
    {'name': 'Ganda', 'name_esp': 'Ganda', 'acronym': 'LUG', 'is_active': False,},
    {'name': 'Luiseno', 'name_esp': 'Luiseño', 'acronym': 'LUI', 'is_active': False,},
    {'name': 'Lunda', 'name_esp': 'Lunda', 'acronym': 'LUN', 'is_active': False,},
    {'name': 'Luo (Kenya and Tanzania)', 'name_esp': 'Luo (Kenia y Tanzania)', 'acronym': 'LUO', 'is_active': False,},
    {'name': 'Lushai', 'name_esp': 'Lushai', 'acronym': 'LUS', 'is_active': False,},
    {'name': 'Macedonian', 'name_esp': 'Macedonio', 'acronym': 'MAC', 'is_active': False,},
    {'name': 'Madurese', 'name_esp': 'Madurés', 'acronym': 'MAD', 'is_active': False,},
    {'name': 'Magahi', 'name_esp': 'Magahi', 'acronym': 'MAG', 'is_active': False,},
    {'name': 'Marshallese', 'name_esp': 'Marshallés', 'acronym': 'MAH', 'is_active': False,},
    {'name': 'Maithili', 'name_esp': 'Maithili', 'acronym': 'MAI', 'is_active': False,},
    {'name': 'Makasar', 'name_esp': 'Makasar', 'acronym': 'MAK', 'is_active': False,},
    {'name': 'Malayalam', 'name_esp': 'Malayalam', 'acronym': 'MAL', 'is_active': False,},
    {'name': 'Mandingo', 'name_esp': 'Mandingo', 'acronym': 'MAN', 'is_active': False,},
    {'name': 'Maori', 'name_esp': 'Maorí', 'acronym': 'MAO', 'is_active': False,},
    {'name': 'Austronesian languages', 'name_esp': 'Lenguas austronesias', 'acronym': 'MAP', 'is_active': False,},
    {'name': 'Marathi', 'name_esp': 'Marathi', 'acronym': 'MAR', 'is_active': False,},
    {'name': 'Masai', 'name_esp': 'Masai', 'acronym': 'MAS', 'is_active': False,},
    {'name': 'Malay (macrolanguage)', 'name_esp': 'Malayo (macrolengua)', 'acronym': 'MAY', 'is_active': False,},
    {'name': 'Moksha', 'name_esp': 'Moksha', 'acronym': 'MDF', 'is_active': False,},
    {'name': 'Mandar', 'name_esp': 'Mandar', 'acronym': 'MDR', 'is_active': False,},
    {'name': 'Mende', 'name_esp': 'Mende', 'acronym': 'MEN', 'is_active': False,},
    {'name': 'Irish, Middle (900-1200)', 'name_esp': 'Irlandés medio (900-1200)', 'acronym': 'MGA', 'is_active': False,},
    {'name': 'Mi\'kmaq; Micmac', 'name_esp': 'Mi\kmaq; Micmac', 'acronym': 'MIC', 'is_active': False,},
    {'name': 'Minangkabau', 'name_esp': 'Minangkabau', 'acronym': 'MIN', 'is_active': False,},
    {'name': 'Uncoded languages', 'name_esp': 'Lenguas no codificadas', 'acronym': 'MIS', 'is_active': False,},
    {'name': 'Macedonian', 'name_esp': 'Macedonio', 'acronym': 'MKD', 'is_active': False,},
    {'name': 'Mon-Khmer languages', 'name_esp': 'Lenguas mon-jemer', 'acronym': 'MKH', 'is_active': False,},
    {'name': 'Malagasy', 'name_esp': 'Malgache', 'acronym': 'MLG', 'is_active': False,},
    {'name': 'Maltese', 'name_esp': 'Maltés', 'acronym': 'MLT', 'is_active': False,},
    {'name': 'Manchu', 'name_esp': 'Manchú', 'acronym': 'MNC', 'is_active': False,},
    {'name': 'Manipuri', 'name_esp': 'Manipurí', 'acronym': 'MNI', 'is_active': False,},
    {'name': 'Manobo languages', 'name_esp': 'Lenguas manobo', 'acronym': 'MNO', 'is_active': False,},
    {'name': 'Mohawk', 'name_esp': 'Mohawk', 'acronym': 'MOH', 'is_active': False,},
    {'name': 'Mongolian', 'name_esp': 'Mongol', 'acronym': 'MON', 'is_active': False,},
    {'name': 'Mossi', 'name_esp': 'Mossi', 'acronym': 'MOS', 'is_active': False,},
    {'name': 'Maori', 'name_esp': 'Maorí', 'acronym': 'MRI', 'is_active': False,},
    {'name': 'Malay (macrolanguage)', 'name_esp': 'Malayo (macrolengua)', 'acronym': 'MSA', 'is_active': False,},
    {'name': 'Multiple languages', 'name_esp': 'Múltiples lenguas', 'acronym': 'MUL', 'is_active': False,},
    {'name': 'Munda languages', 'name_esp': 'Lenguas munda', 'acronym': 'MUN', 'is_active': False,},
    {'name': 'Creek', 'name_esp': 'Creek', 'acronym': 'MUS', 'is_active': False,},
    {'name': 'Mirandese', 'name_esp': 'Mirandés', 'acronym': 'MWL', 'is_active': False,},
    {'name': 'Marwari', 'name_esp': 'Marwari', 'acronym': 'MWR', 'is_active': False,},
    {'name': 'Burmese', 'name_esp': 'Birmano', 'acronym': 'MYA', 'is_active': False,},
    {'name': 'Mayan languages', 'name_esp': 'Lenguas mayas', 'acronym': 'MYN', 'is_active': False,},
    {'name': 'Erzya', 'name_esp': 'Erzia', 'acronym': 'MYV', 'is_active': False,},
    {'name': 'Nahuatl languages', 'name_esp': 'Lenguas náhuatl', 'acronym': 'NAH', 'is_active': False,},
    {'name': 'North American Indian languages', 'name_esp': 'Lenguas indígenas de América del Norte', 'acronym': 'NAI', 'is_active': False,},
    {'name': 'Neapolitan', 'name_esp': 'Napolitano', 'acronym': 'NAP', 'is_active': False,},
    {'name': 'Nauru', 'name_esp': 'Nauruano', 'acronym': 'NAU', 'is_active': False,},
    {'name': 'Navajo; Navaho', 'name_esp': 'Navajo; Navaho', 'acronym': 'NAV', 'is_active': False,},
    {'name': 'Ndebele, South; South Ndebele', 'name_esp': 'Ndebele del sur; Ndebele meridional', 'acronym': 'NBL', 'is_active': False,},
    {'name': 'Ndebele, North; North Ndebele', 'name_esp': 'Ndebele del norte; Ndebele septentrional', 'acronym': 'NDE', 'is_active': False,},
    {'name': 'Ndonga', 'name_esp': 'Ndonga', 'acronym': 'NDO', 'is_active': False,},
    {'name': 'Low German; Low Saxon; German, Low; Saxon, Low', 'name_esp': 'Bajo alemán; Bajo sajón; Alemán bajo; Sajón bajo', 'acronym': 'NDS', 'is_active': False,},
    {'name': 'Nepali (macrolanguage)', 'name_esp': 'Nepalí (macrolengua)', 'acronym': 'NEP', 'is_active': False,},
    {'name': 'Nepal Bhasa; Newari', 'name_esp': 'Nepal Bhasa; Newari', 'acronym': 'NEW', 'is_active': False,},
    {'name': 'Nias', 'name_esp': 'Nias', 'acronym': 'NIA', 'is_active': False,},
    {'name': 'Niger-Kordofanian languages', 'name_esp': 'Lenguas níger-kordofanianas', 'acronym': 'NIC', 'is_active': False,},
    {'name': 'Niuean', 'name_esp': 'Niueano', 'acronym': 'NIU', 'is_active': False,},
    {'name': 'Dutch; Flemish', 'name_esp': 'Neerlandés; Flamenco', 'acronym': 'NLD', 'is_active': False,},
    {'name': 'Bokmål, Norwegian; Norwegian Bokmål', 'name_esp': 'Bokmål noruego', 'acronym': 'NOB', 'is_active': False,},
    {'name': 'Nogai', 'name_esp': 'Nogayo', 'acronym': 'NOG', 'is_active': False,},
    {'name': 'Norse, Old', 'name_esp': 'Nórdico antiguo', 'acronym': 'NON', 'is_active': False,},
    {'name': 'Norwegian', 'name_esp': 'Noruego', 'acronym': 'NOR', 'is_active': False,},
    {'name': 'N\'Ko', 'name_esp': 'N\'Ko', 'acronym': 'NQO', 'is_active': False,},
    {'name': 'Pedi; Sepedi; Northern Sotho', 'name_esp': 'Pedi; Sepedi; Sotho septentrional', 'acronym': 'NSO', 'is_active': False,},
    {'name': 'Nubian languages', 'name_esp': 'Lenguas nubias', 'acronym': 'NUB', 'is_active': False,},
    {'name': 'Classical Newari; Old Newari; Classical Nepal Bhasa', 'name_esp': 'Newari clásico; Newari antiguo; Nepal Bhasa clásico', 'acronym': 'NWC', 'is_active': False,},
    {'name': 'Chichewa; Chewa; Nyanja', 'name_esp': 'Chichewa; Chewa; Nyanja', 'acronym': 'NYA', 'is_active': False,},
    {'name': 'Nyamwezi', 'name_esp': 'Nyamwezi', 'acronym': 'NYM', 'is_active': False,},
    {'name': 'Nyankole', 'name_esp': 'Nyankole', 'acronym': 'NYN', 'is_active': False,},
    {'name': 'Nyoro', 'name_esp': 'Nyoro', 'acronym': 'NYO', 'is_active': False,},
    {'name': 'Nzima', 'name_esp': 'Nzima', 'acronym': 'NZI', 'is_active': False,},
    {'name': 'Occitan (post 1500)', 'name_esp': 'Occitano (posterior a 1500)', 'acronym': 'OCI', 'is_active': False,},
    {'name': 'Ojibwa', 'name_esp': 'Ojibwa', 'acronym': 'OJI', 'is_active': False,},
    {'name': 'Oriya (macrolanguage)', 'name_esp': 'Oriya (macrolengua)', 'acronym': 'ORI', 'is_active': False,},
    {'name': 'Oromo', 'name_esp': 'Oromo', 'acronym': 'ORM', 'is_active': False,},
    {'name': 'Osage', 'name_esp': 'Osage', 'acronym': 'OSA', 'is_active': False,},
    {'name': 'Ossetian; Ossetic', 'name_esp': 'Osetio', 'acronym': 'OSS', 'is_active': False,},
    {'name': 'Turkish, Ottoman (1500-1928)', 'name_esp': 'Turco otomano (1500-1928)', 'acronym': 'OTA', 'is_active': False,},
    {'name': 'Otomian languages', 'name_esp': 'Lenguas otomíes', 'acronym': 'OTO', 'is_active': False,},
    {'name': 'Papuan languages', 'name_esp': 'Lenguas papúes', 'acronym': 'PAA', 'is_active': False,},
    {'name': 'Pangasinan', 'name_esp': 'Pangasinán', 'acronym': 'PAG', 'is_active': False,},
    {'name': 'Pahlavi', 'name_esp': 'Pahlavi', 'acronym': 'PAL', 'is_active': False,},
    {'name': 'Pampanga; Kapampangan', 'name_esp': 'Pampango; Capampangan', 'acronym': 'PAM', 'is_active': False,},
    {'name': 'Panjabi; Punjabi', 'name_esp': 'Panjabi; Punjabi', 'acronym': 'PAN', 'is_active': False,},
    {'name': 'Papiamento', 'name_esp': 'Papiamento', 'acronym': 'PAP', 'is_active': False,},
    {'name': 'Palauan', 'name_esp': 'Palauano', 'acronym': 'PAU', 'is_active': False,},
    {'name': 'Persian, Old (ca.600-400 B.C.)', 'name_esp': 'Persa antiguo (ca. 600-400 a.C.)', 'acronym': 'PEO', 'is_active': False,},
    {'name': 'Persian', 'name_esp': 'Persa', 'acronym': 'PER', 'is_active': False,},
    {'name': 'Philippine languages', 'name_esp': 'Lenguas filipinas', 'acronym': 'PHI', 'is_active': False,},
    {'name': 'Phoenician', 'name_esp': 'Fenicio', 'acronym': 'PHN', 'is_active': False,},
    {'name': 'Pali', 'name_esp': 'Pali', 'acronym': 'PLI', 'is_active': False,},
    {'name': 'Polish', 'name_esp': 'Polaco', 'acronym': 'POL', 'is_active': False,},
    {'name': 'Pohnpeian', 'name_esp': 'Pohnpeiano', 'acronym': 'PON', 'is_active': False,},
    {'name': 'Portuguese', 'name_esp': 'Portugués', 'acronym': 'POR', 'is_active': False,},
    {'name': 'Prakrit languages', 'name_esp': 'Lenguas prácritas', 'acronym': 'PRA', 'is_active': False,},
    {'name': 'Provençal, Old (to 1500);Occitan, Old (to 1500)', 'name_esp': 'Provenzal antiguo (hasta 1500); Occitano antiguo (hasta 1500)', 'acronym': 'PRO', 'is_active': False,},
    {'name': 'Pushto; Pashto', 'name_esp': 'Pushto; Pashto', 'acronym': 'PUS', 'is_active': False,},
    {'name': 'Quechua', 'name_esp': 'Quechua', 'acronym': 'QUE', 'is_active': False,},
    {'name': 'Rajasthani', 'name_esp': 'Rajasthani', 'acronym': 'RAJ', 'is_active': False,},
    {'name': 'Rapanui', 'name_esp': 'Rapanui', 'acronym': 'RAP', 'is_active': False,},
    {'name': 'Rarotongan; Cook Islands Maori', 'name_esp': 'Rarotongano; Maorí de las Islas Cook', 'acronym': 'RAR', 'is_active': False,},
    {'name': 'Romance languages', 'name_esp': 'Lenguas romances', 'acronym': 'ROA', 'is_active': False,},
    {'name': 'Romansh', 'name_esp': 'Romanche', 'acronym': 'ROH', 'is_active': False,},
    {'name': 'Romany', 'name_esp': 'Romaní', 'acronym': 'ROM', 'is_active': False,},
    {'name': 'Romanian; Moldavian; Moldovan', 'name_esp': 'Rumano; Moldavo', 'acronym': 'RON', 'is_active': False,},
    {'name': 'Romanian; Moldavian; Moldovan', 'name_esp': 'Rumano; Moldavo', 'acronym': 'RUM', 'is_active': False,},
    {'name': 'Rundi', 'name_esp': 'Rundi', 'acronym': 'RUN', 'is_active': False,},
    {'name': 'Aromanian; Arumanian; Macedo-Romanian', 'name_esp': 'Arumano; Macedorrumano', 'acronym': 'RUP', 'is_active': False,},
    {'name': 'Russian', 'name_esp': 'Ruso', 'acronym': 'RUS', 'is_active': False,},
    {'name': 'Sandawe', 'name_esp': 'Sandawe', 'acronym': 'SAD', 'is_active': False,},
    {'name': 'Sango', 'name_esp': 'Sango', 'acronym': 'SAG', 'is_active': False,},
    {'name': 'Yakut', 'name_esp': 'Yakuto', 'acronym': 'SAH', 'is_active': False,},
    {'name': 'South American Indian languages', 'name_esp': 'Lenguas indígenas de América del Sur', 'acronym': 'SAI', 'is_active': False,},
    {'name': 'Salishan languages', 'name_esp': 'Lenguas salish', 'acronym': 'SAL', 'is_active': False,},
    {'name': 'Samaritan Aramaic', 'name_esp': 'Arameo samaritano', 'acronym': 'SAM', 'is_active': False,},
    {'name': 'Sanskrit', 'name_esp': 'Sánscrito', 'acronym': 'SAN', 'is_active': False,},
    {'name': 'Sasak', 'name_esp': 'Sasak', 'acronym': 'SAS', 'is_active': False,},
    {'name': 'Santali', 'name_esp': 'Santali', 'acronym': 'SAT', 'is_active': False,},
    {'name': 'Sicilian', 'name_esp': 'Siciliano', 'acronym': 'SCN', 'is_active': False,},
    {'name': 'Scots', 'name_esp': 'Escocés', 'acronym': 'SCO', 'is_active': False,},
    {'name': 'Selkup', 'name_esp': 'Selkup', 'acronym': 'SEL', 'is_active': False,},
    {'name': 'Semitic languages', 'name_esp': 'Lenguas semíticas', 'acronym': 'SEM', 'is_active': False,},
    {'name': 'Irish, Old (to 900)', 'name_esp': 'Irlandés antiguo (hasta 900)', 'acronym': 'SGA', 'is_active': False,},
    {'name': 'Sign Languages', 'name_esp': 'Lenguas de signos', 'acronym': 'SGN', 'is_active': False,},
    {'name': 'Shan', 'name_esp': 'Shan', 'acronym': 'SHN', 'is_active': False,},
    {'name': 'Sidamo', 'name_esp': 'Sidamo', 'acronym': 'SID', 'is_active': False,},
    {'name': 'Sinhala; Sinhalese', 'name_esp': 'Sinhala; Cingalés', 'acronym': 'SIN', 'is_active': False,},
    {'name': 'Siouan languages', 'name_esp': 'Lenguas sioux', 'acronym': 'SIO', 'is_active': False,},
    {'name': 'Sino-Tibetan languages', 'name_esp': 'Lenguas sino-tibetanas', 'acronym': 'SIT', 'is_active': False,},
    {'name': 'Slavic languages', 'name_esp': 'Lenguas eslavas', 'acronym': 'SLA', 'is_active': False,},
    {'name': 'Slovak', 'name_esp': 'Eslovaco', 'acronym': 'SLK', 'is_active': False,},
    {'name': 'Slovak', 'name_esp': 'Eslovaco', 'acronym': 'SLO', 'is_active': False,},
    {'name': 'Slovenian', 'name_esp': 'Esloveno', 'acronym': 'SLV', 'is_active': False,},
    {'name': 'Southern Sami', 'name_esp': 'Sami meridional', 'acronym': 'SMA', 'is_active': False,},
    {'name': 'Northern Sami', 'name_esp': 'Sami septentrional', 'acronym': 'SME', 'is_active': False,},
    {'name': 'Sami languages', 'name_esp': 'Lenguas sami', 'acronym': 'SMI', 'is_active': False,},
    {'name': 'Lule Sami', 'name_esp': 'Sami lule', 'acronym': 'SMJ', 'is_active': False,},
    {'name': 'Inari Sami', 'name_esp': 'Sami inari', 'acronym': 'SMN', 'is_active': False,},
    {'name': 'Samoan', 'name_esp': 'Samoano', 'acronym': 'SMO', 'is_active': False,},
    {'name': 'Skolt Sami', 'name_esp': 'Sami skolt', 'acronym': 'SMS', 'is_active': False,},
    {'name': 'Shona', 'name_esp': 'Shona', 'acronym': 'SNA', 'is_active': False,},
    {'name': 'Sindhi', 'name_esp': 'Sindhi', 'acronym': 'SND', 'is_active': False,},
    {'name': 'Soninke', 'name_esp': 'Soninké', 'acronym': 'SNK', 'is_active': False,},
    {'name': 'Sogdian', 'name_esp': 'Sogdiano', 'acronym': 'SOG', 'is_active': False,},
    {'name': 'Somali', 'name_esp': 'Somalí', 'acronym': 'SOM', 'is_active': False,},
    {'name': 'Songhai languages', 'name_esp': 'Lenguas songhai', 'acronym': 'SON', 'is_active': False,},
    {'name': 'Sotho, Southern', 'name_esp': 'Sotho meridional', 'acronym': 'SOT', 'is_active': False,},
    {'name': 'Spanish; Castilian', 'name_esp': 'Español; Castellano', 'acronym': 'SPA', 'is_active': True,},
    {'name': 'Albanian', 'name_esp': 'Albanés', 'acronym': 'SQI', 'is_active': False,},
    {'name': 'Sardinian', 'name_esp': 'Sardo', 'acronym': 'SRD', 'is_active': False,},
    {'name': 'Sranan Tongo', 'name_esp': 'Sranan tongo', 'acronym': 'SRN', 'is_active': False,},
    {'name': 'Serbian', 'name_esp': 'Serbio', 'acronym': 'SRP', 'is_active': False,},
    {'name': 'Serer', 'name_esp': 'Serer', 'acronym': 'SRR', 'is_active': False,},
    {'name': 'Nilo-Saharan languages', 'name_esp': 'Lenguas nilo-saharianas', 'acronym': 'SSA', 'is_active': False,},
    {'name': 'Swati', 'name_esp': 'Swati', 'acronym': 'SSW', 'is_active': False,},
    {'name': 'Sukuma', 'name_esp': 'Sukuma', 'acronym': 'SUK', 'is_active': False,},
    {'name': 'Sundanese', 'name_esp': 'Sundanés', 'acronym': 'SUN', 'is_active': False,},
    {'name': 'Susu', 'name_esp': 'Susu', 'acronym': 'SUS', 'is_active': False,},
    {'name': 'Sumerian', 'name_esp': 'Sumerio', 'acronym': 'SUX', 'is_active': False,},
    {'name': 'Swahili (macrolanguage)', 'name_esp': 'Suajili (macrolengua)', 'acronym': 'SWA', 'is_active': False,},
    {'name': 'Swedish', 'name_esp': 'Sueco', 'acronym': 'SWE', 'is_active': False,},
    {'name': 'Classical Syriac', 'name_esp': 'Siríaco clásico', 'acronym': 'SYC', 'is_active': False,},
    {'name': 'Syriac', 'name_esp': 'Siríaco', 'acronym': 'SYR', 'is_active': False,},
    {'name': 'Tahitian', 'name_esp': 'Tahitiano', 'acronym': 'TAH', 'is_active': False,},
    {'name': 'Tai languages', 'name_esp': 'Lenguas tai', 'acronym': 'TAI', 'is_active': False,},
    {'name': 'Tamil', 'name_esp': 'Tamil', 'acronym': 'TAM', 'is_active': False,},
    {'name': 'Tatar', 'name_esp': 'Tártaro', 'acronym': 'TAT', 'is_active': False,},
    {'name': 'Telugu', 'name_esp': 'Telugu', 'acronym': 'TEL', 'is_active': False,},
    {'name': 'Timne', 'name_esp': 'Timne', 'acronym': 'TEM', 'is_active': False,},
    {'name': 'Tereno', 'name_esp': 'Tereno', 'acronym': 'TER', 'is_active': False,},
    {'name': 'Tetum', 'name_esp': 'Tetum', 'acronym': 'TET', 'is_active': False,},
    {'name': 'Tajik', 'name_esp': 'Tayiko', 'acronym': 'TGK', 'is_active': False,},
    {'name': 'Tagalog', 'name_esp': 'Tagalo', 'acronym': 'TGL', 'is_active': False,},
    {'name': 'Thai', 'name_esp': 'Tailandés', 'acronym': 'THA', 'is_active': False,},
    {'name': 'Tibetan', 'name_esp': 'Tibetano', 'acronym': 'TIB', 'is_active': False,},
    {'name': 'Tigre', 'name_esp': 'Tigre', 'acronym': 'TIG', 'is_active': False,},
    {'name': 'Tigrinya', 'name_esp': 'Tigriña', 'acronym': 'TIR', 'is_active': False,},
    {'name': 'Tiv', 'name_esp': 'Tiv', 'acronym': 'TIV', 'is_active': False,},
    {'name': 'Tokelau', 'name_esp': 'Tokelauano', 'acronym': 'TKL', 'is_active': False,},
    {'name': 'Klingon; tlhIngan-Hol', 'name_esp': 'Klingon; tlhIngan-Hol', 'acronym': 'TLH', 'is_active': False,},
    {'name': 'Tlingit', 'name_esp': 'Tlingit', 'acronym': 'TLI', 'is_active': False,},
    {'name': 'Tamashek', 'name_esp': 'Tamashek', 'acronym': 'TMH', 'is_active': False,},
    {'name': 'Tonga (Nyasa)', 'name_esp': 'Tonga (Nyasa)', 'acronym': 'TOG', 'is_active': False,},
    {'name': 'Tonga (Tonga Islands)', 'name_esp': 'Tonga (Islas Tonga)', 'acronym': 'TON', 'is_active': False,},
    {'name': 'Tok Pisin', 'name_esp': 'Tok pisin', 'acronym': 'TPI', 'is_active': False,},
    {'name': 'Tsimshian', 'name_esp': 'Tsimshian', 'acronym': 'TSI', 'is_active': False,},
    {'name': 'Tswana', 'name_esp': 'Tswana', 'acronym': 'TSN', 'is_active': False,},
    {'name': 'Tsonga', 'name_esp': 'Tsonga', 'acronym': 'TSO', 'is_active': False,},
    {'name': 'Turkmen', 'name_esp': 'Turcomano', 'acronym': 'TUK', 'is_active': False,},
    {'name': 'Tumbuka', 'name_esp': 'Tumbuka', 'acronym': 'TUM', 'is_active': False,},
    {'name': 'Tupi languages', 'name_esp': 'Lenguas tupí', 'acronym': 'TUP', 'is_active': False,},
    {'name': 'Turkish', 'name_esp': 'Turco', 'acronym': 'TUR', 'is_active': False,},
    {'name': 'Altaic languages', 'name_esp': 'Lenguas altaicas', 'acronym': 'TUT', 'is_active': False,},
    {'name': 'Tuvalu', 'name_esp': 'Tuvaluano', 'acronym': 'TVL', 'is_active': False,},
    {'name': 'Twi', 'name_esp': 'Twi', 'acronym': 'TWI', 'is_active': False,},
    {'name': 'Tuvinian', 'name_esp': 'Tuviniano', 'acronym': 'TYV', 'is_active': False,},
    {'name': 'Udmurt', 'name_esp': 'Udmurto', 'acronym': 'UDM', 'is_active': False,},
    {'name': 'Ugaritic', 'name_esp': 'Ugarítico', 'acronym': 'UGA', 'is_active': False,},
    {'name': 'Uighur; Uyghur', 'name_esp': 'Uigur; Uyghur', 'acronym': 'UIG', 'is_active': False,},
    {'name': 'Ukrainian', 'name_esp': 'Ucraniano', 'acronym': 'UKR', 'is_active': False,},
    {'name': 'Umbundu', 'name_esp': 'Umbundu', 'acronym': 'UMB', 'is_active': False,},
    {'name': 'Undetermined', 'name_esp': 'Indeterminado', 'acronym': 'UND', 'is_active': False,},
    {'name': 'Urdu', 'name_esp': 'Urdu', 'acronym': 'URD', 'is_active': False,},
    {'name': 'Uzbek', 'name_esp': 'Uzbeko', 'acronym': 'UZB', 'is_active': False,},
    {'name': 'Vai', 'name_esp': 'Vai', 'acronym': 'VAI', 'is_active': False,},
    {'name': 'Venda', 'name_esp': 'Venda', 'acronym': 'VEN', 'is_active': False,},
    {'name': 'Vietnamese', 'name_esp': 'Vietnamita', 'acronym': 'VIE', 'is_active': False,},
    {'name': 'Volapük', 'name_esp': 'Volapük', 'acronym': 'VOL', 'is_active': False,},
    {'name': 'Votic', 'name_esp': 'Vótico', 'acronym': 'VOT', 'is_active': False,},
    {'name': 'Wakashan languages', 'name_esp': 'Lenguas wakash', 'acronym': 'WAK', 'is_active': False,},
    {'name': 'Wolaitta; Wolaytta', 'name_esp': 'Wolaitta; Wolaytta', 'acronym': 'WAL', 'is_active': False,},
    {'name': 'Waray', 'name_esp': 'Waray', 'acronym': 'WAR', 'is_active': False,},
    {'name': 'Washo', 'name_esp': 'Washo', 'acronym': 'WAS', 'is_active': False,},
    {'name': 'Welsh', 'name_esp': 'Galés', 'acronym': 'WEL', 'is_active': False,},
    {'name': 'Sorbian languages', 'name_esp': 'Lenguas sorbias', 'acronym': 'WEN', 'is_active': False,},
    {'name': 'Walloon', 'name_esp': 'Valón', 'acronym': 'WLN', 'is_active': False,},
    {'name': 'Wolof', 'name_esp': 'Wolof', 'acronym': 'WOL', 'is_active': False,},
    {'name': 'Kalmyk; Oirat', 'name_esp': 'Calmucio; Oirato', 'acronym': 'XAL', 'is_active': False,},
    {'name': 'Xhosa', 'name_esp': 'Xhosa', 'acronym': 'XHO', 'is_active': False,},
    {'name': 'Yao', 'name_esp': 'Yao', 'acronym': 'YAO', 'is_active': False,},
    {'name': 'Yapese', 'name_esp': 'Yapés', 'acronym': 'YAP', 'is_active': False,},
    {'name': 'Yiddish', 'name_esp': 'Yidis', 'acronym': 'YID', 'is_active': False,},
    {'name': 'Yoruba', 'name_esp': 'Yoruba', 'acronym': 'YOR', 'is_active': False,},
    {'name': 'Yupik languages', 'name_esp': 'Lenguas yupik', 'acronym': 'YPK', 'is_active': False,},
    {'name': 'Zapotec', 'name_esp': 'Zapoteco', 'acronym': 'ZAP', 'is_active': False,},
    {'name': 'Blissymbols; Blissymbolics; Bliss', 'name_esp': 'Blissymbols; Blissymbolics; Bliss', 'acronym': 'ZBL', 'is_active': False,},
    {'name': 'Zenaga', 'name_esp': 'Zenaga', 'acronym': 'ZEN', 'is_active': False,},
    {'name': 'Standard Moroccan Tamazight', 'name_esp': 'Tamazight marroquí estándar', 'acronym': 'ZGH', 'is_active': False,},
    {'name': 'Zhuang; Chuang', 'name_esp': 'Zhuang; Chuang', 'acronym': 'ZHA', 'is_active': False,},
    {'name': 'Chinese', 'name_esp': 'Chino', 'acronym': 'ZHO', 'is_active': False,},
    {'name': 'Zande languages', 'name_esp': 'Lenguas zande', 'acronym': 'ZND', 'is_active': False,},
    {'name': 'Zulu', 'name_esp': 'Zulú', 'acronym': 'ZUL', 'is_active': False,},
    {'name': 'Zuni', 'name_esp': 'Zuni', 'acronym': 'ZUN', 'is_active': False,},
    {'name': 'No linguistic content; Not applicable', 'name_esp': 'Sin contenido lingüístico; No aplicable', 'acronym': 'ZXX', 'is_active': False,},
    {'name': 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', 'name_esp': 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', 'acronym': 'ZZA', 'is_active': False,},
]