# Generated by Django 5.2.1 on 2025-05-08 14:32

import apps.serie.utils.uploads
import core.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_alter_commonlog_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Nombre Slug')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('founded_year', core.utils.utils.YearField(blank=True, null=True, validators=[core.utils.utils.validate_year], verbose_name='Año Fundación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seriess_as_countries', to='common.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'ordering': ['-created_at', 'initial', 'name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre Español')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Nombre Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('explicit', models.BooleanField(default=False, verbose_name='Explicito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='serie.genre', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=15, unique=True, verbose_name='Acrónimo')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Nombre Español')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['acronym', 'name'],
                'unique_together': {('acronym', 'name', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre Español')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Nombre Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('role_staff', models.BooleanField(default=False, verbose_name='Rol Personal')),
                ('role_cast', models.BooleanField(default=False, verbose_name='Rol Elenco')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Ros Película',
                'verbose_name_plural': 'Roles Películas',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'name_esp', 'role_staff', 'role_cast')},
            },
        ),
        migrations.CreateModel(
            name='SerieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha Añadido')),
                ('process', models.TextField(default='', verbose_name='Proceso')),
                ('level', models.CharField(default='INFO', max_length=10, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Log Serie',
                'verbose_name_plural': 'Logs Serie',
                'db_table': 'log_Serie',
                'ordering': ['-timestamp'],
                'unique_together': {('level', 'process', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre Español')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Nombre Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('delete', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='serie.type', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Tipo Serie',
                'verbose_name_plural': 'Tipos Series',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título Original')),
                ('title_secundary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título Secundario')),
                ('release_year', core.utils.utils.YearField(blank=True, null=True, validators=[core.utils.utils.validate_year], verbose_name='Año Lanzamiento')),
                ('ending_year', core.utils.utils.YearField(blank=True, null=True, validators=[core.utils.utils.validate_year], verbose_name='Año Termino')),
                ('episodes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Episodios')),
                ('synopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('distributors', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='series_as_distributors', to='serie.company', verbose_name='Distribuidoras')),
                ('genres', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='series_as_genre', to='serie.genre', verbose_name='Géneros')),
                ('producers', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='series_as_producers', to='serie.company', verbose_name='Productoras')),
                ('serie_rating', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_ratings', to='serie.rating', verbose_name='Clasificación Serie')),
                ('serie_types', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_types', to='serie.type', verbose_name='Tipo Serie')),
            ],
            options={
                'verbose_name': 'Serie',
                'verbose_name_plural': 'Series',
                'ordering': ['-created_at', 'title'],
                'unique_together': {('title', 'title_secundary', 'release_year')},
            },
        ),
        migrations.CreateModel(
            name='SerieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100, verbose_name='Personaje')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Personaje Slug')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('actor', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='persons_as_serie_cast_roles', to='common.person', verbose_name='Actor')),
                ('role', models.ForeignKey(limit_choices_to={'is_active': True, 'role_cast': True}, on_delete=django.db.models.deletion.CASCADE, related_name='actors_as_roles', to='serie.role', verbose_name='Rol')),
                ('serie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_casts', to='serie.serie', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Reparto Serie',
                'verbose_name_plural': 'Reparto Series',
                'ordering': ['serie', 'actor', 'character_name'],
                'unique_together': {('serie', 'actor', 'role', 'character_name')},
            },
        ),
        migrations.CreateModel(
            name='SerieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.serie.utils.uploads.serie_image_path, verbose_name='Imagen Serie')),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL')),
                ('name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('serie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_images', to='serie.serie', verbose_name='Serie')),
                ('size_image', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='series_images_as_sizes', to='common.imagesize', verbose_name='Tamaño')),
            ],
            options={
                'verbose_name': 'Imagen Serie',
                'verbose_name_plural': 'Imágenes Series',
                'ordering': ['serie', 'size_image', 'name'],
                'unique_together': {('serie', 'size_image', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SerieImageExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.serie.utils.uploads.serie_image_extra_path, verbose_name='Imagen Extra Serie')),
                ('name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('serie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_images_exta', to='serie.serie', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Imagen Extra Serie',
                'verbose_name_plural': 'Imágenes Extra Series',
                'ordering': ['serie', 'name'],
                'unique_together': {('serie', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SerieStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('person', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_persons', to='common.person', verbose_name='Persona')),
                ('role', models.ForeignKey(limit_choices_to={'is_active': True, 'role_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='persons_as_serie_staff_roles', to='serie.role', verbose_name='Rol')),
                ('serie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_staffs', to='serie.serie', verbose_name='Serie')),
            ],
            options={
                'verbose_name': 'Personal Película',
                'verbose_name_plural': 'Personal Películas',
                'ordering': ['serie', 'role', 'person'],
                'unique_together': {('serie', 'role', 'person')},
            },
        ),
        migrations.CreateModel(
            name='TitleSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, verbose_name='Título Slug')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('serie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='series_as_title', to='serie.serie', verbose_name='Serie')),
                ('title_lang', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='titles_series_as_languages', to='common.language', verbose_name='Lenguaje')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ['title_lang', 'initial', 'title'],
                'unique_together': {('title_lang', 'title', 'serie')},
            },
        ),
    ]
