# Generated by Django 5.2.1 on 2025-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renpy', '0002_alter_titlegame_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='games_as_developed', to='renpy.developer', verbose_name='Desarrollador'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='games_as_genre', to='renpy.genre', verbose_name='Géneros'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publishers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='games_as_published', to='renpy.publisher', verbose_name='Editor'),
        ),
        migrations.AlterField(
            model_name='game',
            name='translators',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='games_as_translated', to='renpy.translator', verbose_name='Traductores'),
        ),
    ]
