# Generated by Django 5.2.1 on 2025-05-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temp_animesong',
            table='temp_anime_song',
        ),
    ]
