# Generated by Django 5.2.1 on 2025-05-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataanime',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de anime (MAL)', 'verbose_name_plural': 'Datos de animes (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='dataanimecharacters',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de personaje de anime (MAL)', 'verbose_name_plural': 'Datos de personajes de animes (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='dataanimepictures',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de imagen de anime (MAL)', 'verbose_name_plural': 'Datos de imágenes de animes (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='dataanimestaff',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de personal de anime (MAL)', 'verbose_name_plural': 'Datos de personal de animes (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='datacharacter',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de personaje (MAL)', 'verbose_name_plural': 'Datos de personajes (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='datacharacterpictures',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de imagen de personaje (MAL)', 'verbose_name_plural': 'Datos de imágenes de personajes (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='dataimageurl',
            options={'ordering': ['-created_at', 'url'], 'verbose_name': 'Dato de imagen URL (MAL)', 'verbose_name_plural': 'Datos de imágenes de URL (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='datamanga',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de manga (MAL)', 'verbose_name_plural': 'Datos de mangas (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='datamangacharacters',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de personaje de manga (MAL)', 'verbose_name_plural': 'Datos de personajes de mangas (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='datamangapictures',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de imagen de manga (MAL)', 'verbose_name_plural': 'Datos de imágenes de mangas (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='dataotakuperson',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de persona (MAL)', 'verbose_name_plural': 'Datos de personas (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='dataotakupersonpictures',
            options={'ordering': ['-created_at', 'mal_id'], 'verbose_name': 'Dato de imagen de persona (MAL)', 'verbose_name_plural': 'Datos de imágenes de personas (MAL)'},
        ),
        migrations.AlterModelOptions(
            name='temp_characters',
            options={'verbose_name': 'Temp. Personaje', 'verbose_name_plural': 'Temp. Personajes'},
        ),
        migrations.AlterModelOptions(
            name='temp_otakupersons',
            options={'verbose_name': 'Temp. Otaku Persona', 'verbose_name_plural': 'Temp. Otaku Personas'},
        ),
    ]
