# Generated by Django 5.2.1 on 2025-05-16 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_personimageextra_options_and_more'),
        ('otaku', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titleanime',
            name='title_lang',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='titles_animes_as_languages', to='common.language', verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='titlemanga',
            name='title_lang',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='titles_mangas_as_languages', to='common.language', verbose_name='Idioma'),
        ),
    ]
