default_serie_genres = [
    {'name': 'Action', 'name_esp': 'Acción', 'is_active': True, 'explicit': False, 'description': 'Series con escenas de lucha, persecuciones y mucha adrenalina.',},
    {'name': 'Adventure', 'name_esp': 'Aventura', 'is_active': True, 'explicit': False, 'description': 'Series con viajes emocionantes y exploración de lugares desconocidos.',},
    {'name': 'Comedy', 'name_esp': 'Comedia', 'is_active': True, 'explicit': False, 'description': 'Series diseñadas para hacer reír al público.',},
    {'name': 'Drama', 'name_esp': 'Drama', 'is_active': True, 'explicit': False, 'description': 'Series que exploran conflictos emocionales y situaciones de la vida real.',},
    {'name': 'Science Fiction', 'name_esp': 'Ciencia Ficción', 'is_active': True, 'explicit': False, 'description': 'Series con elementos científicos y tecnológicos especulativos.',},
    {'name': 'Fantasy', 'name_esp': 'Fantasía', 'is_active': True, 'explicit': False, 'description': 'Series con elementos mágicos, criaturas míticas y mundos imaginarios.',},
    {'name': 'Horror', 'name_esp': 'Terror', 'is_active': True, 'explicit': False, 'description': 'Series que buscan asustar, causar miedo y repulsión.',},
    {'name': 'Thriller', 'name_esp': 'Suspenso', 'is_active': True, 'explicit': False, 'description': 'Series que generan tensión e incertidumbre en el espectador.',},
    {'name': 'Animation', 'name_esp': 'Animación', 'is_active': True, 'explicit': False, 'description': 'Series creadas mediante la técnica de animación.',},
    {'name': 'Romance', 'name_esp': 'Romance', 'is_active': True, 'explicit': False, 'description': 'Series centradas en relaciones amorosas y emocionales.',},
    {'name': 'Crime', 'name_esp': 'Crimen', 'is_active': True, 'explicit': False, 'description': 'Series que giran en torno a actividades delictivas y sus consecuencias.',},
    {'name': 'Mystery', 'name_esp': 'Misterio', 'is_active': True, 'explicit': False, 'description': 'Series que presentan enigmas y secretos que deben ser resueltos.',},
    {'name': 'Historical', 'name_esp': 'Histórico', 'is_active': True, 'explicit': False, 'description': 'Series basadas en eventos o personajes del pasado.',},
    {'name': 'Western', 'name_esp': 'Oeste', 'is_active': True, 'explicit': False, 'description': 'Series ambientadas en el Viejo Oeste americano.',},
    {'name': 'Family', 'name_esp': 'Familiar', 'is_active': True, 'explicit': False, 'description': 'Series aptas para ser disfrutadas por toda la familia.',},
    {'name': 'Melodrama', 'name_esp': 'Melodrama', 'is_active': False, 'explicit': False, 'description': '',},
]

default_serie_types = [
    {'name': 'Documentary', 'name_esp': 'Documental', 'is_active': True, 'description': 'Series que presentan hechos reales con fines informativos o de análisis.',},
    {'name': 'Animated Feature Film', 'name_esp': 'Largometraje Animado', 'is_active': True, 'description': 'Series de animación de larga duración.',},
    {'name': 'Live-Action Feature Film', 'name_esp': 'Largometraje de Acción Real', 'is_active': True, 'description': 'Series con actores reales.',},
    {'name': 'Short Film', 'name_esp': 'Cortometraje', 'is_active': True, 'description': 'Series de corta duración.',},
    {'name': 'TV Movie', 'name_esp': 'Serie para Televisión', 'is_active': True, 'description': 'Series producidas para ser emitidas en televisión.',},
    {'name': 'Direct-to-Video', 'name_esp': 'Directo a Video', 'is_active': True, 'description': 'Series lanzadas directamente en formato de video.',},
    {'name': 'Independent Film', 'name_esp': 'Serie Independiente', 'is_active': True, 'description': 'Series producidas fuera de los grandes estudios.',},
    {'name': 'Experimental Film', 'name_esp': 'Serie Experimental', 'is_active': True, 'description': 'Series que desafían las convenciones narrativas y formales.',},
]

default_serie_roles = [
    {'name': 'Lead', 'name_esp': 'Principal', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'El actor o actriz que interpreta al personaje central de la serie.',},
    {'name': 'Supporting', 'name_esp': 'Actor de Reparto', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Un actor o actrizque interpreta un personaje secundario importante.',},
    {'name': 'Cameo', 'name_esp': 'Cameo', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Una aparición breve de una persona famosa en la serie.',},
    {'name': 'Voice Actor', 'name_esp': 'Actor de Voz', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Un actor que proporciona la voz de un personaje animado o digital.',},
    {'name': 'Narrator', 'name_esp': 'Narrador', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'La voz en off que cuenta parte de la historia.',},
    {'name': 'Extra', 'name_esp': 'Extra Destacado', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Un extra con una participación ligeramente más notable.',},
    {'name': 'Director', 'name_esp': 'Director', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la visión creativa general de la serie.',},
    {'name': 'Screenwriter', 'name_esp': 'Guionista', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona que escribe el guion de la serie.',},
    {'name': 'Producer', 'name_esp': 'Productor', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la gestión y financiación de la serie.',},
    {'name': 'Cinematographer', 'name_esp': 'Director de Fotografía', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la filmación y el aspecto visual de la serie.',},
    {'name': 'Film Editor', 'name_esp': 'Montajista', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona que ensambla las diferentes tomas para crear la serie final.',},
    {'name': 'Production Designer', 'name_esp': 'Diseñador de Producción', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable del aspecto visual del set y los escenarios.',},
    {'name': 'Costume Designer', 'name_esp': 'Diseñador de Vestuario', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable del vestuario de los personajes.',},
    {'name': 'Composer', 'name_esp': 'Compositor', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona que escribe la música original para la serie.',},
    {'name': 'Sound Designer', 'name_esp': 'Diseñador de Sonido', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable del diseño y la mezcla del sonido de la serie.',},
    {'name': 'Art Director', 'name_esp': 'Director de Arte', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la supervisión de los aspectos visuales de la serie.',},
    {'name': 'Casting Director', 'name_esp': 'Director de Casting', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de seleccionar a los actores para los roles.',},
    {'name': 'Visual Effects Supervisor', 'name_esp': 'Supervisor de Efectos Visuales', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la creación de los efectos visuales.',},
    # Roles de Casting
    {'name': 'Lead', 'name_esp': 'Principal', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'El actor o actriz que interpreta al personaje central de la serie.',},
    {'name': 'Supporting', 'name_esp': 'Actor de Reparto', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Un actor o actrizque interpreta un personaje secundario importante.',},
    {'name': 'Cameo', 'name_esp': 'Cameo', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Una aparición breve de una persona famosa en la serie.',},
    {'name': 'Voice Actor', 'name_esp': 'Actor de Voz', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Un actor que proporciona la voz de un personaje animado o digital.',},
    {'name': 'Narrator', 'name_esp': 'Narrador', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'La voz en off que cuenta parte de la historia.',},
    {'name': 'Extra', 'name_esp': 'Extra Destacado', 'role_cast': True, 'role_staff': False, 'is_active': True, 'description': 'Un extra con una participación ligeramente más notable.',},
    {'name': 'Director', 'name_esp': 'Director', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la visión creativa general de la serie.',},
    {'name': 'Screenwriter', 'name_esp': 'Guionista', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona que escribe el guion de la serie.',},
    {'name': 'Producer', 'name_esp': 'Productor', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la gestión y financiación de la serie.',},
    {'name': 'Cinematographer', 'name_esp': 'Director de Fotografía', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la filmación y el aspecto visual de la serie.',},
    {'name': 'Film Editor', 'name_esp': 'Montajista', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona que ensambla las diferentes tomas para crear la serie final.',},
    {'name': 'Production Designer', 'name_esp': 'Diseñador de Producción', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable del aspecto visual del set y los escenarios.',},
    {'name': 'Costume Designer', 'name_esp': 'Diseñador de Vestuario', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable del vestuario de los personajes.',},
    {'name': 'Composer', 'name_esp': 'Compositor', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona que escribe la música original para la serie.',},
    {'name': 'Sound Designer', 'name_esp': 'Diseñador de Sonido', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable del diseño y la mezcla del sonido de la serie.',},
    {'name': 'Art Director', 'name_esp': 'Director de Arte', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la supervisión de los aspectos visuales de la serie.',},
    {'name': 'Casting Director', 'name_esp': 'Director de Casting', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de seleccionar a los actores para los roles.',},
    {'name': 'Visual Effects Supervisor', 'name_esp': 'Supervisor de Efectos Visuales', 'role_cast': False, 'role_staff': True, 'is_active': True, 'description': 'La persona responsable de la creación de los efectos visuales.',},
]

default_serie_ratings = [
    {'acronym': 'TV-Y', 'name': 'Preschool children: children under 6 years old.', 'name_esp': 'Público preinfantil: niños menores de 6 años.', 'is_active': True, 'description': 'Esta clasificación está diseñada para niños muy pequeños, menores de 6 años. El contenido en esta categoría se considera apropiado para todos los niños en este grupo de edad.',},
    {'acronym': 'TV-Y7', 'name': 'Children\'s audience: 7 years and up.', 'name_esp': 'Público infantil: desde 7 años.', 'is_active': True, 'description': 'Esta clasificación es para programas dirigidos a niños a partir de los 7 años. El contenido está diseñado para ser apropiado para niños, pero puede contener temas más complejos o elementos de fantasía que podrían no ser adecuados para niños más pequeños.',},
    {'acronym': 'TV-Y7-FV', 'name': 'Children\'s audience with fictional violence, fantasy, or intense emotions: 7 years and up.', 'name_esp': 'Público infantil con violencia ficticia, de fantasía ó emociones fuertes: desde 7 años.', 'is_active': True, 'description': 'Similar a TV-Y7, esta clasificación también está dirigida a niños de 7 años en adelante. La adición de "-FV" indica que el programa puede contener violencia de naturaleza ficticia o de fantasía, o presentar emociones más intensas que podrían ser más adecuadas para este grupo de edad.',},
    {'acronym': 'TV-G', 'name': 'General audience.', 'name_esp': 'Público general.', 'is_active': True, 'description': 'Los programas con esta clasificación se consideran apropiados para todas las edades. No contienen material que los padres puedan considerar inadecuado para niños.',},
    {'acronym': 'TV-PG', 'name': 'Parental guidance: Parental supervision suggested.', 'name_esp': 'Guía paterna: Supervisión paternal.', 'is_active': True, 'description': 'Se sugiere la supervisión de los padres para programas con esta clasificación. El contenido puede contener material que los padres podrían considerar inadecuado para niños pequeños, como violencia leve, algo de lenguaje sugestivo o temas ligeramente más maduros.',},
    {'acronym': 'TV-14', 'name': 'Viewers over 14 years old: Parental guidance strongly advised.', 'name_esp': 'Mayores de 14 años: Se requiere enfáticamente la compañía de los padres.', 'is_active': True, 'description': 'Esta clasificación advierte que el programa puede contener material que no es adecuado para niños menores de 14 años. Se aconseja encarecidamente a los padres que vean el programa con sus hijos menores de esta edad. El contenido podría incluir violencia más intensa, lenguaje más fuerte, temas sexuales sugestivos o diálogos más complejos.',},
    {'acronym': 'TV-MA', 'name': 'Mature audience (17 years and up).', 'name_esp': 'Mayores de 17 años.', 'is_active': True, 'description': 'Esta clasificación está reservada para programas que se consideran adecuados solo para audiencias adultas (mayores de 17 años). El contenido puede incluir violencia gráfica, lenguaje explícito, contenido sexual intenso o temas adultos.',},
]


