# Generated by Django 5.2.1 on 2025-05-11 22:19

import apps.common.utils.uploads
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha Añadido')),
                ('process', models.TextField(default='', verbose_name='Proceso')),
                ('level', models.CharField(default='INFO', max_length=10, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Log General',
                'verbose_name_plural': 'Logs General',
                'db_table': 'log_Common',
                'ordering': ['-timestamp'],
                'unique_together': {('level', 'process', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(max_length=60, unique=True, verbose_name='Nombre Español')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('initial_esp', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial Español')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=60, unique=True, verbose_name='Nombre Slug')),
                ('code', models.CharField(blank=True, max_length=4, verbose_name='Código')),
                ('numeric_code', models.PositiveIntegerField(blank=True, default=0, verbose_name='Código Numerico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['initial', 'name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('for_video', models.BooleanField(default=False, verbose_name='Videos')),
                ('for_music', models.BooleanField(default=False, verbose_name='Música')),
                ('for_image', models.BooleanField(default=False, verbose_name='Imágenes')),
                ('for_document', models.BooleanField(default=False, verbose_name='Documentos')),
                ('for_other', models.BooleanField(default=False, verbose_name='Otros')),
                ('slug', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Nombre Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Formato',
                'verbose_name_plural': 'Formatos',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='ImageSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(max_length=20, verbose_name='Nombre Español')),
                ('slug', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Tamaño de Imagen',
                'verbose_name_plural': 'Tamaños de Imágenes',
                'ordering': ['name'],
                'unique_together': {('name', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nombre Español')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Acrónimo')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'acronym', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nombre Completo')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('biography', models.TextField(blank=True, verbose_name='Biografía')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('country', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons_as_countries', to='common.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
                'ordering': ['initial', 'full_name'],
                'unique_together': {('initial', 'full_name')},
            },
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('slug', models.CharField(blank=True, editable=False, max_length=10, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Calidad',
                'verbose_name_plural': 'Calidades',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('acronym', models.CharField(max_length=5, unique=True, verbose_name='Acrónimo')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='URL')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Sitio Web',
                'verbose_name_plural': 'Sitios Webs',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'acronym', 'url')},
            },
        ),
        migrations.CreateModel(
            name='PersonImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.common.utils.uploads.person_image_path, verbose_name='Imagen Persona')),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL')),
                ('name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('person', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='persons_as_images', to='common.person', verbose_name='Persona')),
                ('size_image', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='persons_images_as_sizes', to='common.imagesize', verbose_name='Tamaño')),
            ],
            options={
                'verbose_name': 'Imagen Persona',
                'verbose_name_plural': 'Imágenes Personas',
                'ordering': ['person', 'size_image', 'name'],
                'unique_together': {('person', 'size_image', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PersonImageExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.common.utils.uploads.person_image_extra_path, verbose_name='Imagen Extra Persona')),
                ('name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=150, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('person', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='persons_as_exta_images', to='common.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Imágen extra persona',
                'verbose_name_plural': 'Imágenes extras de personas',
                'ordering': ['person', 'name'],
                'unique_together': {('person', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PersonNickname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, verbose_name='Apodo')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Apodo Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('person', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='persons_as_nicknames', to='common.person', verbose_name='Persona')),
            ],
            options={
                'verbose_name': 'Apodo Persona',
                'verbose_name_plural': 'Apodos Persona',
                'ordering': ['initial', 'nickname'],
                'unique_together': {('person', 'initial', 'nickname')},
            },
        ),
    ]
