# Generated by Django 5.2.1 on 2025-05-14 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['created_at', 'name'], 'verbose_name': 'Idioma', 'verbose_name_plural': 'Idiomas'},
        ),
    ]
