# Generated by Django 5.2.1 on 2025-05-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commonlog',
            table='log_Common',
        ),
    ]
