# Generated by Django 5.2.1 on 2025-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_commonlog_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha Añadido'),
        ),
    ]
