# Generated by Django 5.2.1 on 2025-05-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_language_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personimageextra',
            options={'ordering': ['person', 'name'], 'verbose_name': 'Imagen extra persona', 'verbose_name_plural': 'Imágenes extras de personas'},
        ),
        migrations.AlterField(
            model_name='country',
            name='numeric_code',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Código Numérico'),
        ),
    ]
