# Generated by Django 5.2.1 on 2025-05-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_personimageextra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personimage',
            name='name',
            field=models.CharField(editable=False, max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personimage',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150, verbose_name='Nombre Slug'),
        ),
    ]
