# Generated by Django 5.2.1 on 2025-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='acepto_terminos',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=150, unique=True, verbose_name='Nombre Slug'),
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha Añadido')),
                ('process', models.TextField(default='', verbose_name='Proceso')),
                ('level', models.CharField(default='INFO', max_length=10, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Log Usuario',
                'verbose_name_plural': 'Logs Usuarios',
                'db_table': 'log_Usuario',
                'ordering': ['-timestamp'],
                'unique_together': {('level', 'process', 'timestamp')},
            },
        ),
    ]
