default_music_genres = [
    {'name': 'Acid Jazz', 'name_esp': 'Acid Jazz', 'is_active': True,},
    {'name': 'Acoustic Folk', 'name_esp': 'Folk Acústico', 'is_active': True,},
    {'name': 'African Music', 'name_esp': 'Música Africana', 'is_active': True,},
    {'name': 'Afrobeat', 'name_esp': 'Afrobeat', 'is_active': True,},
    {'name': 'Alternative Country', 'name_esp': 'Country Alternativo', 'is_active': True,},
    {'name': 'Alternative J-rock', 'name_esp': 'J-rock Alternativo', 'is_active': True,},
    {'name': 'Alternative Pop', 'name_esp': 'Pop Alternativo', 'is_active': True,},
    {'name': 'Alternative Rock', 'name_esp': 'Rock Alternativo', 'is_active': True,},
    {'name': 'Ambient', 'name_esp': 'Ambient', 'is_active': True,},
    {'name': 'Ambient Pop', 'name_esp': 'Pop Ambiental', 'is_active': True,},
    {'name': 'Anime Instrumental', 'name_esp': 'Instrumental de Anime', 'is_active': True,},
    {'name': 'Anison (Anime Song)', 'name_esp': 'Anison (Canción de Anime)', 'is_active': True,},
    {'name': 'Anime Soundtrack', 'name_esp': 'Banda Sonora de Anime', 'is_active': True,},
    {'name': 'Arena Rock', 'name_esp': 'Arena Rock', 'is_active': True,},
    {'name': 'Art Rock', 'name_esp': 'Rock Artístico', 'is_active': True,},
    {'name': 'Asian Music', 'name_esp': 'Música Asiática', 'is_active': True,},
    {'name': 'Avant-Garde', 'name_esp': 'Avant-Garde', 'is_active': True,},
    {'name': 'Bachata', 'name_esp': 'Bachata', 'is_active': True,},
    {'name': 'Baroque', 'name_esp': 'Barroco', 'is_active': True,},
    {'name': 'Bebop', 'name_esp': 'Bebop', 'is_active': True,},
    {'name': 'Bhangra', 'name_esp': 'Bhangra', 'is_active': True,},
    {'name': 'Big Band', 'name_esp': 'Big Band', 'is_active': True,},
    {'name': 'Big Room House', 'name_esp': 'Big Room House', 'is_active': True,},
    {'name': 'Black Metal', 'name_esp': 'Black Metal', 'is_active': True,},
    {'name': 'Bluegrass', 'name_esp': 'Bluegrass', 'is_active': True,},
    {'name': 'Blues', 'name_esp': 'Blues', 'is_active': True,},
    {'name': 'Blues Rock', 'name_esp': 'Blues Rock', 'is_active': True,},
    {'name': 'Bossa Nova', 'name_esp': 'Bossa Nova', 'is_active': True,},
    {'name': 'Breakbeat', 'name_esp': 'Breakbeat', 'is_active': True,},
    {'name': 'Britpop', 'name_esp': 'Britpop', 'is_active': True,},
    {'name': 'Calypso', 'name_esp': 'Calipso', 'is_active': True,},
    {'name': 'Celtic Music', 'name_esp': 'Música Celta', 'is_active': True,},
    {'name': 'Cha-Cha-Chá', 'name_esp': 'Cha-Cha-Chá', 'is_active': True,},
    {'name': 'Chamber Folk', 'name_esp': 'Folk de Cámara', 'is_active': True,},
    {'name': 'Chicago Blues', 'name_esp': 'Blues de Chicago', 'is_active': True,},
    {'name': 'Children\'s Music', 'name_esp': 'Música para Niños', 'is_active': True,},
    {'name': 'Chillwave', 'name_esp': 'Chillwave', 'is_active': True,},
    {'name': 'Classic Rock', 'name_esp': 'Rock Clásico', 'is_active': True,},
    {'name': 'Classical', 'name_esp': 'Classical', 'is_active': True,},
    {'name': 'Classical', 'name_esp': 'Clásica', 'is_active': True,},
    {'name': 'Classical Music', 'name_esp': 'Música Clásica', 'is_active': True,},
    {'name': 'Classical Period', 'name_esp': 'Período Clásico', 'is_active': True,},
    {'name': 'Contemporary Classical', 'name_esp': 'Clásica Contemporánea', 'is_active': True,},
    {'name': 'Contemporary Gospel', 'name_esp': 'Gospel Contemporáneo', 'is_active': True,},
    {'name': 'Contemporary R&B', 'name_esp': 'R&B Contemporáneo', 'is_active': True,},
    {'name': 'Cool Jazz', 'name_esp': 'Cool Jazz', 'is_active': True,},
    {'name': 'Corrido', 'name_esp': 'Corrido', 'is_active': True,},
    {'name': 'Country', 'name_esp': 'Country', 'is_active': True,},
    {'name': 'Country Pop', 'name_esp': 'Country Pop', 'is_active': True,},
    {'name': 'Country Rock', 'name_esp': 'Country Rock', 'is_active': True,},
    {'name': 'C-pop', 'name_esp': 'C-pop', 'is_active': True,},
    {'name': 'Cumbia', 'name_esp': 'Cumbia', 'is_active': True,},
    {'name': 'Dancehall', 'name_esp': 'Dancehall', 'is_active': True,},
    {'name': 'Dance-pop', 'name_esp': 'Dance-pop', 'is_active': True,},
    {'name': 'Dark Ambient', 'name_esp': 'Ambient Oscuro', 'is_active': True,},
    {'name': 'Dark Wave', 'name_esp': 'Dark Wave', 'is_active': True,},
    {'name': 'Death Metal', 'name_esp': 'Death Metal', 'is_active': True,},
    {'name': 'Deep House', 'name_esp': 'Deep House', 'is_active': True,},
    {'name': 'Delta Blues', 'name_esp': 'Blues del Delta', 'is_active': True,},
    {'name': 'Delta Blues', 'name_esp': 'Delta Blues', 'is_active': True,},
    {'name': 'Dixieland', 'name_esp': 'Dixieland', 'is_active': True,},
    {'name': 'Djent', 'name_esp': 'Djent', 'is_active': True,},
    {'name': 'Doom Metal', 'name_esp': 'Doom Metal', 'is_active': True,},
    {'name': 'Downtempo', 'name_esp': 'Downtempo', 'is_active': True,},
    {'name': 'Drone', 'name_esp': 'Drone', 'is_active': True,},
    {'name': 'Drum and Bass', 'name_esp': 'Drum and Bass', 'is_active': True,},
    {'name': 'Dub', 'name_esp': 'Dub', 'is_active': True,},
    {'name': 'Dubstep', 'name_esp': 'Dubstep', 'is_active': True,},
    {'name': 'Easy Listening', 'name_esp': 'Música Ligera', 'is_active': True,},
    {'name': 'Electric Blues', 'name_esp': 'Blues Eléctrico', 'is_active': True,},
    {'name': 'Electro House', 'name_esp': 'Electro House', 'is_active': True,},
    {'name': 'Electronic', 'name_esp': 'Electrónica', 'is_active': True,},
    {'name': 'Electronic Body Music (EBM)', 'name_esp': 'Música Electrónica Corporal (EBM)', 'is_active': True,},
    {'name': 'Electronic Dance Music (EDM)', 'name_esp': 'Música Electrónica de Baile (EDM)', 'is_active': True,},
    {'name': 'Electronic Music', 'name_esp': 'Música Electrónica', 'is_active': True,},
    {'name': 'Electropop', 'name_esp': 'Electropop', 'is_active': True,},
    {'name': 'Emo', 'name_esp': 'Emo', 'is_active': True,},
    {'name': 'Eurodance', 'name_esp': 'Eurodance', 'is_active': True,},
    {'name': 'Experimental Music', 'name_esp': 'Música Experimental', 'is_active': True,},
    {'name': 'Experimental Rock', 'name_esp': 'Rock Experimental', 'is_active': True,},
    {'name': 'Film Score', 'name_esp': 'Banda Sonora de Películas', 'is_active': True,},
    {'name': 'Flamenco', 'name_esp': 'Flamenco', 'is_active': True,},
    {'name': 'Folk', 'name_esp': 'Folk', 'is_active': True,},
    {'name': 'Folk Metal', 'name_esp': 'Folk Metal', 'is_active': True,},
    {'name': 'Folk Pop', 'name_esp': 'Folk Pop', 'is_active': True,},
    {'name': 'Folk Rock', 'name_esp': 'Folk Rock', 'is_active': True,},
    {'name': 'Free Jazz', 'name_esp': 'Free Jazz', 'is_active': True,},
    {'name': 'Funk', 'name_esp': 'Funk', 'is_active': True,},
    {'name': 'Fusion', 'name_esp': 'Fusión', 'is_active': True,},
    {'name': 'Future Bass', 'name_esp': 'Future Bass', 'is_active': True,},
    {'name': 'Gamelan', 'name_esp': 'Gamelan', 'is_active': True,},
    {'name': 'Gangsta Rap', 'name_esp': 'Gangsta Rap', 'is_active': True,},
    {'name': 'Garage', 'name_esp': 'Garage', 'is_active': True,},
    {'name': 'Glam Metal', 'name_esp': 'Glam Metal', 'is_active': True,},
    {'name': 'Glitch', 'name_esp': 'Glitch', 'is_active': True,},
    {'name': 'Gospel', 'name_esp': 'Gospel', 'is_active': True,},
    {'name': 'Gothic Metal', 'name_esp': 'Metal Gótico', 'is_active': True,},
    {'name': 'Gothic Rock', 'name_esp': 'Rock Gótico', 'is_active': True,},
    {'name': 'Grime', 'name_esp': 'Grime', 'is_active': True,},
    {'name': 'Groove Metal', 'name_esp': 'Groove Metal', 'is_active': True,},
    {'name': 'Grunge', 'name_esp': 'Grunge', 'is_active': True,},
    {'name': 'Hard Rock', 'name_esp': 'Hard Rock', 'is_active': True,},
    {'name': 'Hardcore Punk', 'name_esp': 'Hardcore Punk', 'is_active': True,},
    {'name': 'Heavy J-rock', 'name_esp': 'J-rock Pesado', 'is_active': True,},
    {'name': 'Heavy Metal', 'name_esp': 'Heavy Metal', 'is_active': True,},
    {'name': 'Highlife', 'name_esp': 'Highlife', 'is_active': True,},
    {'name': 'Hip Hop', 'name_esp': 'Hip Hop', 'is_active': True,},
    {'name': 'House', 'name_esp': 'House', 'is_active': True,},
    {'name': 'IDM (Intelligent Dance Music)', 'name_esp': 'IDM (Música Electrónica Inteligente)', 'is_active': True,},
    {'name': 'Idol Pop', 'name_esp': 'Pop de Idols', 'is_active': True,},
    {'name': 'Indie', 'name_esp': 'Indie', 'is_active': True,},
    {'name': 'Indie Folk', 'name_esp': 'Folk Indie', 'is_active': True,},
    {'name': 'Indie Pop', 'name_esp': 'Indie Pop', 'is_active': True,},
    {'name': 'Indie Pop', 'name_esp': 'Pop Indie', 'is_active': True,},
    {'name': 'Indie Rock', 'name_esp': 'Indie Rock', 'is_active': True,},
    {'name': 'Indie Rock', 'name_esp': 'Rock Indie', 'is_active': True,},
    {'name': 'Indietronica', 'name_esp': 'Indietrónica', 'is_active': True,},
    {'name': 'Industrial', 'name_esp': 'Industrial', 'is_active': True,},
    {'name': 'Industrial Metal', 'name_esp': 'Metal Industrial', 'is_active': True,},
    {'name': 'Industrial Rock', 'name_esp': 'Rock Industrial', 'is_active': True,},
    {'name': 'Instrumental Pop', 'name_esp': 'Pop Instrumental', 'is_active': True,},
    {'name': 'Italo Disco', 'name_esp': 'Italo Disco', 'is_active': True,},
    {'name': 'Jazz', 'name_esp': 'Jazz', 'is_active': True,},
    {'name': 'Jazz Fusion', 'name_esp': 'Jazz Fusión', 'is_active': True,},
    {'name': 'J-Pop', 'name_esp': 'J-Pop', 'is_active': True,},
    {'name': 'J-Rock', 'name_esp': 'J-Rock', 'is_active': True,},
    {'name': 'Juju Music', 'name_esp': 'Música Juju', 'is_active': True,},
    {'name': 'Jungle', 'name_esp': 'Jungle', 'is_active': True,},
    {'name': 'K-Ballad', 'name_esp': 'Balada Coreana', 'is_active': True,},
    {'name': 'K-pop', 'name_esp': 'K-pop', 'is_active': True,},
    {'name': 'Krautrock', 'name_esp': 'Krautrock', 'is_active': True,},
    {'name': 'Latin', 'name_esp': 'Latina', 'is_active': True,},
    {'name': 'Latin Alternative', 'name_esp': 'Alternativa Latina', 'is_active': True,},
    {'name': 'Latin Dance', 'name_esp': 'Música Latina de Baile', 'is_active': True,},
    {'name': 'Latin Music', 'name_esp': 'Música Latina', 'is_active': True,},
    {'name': 'Latin Pop', 'name_esp': 'Pop Latino', 'is_active': True,},
    {'name': 'Latin Trap', 'name_esp': 'Trap Latino', 'is_active': True,},
    {'name': 'Liquid Drum and Bass', 'name_esp': 'Liquid Drum and Bass', 'is_active': True,},
    {'name': 'Lo-fi Hip Hop', 'name_esp': 'Lo-fi Hip Hop', 'is_active': True,},
    {'name': 'Lullabies', 'name_esp': 'Canciones de Cuna', 'is_active': True,},
    {'name': 'Mambo', 'name_esp': 'Mambo', 'is_active': True,},
    {'name': 'Mariachi', 'name_esp': 'Mariachi', 'is_active': True,},
    {'name': 'Math Rock', 'name_esp': 'Math Rock', 'is_active': True,},
    {'name': 'Meditation', 'name_esp': 'Meditación', 'is_active': True,},
    {'name': 'Merengue', 'name_esp': 'Merengue', 'is_active': True,},
    {'name': 'Merseybeat', 'name_esp': 'Merseybeat', 'is_active': True,},
    {'name': 'Metal', 'name_esp': 'Metal', 'is_active': True,},
    {'name': 'Middle Eastern Music', 'name_esp': 'Música del Medio Oriente', 'is_active': True,},
    {'name': 'Minimal Techno', 'name_esp': 'Techno Minimal', 'is_active': True,},
    {'name': 'Moombahton', 'name_esp': 'Moombahton', 'is_active': True,},
    {'name': 'Motown', 'name_esp': 'Motown', 'is_active': True,},
    {'name': 'Musical Theatre', 'name_esp': 'Teatro Musical', 'is_active': True,},
    {'name': 'Neo Soul', 'name_esp': 'Neo Soul', 'is_active': True,},
    {'name': 'New Age', 'name_esp': 'New Age', 'is_active': True,},
    {'name': 'New Flamenco', 'name_esp': 'Nuevo Flamenco', 'is_active': True,},
    {'name': 'New Romantic', 'name_esp': 'Nuevo Romántico', 'is_active': True,},
    {'name': 'New Wave', 'name_esp': 'New Wave', 'is_active': True,},
    {'name': 'Noise Rock', 'name_esp': 'Noise Rock', 'is_active': True,},
    {'name': 'Norteño', 'name_esp': 'Norteño', 'is_active': True,},
    {'name': 'Nu Metal', 'name_esp': 'Nu Metal', 'is_active': True,},
    {'name': 'Old School Hip Hop', 'name_esp': 'Hip Hop de la Vieja Escuela', 'is_active': True,},
    {'name': 'Opera', 'name_esp': 'Ópera', 'is_active': True,},
    {'name': 'P-Funk', 'name_esp': 'P-Funk', 'is_active': True,},
    {'name': 'Poetry', 'name_esp': 'Poesía', 'is_active': True,},
    {'name': 'Pop', 'name_esp': 'Pop', 'is_active': True,},
    {'name': 'Pop Punk', 'name_esp': 'Pop Punk', 'is_active': True,},
    {'name': 'Post-Hardcore', 'name_esp': 'Post-Hardcore', 'is_active': True,},
    {'name': 'Post-Punk', 'name_esp': 'Post-Punk', 'is_active': True,},
    {'name': 'Post-Rock', 'name_esp': 'Post-Rock', 'is_active': True,},
    {'name': 'Power Metal', 'name_esp': 'Power Metal', 'is_active': True,},
    {'name': 'Power Pop', 'name_esp': 'Power Pop', 'is_active': True,},
    {'name': 'Progressive Electronic', 'name_esp': 'Electrónica Progresiva', 'is_active': True,},
    {'name': 'Progressive House', 'name_esp': 'House Progresivo', 'is_active': True,},
    {'name': 'Progressive Metal', 'name_esp': 'Metal Progresivo', 'is_active': True,},
    {'name': 'Progressive Rock', 'name_esp': 'Rock Progresivo', 'is_active': True,},
    {'name': 'Progressive Trance', 'name_esp': 'Trance Progresivo', 'is_active': True,},
    {'name': 'Psychedelic Pop', 'name_esp': 'Pop Psicodélico', 'is_active': True,},
    {'name': 'Psychedelic Rock', 'name_esp': 'Rock Psicodélico', 'is_active': True,},
    {'name': 'Punk', 'name_esp': 'Punk', 'is_active': True,},
    {'name': 'Punk Rock', 'name_esp': 'Punk Rock', 'is_active': True,},
    {'name': 'Qawwali', 'name_esp': 'Qawwali', 'is_active': True,},
    {'name': 'R&B', 'name_esp': 'R&B', 'is_active': True,},
    {'name': 'Ranchera', 'name_esp': 'Ranchera', 'is_active': True,},
    {'name': 'Rap', 'name_esp': 'Rap', 'is_active': True,},
    {'name': 'Reggae', 'name_esp': 'Reggae', 'is_active': True,},
    {'name': 'Reggaeton', 'name_esp': 'Reggaetón', 'is_active': True,},
    {'name': 'Reggaeton Fusion', 'name_esp': 'Fusión de Reggaetón', 'is_active': True,},
    {'name': 'Regional Mexican', 'name_esp': 'Regional Mexicano', 'is_active': True,},
    {'name': 'Rock', 'name_esp': 'Rock', 'is_active': True,},
    {'name': 'Romantic Period', 'name_esp': 'Período Romántico', 'is_active': True,},
    {'name': 'Salsa', 'name_esp': 'Salsa', 'is_active': True,},
    {'name': 'Samba', 'name_esp': 'Samba', 'is_active': True,},
    {'name': 'Screamo', 'name_esp': 'Screamo', 'is_active': True,},
    {'name': 'Shoegaze', 'name_esp': 'Shoegaze', 'is_active': True,},
    {'name': 'Ska', 'name_esp': 'Ska', 'is_active': True,},
    {'name': 'Ska-Punk', 'name_esp': 'Ska-Punk', 'is_active': True,},
    {'name': 'Sludge Metal', 'name_esp': 'Sludge Metal', 'is_active': True,},
    {'name': 'Smooth Jazz', 'name_esp': 'Smooth Jazz', 'is_active': True,},
    {'name': 'Soul', 'name_esp': 'Soul', 'is_active': True,},
    {'name': 'Soul Jazz', 'name_esp': 'Soul Jazz', 'is_active': True,},
    {'name': 'Soundtrack', 'name_esp': 'Banda Sonora', 'is_active': True,},
    {'name': 'Southern Rock', 'name_esp': 'Rock Sureño', 'is_active': True,},
    {'name': 'Space Rock', 'name_esp': 'Space Rock', 'is_active': True,},
    {'name': 'Spirituals', 'name_esp': 'Espirituales', 'is_active': True,},
    {'name': 'Spoken Word', 'name_esp': 'Palabra Hablada', 'is_active': True,},
    {'name': 'Surf Rock', 'name_esp': 'Surf Rock', 'is_active': True,},
    {'name': 'Swing', 'name_esp': 'Swing', 'is_active': True,},
    {'name': 'Symphonic Metal', 'name_esp': 'Metal Sinfónico', 'is_active': True,},
    {'name': 'Symphonic Rock', 'name_esp': 'Rock Sinfónico', 'is_active': True,},
    {'name': 'Synth-pop', 'name_esp': 'Synth-pop', 'is_active': True,},
    {'name': 'Synthwave', 'name_esp': 'Synthwave', 'is_active': True,},
    {'name': 'Tango', 'name_esp': 'Tango', 'is_active': True,},
    {'name': 'Techno', 'name_esp': 'Techno', 'is_active': True,},
    {'name': 'Tejano', 'name_esp': 'Tejano', 'is_active': True,},
    {'name': 'Thrash Metal', 'name_esp': 'Thrash Metal', 'is_active': True,},
    {'name': 'Traditional Bluegrass', 'name_esp': 'Bluegrass Tradicional', 'is_active': True,},
    {'name': 'Traditional Country', 'name_esp': 'Country Tradicional', 'is_active': True,},
    {'name': 'Trance', 'name_esp': 'Trance', 'is_active': True,},
    {'name': 'Trap', 'name_esp': 'Trap', 'is_active': True,},
    {'name': 'Trip Hop', 'name_esp': 'Trip Hop', 'is_active': True,},
    {'name': 'Video Game Music', 'name_esp': 'Música de Videojuegos', 'is_active': True,},
    {'name': 'Video Game Soundtrack', 'name_esp': 'Banda Sonora de Videojuegos', 'is_active': True,},
    {'name': 'Visual Kei', 'name_esp': 'Visual Kei', 'is_active': True,},
    {'name': 'World Music', 'name_esp': 'Música del Mundo', 'is_active': True,},
    {'name': 'Worldbeat', 'name_esp': 'Worldbeat', 'is_active': True,},
    {'name': 'Zouk', 'name_esp': 'Zouk', 'is_active': True,},
]

default_music_roles = [
    {'name': 'Accordionist', 'name_esp': 'Acordeonista', 'is_active': True,},
    {'name': 'Arranger', 'name_esp': 'Arreglista', 'is_active': True,},
    {'name': 'Backing Band', 'name_esp': 'Banda de acompañamiento', 'is_active': True,},
    {'name': 'Backing Vocalist', 'name_esp': 'Corista', 'is_active': True,},
    {'name': 'Bandleader', 'name_esp': 'Director de banda', 'is_active': True,},
    {'name': 'Bassist', 'name_esp': 'Bajista', 'is_active': True,},
    {'name': 'Brass Section', 'name_esp': 'Sección de metales', 'is_active': True,},
    {'name': 'Cellist', 'name_esp': 'Violonchelista', 'is_active': True,},
    {'name': 'Choir', 'name_esp': 'Coro', 'is_active': True,},
    {'name': 'Choreographer', 'name_esp': 'Coreógrafo', 'is_active': True,},
    {'name': 'Composer', 'name_esp': 'Compositor', 'is_active': True,},
    {'name': 'Conductor', 'name_esp': 'Director de orquesta', 'is_active': True,},
    {'name': 'Dancer', 'name_esp': 'Bailarín', 'is_active': True,},
    {'name': 'DJ', 'name_esp': 'DJ', 'is_active': True,},
    {'name': 'Drummer', 'name_esp': 'Baterista', 'is_active': True,},
    {'name': 'Flutist', 'name_esp': 'Flautista', 'is_active': True,},
    {'name': 'Guitarist', 'name_esp': 'Guitarrista', 'is_active': True,},
    {'name': 'Harpist', 'name_esp': 'Arpista', 'is_active': True,},
    {'name': 'Keyboardist', 'name_esp': 'Tecladista', 'is_active': True,},
    {'name': 'Lead Guitarist', 'name_esp': 'Guitarrista Principal', 'is_active': True,},
    {'name': 'Lighting Designer', 'name_esp': 'Diseñador de iluminación', 'is_active': True,},
    {'name': 'Lyricist', 'name_esp': 'Letrista', 'is_active': True,},
    {'name': 'Manager', 'name_esp': 'Mánager', 'is_active': True,},
    {'name': 'Orchestra', 'name_esp': 'Orquesta', 'is_active': True,},
    {'name': 'Percussionist', 'name_esp': 'Percusionista', 'is_active': True,},
    {'name': 'Pianist', 'name_esp': 'Pianista', 'is_active': True,},
    {'name': 'Producer', 'name_esp': 'Productor', 'is_active': True,},
    {'name': 'Publicist', 'name_esp': 'Publicista', 'is_active': True,},
    {'name': 'Rhythm Guitarist', 'name_esp': 'Guitarrista Rítmico', 'is_active': True,},
    {'name': 'Roadie', 'name_esp': 'Asistente de gira', 'is_active': True,},
    {'name': 'Sampler', 'name_esp': 'Sampler', 'is_active': True,},
    {'name': 'Saxophonist', 'name_esp': 'Saxofonista', 'is_active': True,},
    {'name': 'Sound Engineer', 'name_esp': 'Ingeniero de sonido', 'is_active': True,},
    {'name': 'String Section', 'name_esp': 'Sección de cuerdas', 'is_active': True,},
    {'name': 'Synthesizer Player', 'name_esp': 'Intérprete de sintetizador', 'is_active': True,},
    {'name': 'Technician', 'name_esp': 'Técnico', 'is_active': True,},
    {'name': 'Tour Manager', 'name_esp': 'Gerente de gira', 'is_active': True,},
    {'name': 'Trombonist', 'name_esp': 'Trombonista', 'is_active': True,},
    {'name': 'Trumpeter', 'name_esp': 'Trompetista', 'is_active': True,},
    {'name': 'Turntablist', 'name_esp': 'Toramesas', 'is_active': True,},
    {'name': 'Violinist', 'name_esp': 'Violinista', 'is_active': True,},
    {'name': 'Visual Artist', 'name_esp': 'Artista visual', 'is_active': True,},
    {'name': 'Vocalist', 'name_esp': 'Vocalista', 'is_active': True,},
    {'name': 'Woodwind Section', 'name_esp': 'Sección de viento madera', 'is_active': True,},
]

default_music_albums_types = [
    {'name': 'Mixtape', 'name_esp': 'Mixtape (típicamente en hip-hop y electrónica)', 'is_active': True,},
    {'name': 'Split Album', 'name_esp': 'Álbum compartido (entre dos o más artistas)', 'is_active': True,},
    {'name': 'EP (Extended Play)', 'name_esp': 'EP (Reproducción Extendida)', 'is_active': True,},
    {'name': 'Covers Album', 'name_esp': 'Álbum de versiones (covers)', 'is_active': True,},
    {'name': 'Bootleg Album', 'name_esp': 'Álbum pirata (no oficial)', 'is_active': True,},
    {'name': 'Greatest Hits Album', 'name_esp': 'Álbum de grandes éxitos', 'is_active': True,},
    {'name': 'Soundtrack Album', 'name_esp': 'Álbum de banda sonora', 'is_active': True,},
    {'name': 'Compilation Album', 'name_esp': 'Álbum recopilatorio', 'is_active': True,},
    {'name': 'Instrumental Album', 'name_esp': 'Álbum instrumental', 'is_active': True,},
    {'name': 'Box Set', 'name_esp': 'Caja recopilatoria', 'is_active': True,},
    {'name': 'Concept Album', 'name_esp': 'Álbum conceptual', 'is_active': True,},
    {'name': 'Studio Album', 'name_esp': 'Álbum de estudio', 'is_active': True,},
    {'name': 'Remix Album', 'name_esp': 'Álbum de remixes', 'is_active': True,},
    {'name': 'Christmas Album', 'name_esp': 'Álbum navideño', 'is_active': True,},
    {'name': 'Demo Album', 'name_esp': 'Álbum de demos', 'is_active': True,},
    {'name': 'Tribute Album', 'name_esp': 'Álbum tributo', 'is_active': True,},
    {'name': 'Live Album', 'name_esp': 'Álbum en vivo', 'is_active': True,},
    {'name': 'Triple Album', 'name_esp': 'Álbum triple', 'is_active': True,},
    {'name': 'Double Album', 'name_esp': 'Álbum doble', 'is_active': True,},
]

default_music_artist_types = [
    {'name': 'Band', 'name_esp': 'Banda, Grupo musical', 'is_active': True,},
    {'name': 'Choir', 'name_esp': 'Coro', 'is_active': True,},
    {'name': 'Collaborating Artist', 'name_esp': 'Artista colaborador', 'is_active': True,},
    {'name': 'Composer (as artist)', 'name_esp': 'Compositor (como artista)', 'is_active': True,},
    {'name': 'Cover Band', 'name_esp': 'Banda de versiones (covers)', 'is_active': True,},
    {'name': 'DJ (Disc Jockey)', 'name_esp': 'DJ (Disc Jockey)', 'is_active': True,},
    {'name': 'Duo', 'name_esp': 'Dúo', 'is_active': True,},
    {'name': 'Ensemble', 'name_esp': 'Ensamble', 'is_active': True,},
    {'name': 'Featured Artist', 'name_esp': 'Artista invitado', 'is_active': True,},
    {'name': 'Lyricist (as artist)', 'name_esp': 'Letrista (como artista)', 'is_active': True,},
    {'name': 'Musical Group', 'name_esp': 'Grupo musical', 'is_active': True,},
    {'name': 'Octet', 'name_esp': 'Octeto', 'is_active': True,},
    {'name': 'One-man Band', 'name_esp': 'Hombre orquesta', 'is_active': True,},
    {'name': 'Orchestra', 'name_esp': 'Orquesta', 'is_active': True,},
    {'name': 'Performing Artist', 'name_esp': 'Artista intérprete', 'is_active': True,},
    {'name': 'Producer (as artist)', 'name_esp': 'Productor (como artista)', 'is_active': True,},
    {'name': 'Quartet', 'name_esp': 'Cuarteto', 'is_active': True,},
    {'name': 'Quintet', 'name_esp': 'Quinteto', 'is_active': True,},
    {'name': 'Septet', 'name_esp': 'Septeto', 'is_active': True,},
    {'name': 'Sextet', 'name_esp': 'Sexteto', 'is_active': True,},
    {'name': 'Solo Artist', 'name_esp': 'Solista', 'is_active': True,},
    {'name': 'Supergroup', 'name_esp': 'Supergrupo (banda formada por músicos ya famosos)', 'is_active': True,},
    {'name': 'Tribute Band', 'name_esp': 'Banda tributo', 'is_active': True,},
    {'name': 'Trio', 'name_esp': 'Trío', 'is_active': True,},
    {'name': 'Virtual Artist', 'name_esp': 'Artista virtual', 'is_active': True,},
]
