# Generated by Django 5.2.1 on 2025-05-11 22:19

import apps.movie.utils.uploads
import core.utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Nombre Slug')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('founded_year', core.utils.utils.YearField(blank=True, null=True, validators=[core.utils.utils.validate_year], verbose_name='Año Fundación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('country', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_countries', to='common.country', verbose_name='País')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'ordering': ['-created_at', 'initial', 'name'],
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre Español')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Nombre Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('explicit', models.BooleanField(default=False, verbose_name='Explicito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='movie.genre', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='MovieLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='fecha Añadido')),
                ('process', models.TextField(default='', verbose_name='Proceso')),
                ('level', models.CharField(default='INFO', max_length=10, verbose_name='Nivel')),
                ('message', models.TextField(verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Log Película',
                'verbose_name_plural': 'Logs Películas',
                'db_table': 'log_Movie',
                'ordering': ['-timestamp'],
                'unique_together': {('level', 'process', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=15, unique=True, verbose_name='Acrónimo')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Nombre Español')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=60, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['acronym', 'name'],
                'unique_together': {('acronym', 'name', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre Español')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Nombre Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('role_staff', models.BooleanField(default=False, verbose_name='Rol Personal')),
                ('role_cast', models.BooleanField(default=False, verbose_name='Rol Elenco')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Ros Película',
                'verbose_name_plural': 'Roles Películas',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'name_esp', 'role_staff', 'role_cast')},
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('name_esp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Nombre Español')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True, verbose_name='Nombre Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('parent', models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='movie.type', verbose_name='Padre')),
            ],
            options={
                'verbose_name': 'Tipo Película',
                'verbose_name_plural': 'Tipos Películas',
                'ordering': ['-created_at', 'name'],
                'unique_together': {('name', 'name_esp')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título Original')),
                ('title_secundary', models.CharField(blank=True, max_length=255, null=True, verbose_name='Título Secundario')),
                ('release_year', core.utils.utils.YearField(blank=True, null=True, validators=[core.utils.utils.validate_year], verbose_name='Año Lanzamiento')),
                ('duration_minutes', models.PositiveIntegerField(blank=True, default=0, verbose_name='Duración Minutos')),
                ('synopsis', models.TextField(blank=True, verbose_name='Sinopsis')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('distributors', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='movies_as_distributors', to='movie.company', verbose_name='Distribuidoras')),
                ('genres', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='movies_as_genre', to='movie.genre', verbose_name='Géneros')),
                ('producers', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True}, related_name='movies_as_producers', to='movie.company', verbose_name='Productoras')),
                ('movie_rating', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_ratings', to='movie.rating', verbose_name='Clasificación Película')),
                ('movie_types', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_types', to='movie.type', verbose_name='Tipo Película')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-created_at', 'title'],
                'unique_together': {('title', 'title_secundary', 'release_year')},
            },
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.movie.utils.uploads.movie_image_path, verbose_name='Imagen Película')),
                ('image_url', models.URLField(blank=True, max_length=2000, null=True, verbose_name='URL')),
                ('name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('movie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_images', to='movie.movie', verbose_name='Película')),
                ('size_image', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_images_as_sizes', to='common.imagesize', verbose_name='Tamaño')),
            ],
            options={
                'verbose_name': 'Imagen Película',
                'verbose_name_plural': 'Imágenes Películas',
                'ordering': ['movie', 'size_image', 'name'],
                'unique_together': {('movie', 'size_image', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MovieImageExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.movie.utils.uploads.movie_image_extra_path, verbose_name='Imagen Extra Película')),
                ('name', models.CharField(editable=False, max_length=150, unique=True, verbose_name='Nombre')),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True, verbose_name='Nombre Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('movie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_exta_images', to='movie.movie', verbose_name='Película')),
            ],
            options={
                'verbose_name': 'Imagen Extra Película',
                'verbose_name_plural': 'Imágenes Extra Películas',
                'ordering': ['movie', 'name'],
                'unique_together': {('movie', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MovieStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('movie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_staffs', to='movie.movie', verbose_name='Película')),
                ('person', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_persons', to='common.person', verbose_name='Persona')),
                ('role', models.ForeignKey(limit_choices_to={'is_active': True, 'role_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='persons_as_movie_staff_roles', to='movie.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Personal Película',
                'verbose_name_plural': 'Personal Películas',
                'ordering': ['movie', 'role', 'person'],
                'unique_together': {('movie', 'role', 'person')},
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=100, verbose_name='Personaje')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Personaje Slug')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('actor', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='persons_as_movie_cast_roles', to='common.person', verbose_name='Actor')),
                ('movie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_casts', to='movie.movie', verbose_name='Película')),
                ('role', models.ForeignKey(limit_choices_to={'is_active': True, 'role_cast': True}, on_delete=django.db.models.deletion.CASCADE, related_name='actors_as_roles', to='movie.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Reparto Película',
                'verbose_name_plural': 'Reparto Películas',
                'ordering': ['movie', 'actor', 'character_name'],
                'unique_together': {('movie', 'actor', 'role', 'character_name')},
            },
        ),
        migrations.CreateModel(
            name='TitleMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, verbose_name='Título Slug')),
                ('initial', models.CharField(blank=True, editable=False, max_length=1, verbose_name='Inicial')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('movie', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_title', to='movie.movie', verbose_name='Pelicula')),
                ('title_lang', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='titles_movies_as_languages', to='common.language', verbose_name='Lenguaje')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ['movie', 'title_lang', 'initial', 'title'],
                'unique_together': {('title_lang', 'title', 'movie')},
            },
        ),
    ]
