# Generated by Django 5.2.1 on 2025-05-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['initial', 'name'], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
    ]
