# Generated by Django 5.2.1 on 2025-05-16 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Rol Película', 'verbose_name_plural': 'Roles Películas'},
        ),
        migrations.AlterField(
            model_name='titlemovie',
            name='movie',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='movies_as_title', to='movie.movie', verbose_name='Película'),
        ),
    ]
