# Generated by Django 5.2.1 on 2025-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha Añadido'),
        ),
    ]
