# Generated by Django 5.2.1 on 2025-05-16 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_personimageextra_options_and_more'),
        ('movie', '0002_alter_role_options_alter_titlemovie_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titlemovie',
            name='title_lang',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='titles_movies_as_languages', to='common.language', verbose_name='Idioma'),
        ),
    ]
