default_renpy_engines =[
    {'name':'Ren\'Py', 'is_active':True, 'description':'Un motor de videojuego gratuito y de código abierto diseñado para crear novelas visuales, un tipo de historia interactiva basada en texto con elementos visuales. Está escrito en Python y es conocido por su facilidad de uso para desarrolladores y su capacidad para crear historias ramificadas complejas.',},
    {'name':'RPGM (RPG Maker)', 'is_active':True, 'description':'Una serie de software de creación de juegos diseñado específicamente para desarrollar videojuegos de rol (RPG). Sin embargo, también permite la creación de otros géneros como juegos de aventura o novelas visuales con ajustes. Cuenta con herramientas para la creación de mapas, eventos, personajes y scripting para personalizar la jugabilidad.',},
    {'name':'Unity', 'is_active':True, 'description':'Una plataforma de desarrollo en tiempo real 3D y 2D muy popular y potente. Ofrece un entorno de desarrollo integrado con un editor visual y soporte para múltiples lenguajes de programación (principalmente C#). Es capaz de crear juegos para una amplia gama de plataformas, incluyendo PC, consolas, móviles, VR y AR.',},
    {'name':'Unreal (Unreal Engine)', 'is_active':True, 'description':'Otro motor de desarrollo de juegos profesional conocido por sus gráficos de alta fidelidad y sus potentes herramientas para la creación de juegos 3D inmersivos. Utiliza principalmente el lenguaje de programación C++ y es utilizado en la industria para juegos de alta calidad, así como en otras áreas como la visualización en tiempo real y la producción virtual.',},
    {'name':'Wolf RPG (Wolf RPG Editor)', 'is_active':True, 'description':'Un software gratuito de creación de juegos diseñado para desarrollar juegos de rol (RPG). Ofrece herramientas para la creación de mapas, eventos y personajes, así como capacidades de scripting para personalizar la mecánica de juego y los elementos de la historia. Es particularmente popular en la comunidad de desarrollo de juegos indie japonesa.',},
    {'name':'HTML', 'is_active':True, 'description':'Se refiere al uso de HTML5, junto con CSS y JavaScript, para el desarrollo de juegos que se ejecutan directamente en navegadores web sin necesidad de plugins. Permite la creación de juegos 2D y algunos juegos 3D ligeros utilizando el elemento Canvas para gráficos y la API Web Audio para sonido. Es una tecnología multiplataforma por naturaleza, ya que los juegos pueden jugarse en cualquier dispositivo con un navegador web moderno.',},
    {'name':'Flash', 'is_active':True, 'description':'Fue una plataforma multimedia utilizada para crear animaciones, juegos y aplicaciones interactivas para la web. En el desarrollo de juegos, permitía la creación de juegos 2D basados en vectores y bitmaps, utilizando el lenguaje de programación ActionScript. Aunque alguna vez fue muy popular para juegos web, su uso ha disminuido significativamente debido a problemas de seguridad y la aparición de tecnologías web más modernas como HTML5',},
    {'name':'Java', 'is_active':True, 'description':'Un lenguaje de programación versátil que se puede utilizar para desarrollar juegos de diversos tipos, desde juegos 2D simples hasta aventuras 3D complejas. Se caracteriza por su independencia de plataforma (los juegos pueden ejecutarse en cualquier dispositivo con una Máquina Virtual de Java - JVM), su orientación a objetos y sus amplias bibliotecas.',},
    {'name':'ADRIFT', 'is_active':True, 'description':'Un sistema de desarrollo de ficción interactiva (antes conocido como aventuras de texto) basado en GUI para Windows. Está diseñado para ser intuitivo y fácil de usar, permitiendo a los creadores concentrarse en la historia mediante interfaces visuales en lugar de programación compleja. Los juegos creados con ADRIFT se pueden jugar en Windows, Mac, Linux y navegadores web.',},
    {'name':'Others', 'is_active':True, 'description':'Esta categoría es genérica y agrupa motores o herramientas de desarrollo de juegos que no se encuentran en la lista específica. Podría incluir una amplia variedad de software con diferentes funcionalidades y enfoques.',},
    {'name':'QSP (Quest Soft Player)', 'is_active':True, 'description':'Un sistema de desarrollo de juegos basado en texto que se inclina hacia una interfaz basada en elecciones, aunque también ofrece la opción de crear juegos con parser de texto. Es multiplataforma y cuenta con una comunidad grande y estable. Permite el uso de HTML, CSS y JavaScript para la presentación del contenido.',},
    {'name':'RAGS', 'is_active':True, 'description':'Un sistema diseñado para crear juegos interactivos de ficción de forma rápida y sencilla. Ofrece una interfaz intuitiva y permite integrar imágenes y objetos fácilmente. Su objetivo es facilitar la creación de mundos interactivos y puzles para los jugadores.',},
    {'name':'Tads (Text Adventure Development System)', 'is_active':True, 'description':'Un lenguaje de programación especializado y un conjunto de herramientas para crear juegos de ficción interactiva basados en texto. Permite a los desarrolladores escribir juegos con tramas complejas, puzles e interacciones con el jugador.',},
    {'name':'WebGL', 'is_active':True, 'description':'Una API de JavaScript para renderizar gráficos interactivos 2D y 3D dentro de cualquier navegador web compatible 1  sin necesidad de plugins. Permite el desarrollo de juegos que se pueden jugar directamente en línea en diversas plataformas y dispositivos',},
    {'name':'WebGL', 'is_active':True, 'description':'Una API de JavaScript para renderizar gráficos interactivos 2D y 3D dentro de cualquier navegador web compatible 1  sin necesidad de plugins. Permite el desarrollo de juegos que se pueden jugar directamente en línea en diversas plataformas y dispositivos',},
    {'name':'WebGL', 'is_active':True, 'description':'Una API de JavaScript para renderizar gráficos interactivos 2D y 3D dentro de cualquier navegador web compatible 1  sin necesidad de plugins. Permite el desarrollo de juegos que se pueden jugar directamente en línea en diversas plataformas y dispositivos',},
]

default_renpy_status = [
    {'name': 'Abandoned', 'name_esp': 'Abandonado', 'is_active': True, 'description': 'El proyecto ha sido detenido por sus desarrolladores y no se espera que se continúe en el futuro.',},
    {'name': 'Completed', 'name_esp': 'Completado', 'is_active': True, 'description': 'El proyecto ha sido finalizado por sus desarrolladores y se considera que está en su estado final.',},
    {'name': 'Onhold', 'name_esp': 'En pausa', 'is_active': True, 'description': 'El desarrollo del proyecto se ha detenido temporalmente, pero existe la posibilidad de que se retome en el futuro.',},
    {'name': 'Developing', 'name_esp': 'En desarrollo', 'is_active': True, 'description': 'El proyecto se encuentra actualmente en proceso de creación y se están añadiendo nuevas funcionalidades o contenido.',},

]

default_renpy_genres = [
    {'name': '2D Game', 'name_esp': 'Juego 2D', 'is_active': True, 'explicit': False, 'description': 'Juego con gráficos bidimensionales, donde el movimiento y la interacción ocurren en un plano de dos dimensiones.',},
    {'name': '2D CG', 'name_esp': 'CG 2D', 'is_active': True, 'explicit': False, 'description': 'Imágenes generadas por computadora en dos dimensiones, a menudo utilizadas para escenas estáticas o ilustraciones dentro de un juego.',},
    {'name': '3D Game', 'name_esp': 'Juego 3D', 'is_active': True, 'explicit': False, 'description': 'Juego con gráficos tridimensionales, que permite movimiento e interacción en un espacio de tres dimensiones.',},
    {'name': '3D CG', 'name_esp': 'CG 3D', 'is_active': True, 'explicit': False, 'description': 'Imágenes generadas por computadora en tres dimensiones, utilizadas para personajes, entornos o escenas dentro de un juego.',},
    {'name': 'Adventure', 'name_esp': 'Aventura', 'is_active': True, 'explicit': False, 'description': 'Género de juego que se centra en la exploración, la resolución de puzles y la interacción narrativa.',},
    {'name': 'Ahegao', 'name_esp': 'Ahegao', 'is_active': True, 'explicit': True, 'description': 'Expresión facial exagerada que a menudo se encuentra en contenido erótico.',},
    {'name': 'AI CG', 'name_esp': 'CG IA', 'is_active': True, 'explicit': False, 'description': 'Imágenes generadas por inteligencia artificial.',},
    {'name': 'Anal Sex', 'name_esp': 'Sexo Anal', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que involucra la penetración del ano.',},
    {'name': 'Animated', 'name_esp': 'Animado', 'is_active': True, 'explicit': False, 'description': 'Contenido que presenta movimiento a través de una secuencia de imágenes.',},
    {'name': 'BDSM', 'name_esp': 'BDSM', 'is_active': True, 'explicit': True, 'description': 'Prácticas sexuales que involucran Bondage, Disciplina, Dominación/Sumisión y Sadismo/Masoquismo.',},
    {'name': 'Bestiality', 'name_esp': 'Bestialidad', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual entre un humano y un animal.',},
    {'name': 'Big Ass', 'name_esp': 'Trasero Grande', 'is_active': True, 'explicit': True, 'description': 'Representación de personajes con traseros de gran tamaño.',},
    {'name': 'Big Tits', 'name_esp': 'Pechos Grandes', 'is_active': True, 'explicit': True, 'description': 'Representación de personajes con pechos de gran tamaño.',},
    {'name': 'Blackmail', 'name_esp': 'Chantaje', 'is_active': True, 'explicit': False, 'description': 'Acto de exigir dinero u otra compensación a cambio de no revelar información perjudicial.',},
    {'name': 'Bukkake', 'name_esp': 'Bukkake', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que involucra la eyaculación múltiple sobre una persona.',},
    {'name': 'Censored', 'name_esp': 'Censurado', 'is_active': True, 'explicit': True, 'description': 'Contenido al que se le han eliminado partes consideradas obscenas o inapropiadas.',},
    {'name': 'Character Creation', 'name_esp': 'Creación de Personajes', 'is_active': True, 'explicit': False, 'description': 'Función que permite al jugador personalizar la apariencia o atributos de un personaje en un juego.',},
    {'name': 'Cheating', 'name_esp': 'Engaño', 'is_active': True, 'explicit': True, 'description': 'Infidelidad en una relación romántica o sexual.',},
    {'name': 'Combat', 'name_esp': 'Combate', 'is_active': True, 'explicit': False, 'description': 'Enfrentamiento físico o armado entre personajes.',},
    {'name': 'Corruption', 'name_esp': 'Corrupción', 'is_active': True, 'explicit': False, 'description': 'Proceso por el cual un personaje se vuelve moralmente depravado o malvado.',},
    {'name': 'Cosplay', 'name_esp': 'Cosplay', 'is_active': True, 'explicit': False, 'description': 'Práctica de disfrazarse como personajes de ficción.',},
    {'name': 'Creampie', 'name_esp': 'Creampie', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que resulta en la eyaculación dentro de la vagina.',},
    {'name': 'Dating sim', 'name_esp': 'Simulador de Citas', 'is_active': True, 'explicit': True, 'description': 'Género de juego que se centra en desarrollar relaciones románticas con personajes.',},
    {'name': 'DILF', 'name_esp': 'DILF', 'is_active': True, 'explicit': True, 'description': 'Acrónimo de "Dad I\'d Like to Fuck", refiriéndose a un padre atractivo.',},
    {'name': 'Drugs', 'name_esp': 'Drogas', 'is_active': True, 'explicit': False, 'description': 'Sustancias que alteran el estado mental o físico.',},
    {'name': 'Dystopian Setting', 'name_esp': 'Ambientación Distópica', 'is_active': True, 'explicit': False, 'description': 'Entorno ficticio caracterizado por la opresión, la miseria y el control totalitario.',},
    {'name': 'Exhibitionism', 'name_esp': 'Exhibicionismo', 'is_active': True, 'explicit': True, 'description': 'Exposición de los genitales a una persona desprevenida.',},
    {'name': 'Fantasy', 'name_esp': 'Fantasía', 'is_active': True, 'explicit': False, 'description': 'Género que incorpora elementos mágicos, criaturas míticas y mundos imaginarios.',},
    {'name': 'Female Domination', 'name_esp': 'Dominación Femenina', 'is_active': True, 'explicit': True, 'description': 'Interacciones donde una mujer ejerce control sobre otra persona.',},
    {'name': 'Female Protagonist', 'name_esp': 'Protagonista Femenina', 'is_active': True, 'explicit': False, 'description': 'Historia donde el personaje principal es una mujer.',},
    {'name': 'Footjob', 'name_esp': 'Footjob', 'is_active': True, 'explicit': True, 'description': 'Estimulación sexual del pene con los pies.',},
    {'name': 'Furry', 'name_esp': 'Furry', 'is_active': True, 'explicit': False, 'description': 'Interés en personajes animales antropomórficos con características humanas.',},
    {'name': 'Futa/Trans', 'name_esp': 'Futa/Trans', 'is_active': True, 'explicit': True, 'description': 'Contenido que presenta personajes con características sexuales ambiguas (futanari) o personajes transgénero.',},
    {'name': 'Futa/Trans Protagonist', 'name_esp': 'Protagonista Futa/Trans', 'is_active': True, 'explicit': True, 'description': 'La historia tiene como personaje principal a un personaje con características sexuales ambiguas (futanari) o transgénero.',},
    {'name': 'Gay', 'name_esp': 'Gay', 'is_active': True, 'explicit': True, 'description': 'Contenido que se centra en relaciones románticas o sexuales entre hombres.',},
    {'name': 'Graphic Violence', 'name_esp': 'Violencia Gráfica', 'is_active': True, 'explicit': True, 'description': 'Contenido que representa actos de violencia de manera explícita y detallada.',},
    {'name': 'Groping', 'name_esp': 'Manoseo', 'is_active': True, 'explicit': True, 'description': 'Tocar a alguien sexualmente sin su consentimiento.',},
    {'name': 'Group Sex', 'name_esp': 'Sexo Grupal', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que involucra a tres o más personas.',},
    {'name': 'Handjob', 'name_esp': 'Masturbación Manual', 'is_active': True, 'explicit': True, 'description': 'Estimulación sexual del pene con la mano.',},
    {'name': 'Harem', 'name_esp': 'Harem', 'is_active': True, 'explicit': False, 'description': 'Un protagonista (generalmente masculino) rodeado de múltiples intereses amorosos (generalmente femeninos).',},
    {'name': 'Horror', 'name_esp': 'Terror', 'is_active': True, 'explicit': False, 'description': 'Género que busca provocar miedo, shock o disgusto en la audiencia.',},
    {'name': 'Humiliation', 'name_esp': 'Humillación', 'is_active': True, 'explicit': True, 'description': 'Acción de avergonzar o degradar a un personaje.',},
    {'name': 'Humor', 'name_esp': 'Humor', 'is_active': True, 'explicit': False, 'description': 'Contenido destinado a ser cómico o divertido.',},
    {'name': 'Incest', 'name_esp': 'Incesto', 'is_active': True, 'explicit': True, 'description': 'Relaciones sexuales entre miembros cercanos de la misma familia.',},
    {'name': 'Internal View', 'name_esp': 'Vista Interna', 'is_active': True, 'explicit': False, 'description': 'Perspectiva narrativa que se centra en los pensamientos y sentimientos internos de un personaje.',},
    {'name': 'Interracial', 'name_esp': 'Interracial', 'is_active': True, 'explicit': False, 'description': 'Relaciones románticas o sexuales entre personas de diferentes razas.',},
    {'name': 'Japanese Game', 'name_esp': 'Juego Japonés', 'is_active': True, 'explicit': False, 'description': 'Juego desarrollado en Japón.',},
    {'name': 'Kinetic Novel', 'name_esp': 'Novela Cinética', 'is_active': True, 'explicit': False, 'description': 'Un tipo de novela visual que se presenta de forma lineal, sin opciones interactivas significativas para el jugador más allá de avanzar en el texto y las imágenes.',},
    {'name': 'Lactation', 'name_esp': 'Lactancia', 'is_active': True, 'explicit': True, 'description': 'Producción y liberación de leche materna, a menudo con connotaciones eróticas en este contexto.',},
    {'name': 'Lesbian', 'name_esp': 'Lesbiana', 'is_active': True, 'explicit': True, 'description': 'Contenido que se centra en relaciones románticas o sexuales entre mujeres.',},
    {'name': 'Loli', 'name_esp': 'Loli', 'is_active': True, 'explicit': True, 'description': 'Término que describe personajes femeninos prepúberes o de apariencia infantil, a menudo con connotaciones eróticas.',},
    {'name': 'Male Domination', 'name_esp': 'Dominación Masculina', 'is_active': True, 'explicit': True, 'description': 'Interacciones donde un hombre ejerce control sobre otra persona.',},
    {'name': 'Male Protagonist', 'name_esp': 'Protagonista Masculino', 'is_active': True, 'explicit': False, 'description': 'Historia donde el personaje principal es un hombre.',},
    {'name': 'Management', 'name_esp': 'Gestión', 'is_active': True, 'explicit': False, 'description': 'Género de juego que se centra en la administración de recursos, personajes o entidades.',},
    {'name': 'Masturbation', 'name_esp': 'Masturbación', 'is_active': True, 'explicit': True, 'description': 'Autoestimulación sexual.',},
    {'name': 'MIFL', 'name_esp': 'MILF', 'is_active': True, 'explicit': True, 'description': 'Acrónimo de "Mother I\'d Like to Fuck", refiriéndose a una madre atractiva.',},
    {'name': 'Mind Control', 'name_esp': 'Control Mental', 'is_active': True, 'explicit': False, 'description': 'Situación en la que un personaje controla las acciones o pensamientos de otro.',},
    {'name': 'Mobile Game', 'name_esp': 'Juego Móvil', 'is_active': True, 'explicit': False, 'description': 'Juego diseñado para ser jugado en dispositivos móviles como smartphones o tablets.',},
    {'name': 'Monster', 'name_esp': 'Monstruo', 'is_active': True, 'explicit': False, 'description': 'Personajes o criaturas fantásticas, a menudo aterradoras o peligrosas.',},
    {'name': 'Monster Girl', 'name_esp': 'Chica Monstruo', 'is_active': True, 'explicit': False, 'description': 'Personajes femeninos con características de monstruos o animales.',},
    {'name': 'Multiple Endings', 'name_esp': 'Múltiples Finales', 'is_active': True, 'explicit': False, 'description': 'La historia del juego puede concluir de diferentes maneras dependiendo de las decisiones del jugador.',},
    {'name': 'Multiple Penetration', 'name_esp': 'Penetración Múltiple', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que involucra la penetración simultánea de una persona por múltiples individuos o objetos.',},
    {'name': 'Multiple Protagonist', 'name_esp': 'Múltiples Protagonistas', 'is_active': True, 'explicit': False, 'description': 'La historia tiene varios personajes principales con sus propias tramas o perspectivas significativas.',},
    {'name': 'Necrophilia', 'name_esp': 'Necrofilia', 'is_active': True, 'explicit': True, 'description': 'Atracción sexual hacia cadáveres.',},
    {'name': 'Netorare', 'name_esp': 'Netorare', 'is_active': True, 'explicit': True, 'description': 'Género donde un personaje es engañado o su pareja sexual tiene relaciones con otra persona, a menudo explorando sentimientos de celos y traición.',},
    {'name': 'No Sexual Content', 'name_esp': 'Sin Contenido Sexual', 'is_active': True, 'explicit': False, 'description': 'Contenido que no presenta representaciones de actividad sexual.',},
    {'name': 'Oral Sex', 'name_esp': 'Sexo Oral', 'is_active': True, 'explicit': True, 'description': 'Estimulación sexual de los genitales con la boca, los labios o la lengua.',},
    {'name': 'Paranormal', 'name_esp': 'Paranormal', 'is_active': True, 'explicit': False, 'description': 'Contenido que involucra fenómenos que están más allá de la explicación científica.',},
    {'name': 'Parody', 'name_esp': 'Parodia', 'is_active': True, 'explicit': False, 'description': 'Obra que imita de forma cómica otra obra, género o estilo.',},
    {'name': 'Platformer', 'name_esp': 'Plataformas', 'is_active': True, 'explicit': False, 'description': 'Género de videojuego donde el personaje principal debe saltar y escalar a través de niveles llenos de plataformas y obstáculos.',},
    {'name': 'Point & Click', 'name_esp': 'Point & Click', 'is_active': True, 'explicit': False, 'description': 'Género de videojuego de aventura donde la interacción se realiza principalmente señalando objetos en la pantalla y haciendo clic con el ratón para realizar acciones.',},
    {'name': 'Possession', 'name_esp': 'Posesión', 'is_active': True, 'explicit': False, 'description': 'Situación donde una entidad sobrenatural toma control del cuerpo de un personaje.',},
    {'name': 'POV', 'name_esp': 'POV (Punto de Vista)', 'is_active': True, 'explicit': False, 'description': 'Contenido presentado desde la perspectiva del personaje, simulando la visión en primera persona del espectador.',},
    {'name': 'Pregnancy', 'name_esp': 'Embarazo', 'is_active': True, 'explicit': False, 'description': 'Estado de llevar un feto en el útero.',},
    {'name': 'Prostitution', 'name_esp': 'Prostitución', 'is_active': True, 'explicit': True, 'description': 'Práctica de tener relaciones sexuales a cambio de dinero.',},
    {'name': 'Puzzle', 'name_esp': 'Puzle', 'is_active': True, 'explicit': False, 'description': 'Género de videojuego que se centra en la resolución de acertijos y desafíos mentales.',},
    {'name': 'Rape', 'name_esp': 'Violación', 'is_active': True, 'explicit': True, 'description': 'Acto de agresión sexual que involucra la penetración sin consentimiento.',},
    {'name': 'Real porn', 'name_esp': 'Pornografía Real', 'is_active': True, 'explicit': True, 'description': 'Contenido sexual explícito con actores reales.',},
    {'name': 'Religion', 'name_esp': 'Religión', 'is_active': True, 'explicit': False, 'description': 'Temas relacionados con creencias, prácticas y organizaciones religiosas.',},
    {'name': 'Romance', 'name_esp': 'Romance', 'is_active': True, 'explicit': False, 'description': 'Género que se centra en el desarrollo de relaciones amorosas y sentimentales entre personajes.',},
    {'name': 'RPG', 'name_esp': 'RPG (Juego de Rol)', 'is_active': True, 'explicit': False, 'description': 'Género de videojuego donde los jugadores asumen roles de personajes en un mundo de ficción, a menudo con desarrollo de personajes y sistemas de combate.',},
    {'name': 'Sandbox', 'name_esp': 'Sandbox (Mundo Abierto)', 'is_active': True, 'explicit': False, 'description': 'Tipo de juego que proporciona a los jugadores libertad para explorar y interactuar en un mundo virtual con pocos o ningún objetivo lineal.',},
    {'name': 'Scat', 'name_esp': 'Escatología', 'is_active': True, 'explicit': True, 'description': 'Interés sexual en las heces.',},
    {'name': 'School Setting', 'name_esp': 'Ambientación Escolar', 'is_active': True, 'explicit': False, 'description': 'Historia que se desarrolla principalmente en un entorno educativo.',},
    {'name': 'Sci-Fi', 'name_esp': 'Ciencia Ficción', 'is_active': True, 'explicit': False, 'description': 'Género que explora conceptos científicos y tecnológicos, a menudo ambientado en el futuro o en otros planetas.',},
    {'name': 'Sex Toys', 'name_esp': 'Juguetes Sexuales', 'is_active': True, 'explicit': True, 'description': 'Objetos utilizados para la estimulación sexual.',},
    {'name': 'Sexual Harassment', 'name_esp': 'Acoso Sexual', 'is_active': True, 'explicit': True, 'description': 'Comportamiento sexual no deseado que ofende, humilla o intimida a otra persona.',},
    {'name': 'Shooter', 'name_esp': 'Shooter (Disparos)', 'is_active': True, 'explicit': False, 'description': 'Género de videojuego que se centra en el combate con armas de fuego u otras armas a distancia.',},
    {'name': 'Shota', 'name_esp': 'Shota', 'is_active': True, 'explicit': True, 'description': 'Término que describe personajes masculinos prepúberes o de apariencia infantil, a menudo con connotaciones eróticas.',},
    {'name': 'Side-Scroller', 'name_esp': 'Desplazamiento Lateral', 'is_active': True, 'explicit': False, 'description': 'Tipo de videojuego donde la acción se ve desde una perspectiva lateral y el movimiento es principalmente horizontal.',},
    {'name': 'Simulator', 'name_esp': 'Simulador', 'is_active': True, 'explicit': False, 'description': 'Género de videojuego que intenta replicar aspectos de una actividad real, como volar un avión o gestionar una ciudad.',},
    {'name': 'Sissification', 'name_esp': 'Afeminamiento', 'is_active': True, 'explicit': True, 'description': 'Proceso de hacer que un personaje masculino parezca o actúe de manera femenina.',},
    {'name': 'Slave', 'name_esp': 'Esclavo', 'is_active': True, 'explicit': True, 'description': 'Personaje que es propiedad de otro y está obligado a obedecer sus órdenes.',},
    {'name': 'Sleep Sex', 'name_esp': 'Sexo Durante el Sueño', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que ocurre mientras una persona está dormida.',},
    {'name': 'Spanking', 'name_esp': 'Azotes', 'is_active': True, 'explicit': True, 'description': 'Nalgadas, a menudo con connotaciones eróticas o de disciplina.',},
    {'name': 'Strategy', 'name_esp': 'Estrategia', 'is_active': True, 'explicit': False, 'description': 'Género de juego que se centra en la planificación y la toma de decisiones tácticas para lograr la victoria.',},
    {'name': 'Stripping', 'name_esp': 'Desnudarse', 'is_active': True, 'explicit': True, 'description': 'Acto de quitarse la ropa, a menudo con fines de entretenimiento erótico.',},
    {'name': 'Superpowers', 'name_esp': 'Superpoderes', 'is_active': True, 'explicit': False, 'description': 'Habilidades que van más allá de las capacidades humanas normales.',},
    {'name': 'Swinging', 'name_esp': 'Intercambio de Parejas', 'is_active': True, 'explicit': True, 'description': 'Práctica sexual en la que parejas casadas o comprometidas participan en actividades sexuales con otras parejas.',},
    {'name': 'Teasing', 'name_esp': 'Provocación', 'is_active': True, 'explicit': True, 'description': 'Acto de excitar sexualmente a alguien sin la intención de tener relaciones sexuales completas de inmediato.',},
    {'name': 'Tentacles', 'name_esp': 'Tentáculos', 'is_active': True, 'explicit': True, 'description': 'Apéndices largos y flexibles, a menudo de criaturas ficticias, utilizados en interacciones sexuales en este contexto.',},
    {'name': 'Text Based', 'name_esp': 'Basado en Texto', 'is_active': True, 'explicit': False, 'description': 'Tipo de juego donde la interacción y la narrativa se presentan principalmente a través de texto, sin gráficos extensos.',},
    {'name': 'Titfuck', 'name_esp': 'Sexo con Pechos', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que involucra la penetración del pene entre los pechos.',},
    {'name': 'Trainer', 'name_esp': 'Entrenador', 'is_active': True, 'explicit': False, 'description': 'Género de juego donde el jugador entrena o cuida a uno o más personajes o criaturas.',},
    {'name': 'Transformation', 'name_esp': 'Transformación', 'is_active': True, 'explicit': False, 'description': 'Proceso por el cual un personaje cambia de forma o estado.',},
    {'name': 'Trap', 'name_esp': 'Trap (Travesti)', 'is_active': True, 'explicit': True, 'description': 'Término controvertido que describe a un personaje que biológicamente es de un sexo pero tiene una apariencia del sexo opuesto, a menudo usado para generar sorpresa o atracción.',},
    {'name': 'Turn Based Combat', 'name_esp': 'Combate por Turnos', 'is_active': True, 'explicit': False, 'description': 'Sistema de combate en videojuegos donde los participantes realizan acciones por separado en turnos.',},
    {'name': 'Twins', 'name_esp': 'Gemelos', 'is_active': True, 'explicit': False, 'description': 'Personajes que son hermanos idénticos o fraternos.',},
    {'name': 'Urination', 'name_esp': 'Orinar', 'is_active': True, 'explicit': True, 'description': 'Acto de liberar orina del cuerpo, a veces con connotaciones eróticas en este contexto.',},
    {'name': 'Vaginal Sex', 'name_esp': 'Sexo Vaginal', 'is_active': True, 'explicit': True, 'description': 'Actividad sexual que involucra la penetración del pene en la vagina.',},
    {'name': 'Virgin', 'name_esp': 'Virgen', 'is_active': True, 'explicit': False, 'description': 'Personaje que nunca ha tenido relaciones sexuales.',},
    {'name': 'Virtual Reality', 'name_esp': 'Realidad Virtual', 'is_active': True, 'explicit': False, 'description': 'Tecnología que sumerge al usuario en un entorno simulado.',},
    {'name': 'Voiced', 'name_esp': 'Con Voces', 'is_active': True, 'explicit': False, 'description': 'Contenido que incluye actuación de voz para los personajes o la narración.',},
    {'name': 'Vore', 'name_esp': 'Vore (Vorarefilia)', 'is_active': True, 'explicit': True, 'description': 'Parafilia que involucra la fantasía de ser comido vivo o comer a otro ser vivo entero.',},
    {'name': 'Voyeurism', 'name_esp': 'Voyeurismo', 'is_active': True, 'explicit': True, 'description': 'Parafilia que involucra la obtención de excitación sexual al observar a personas desnudas o participando en actividades sexuales sin su conocimiento.',},
]

default_renpy_platforms = [
    {'name': 'PC (Microsoft Windows)', 'name_esp': 'PC (Microsoft Windows)', 'is_active': True, 'description': 'La plataforma de juegos de escritorio más común y versátil.',},
    {'name': 'Linux', 'name_esp': 'Linux', 'is_active': True, 'description': 'Un sistema operativo de código abierto con una selección creciente de juegos.',},
    {'name': 'Mac (macOS)', 'name_esp': 'Mac (macOS)', 'is_active': True, 'description': 'El sistema operativo de Apple, con una selección de juegos disponibles.',},
    {'name': 'Android', 'name_esp': 'Android', 'is_active': True, 'description': 'El sistema operativo móvil de Google, con una gran cantidad de juegos.',},
    {'name': 'iOS (iPhone/iPad)', 'name_esp': 'iOS (iPhone/iPad)', 'is_active': True, 'description': 'El sistema operativo móvil de Apple, con juegos disponibles en la App Store.',},
    {'name': 'PlayStation', 'name_esp': 'PlayStation', 'is_active': False, 'description': 'La línea de consolas de videojuegos de Sony (ej: PS5, PS4).',},
    {'name': 'Xbox', 'name_esp': 'Xbox', 'is_active': False, 'description': 'La línea de consolas de videojuegos de Microsoft (ej: Xbox Series X|S, Xbox One).',},
    {'name': 'Nintendo Switch', 'name_esp': 'Nintendo Switch', 'is_active': False, 'description': 'Una consola híbrida que se puede usar como portátil o conectada a un televisor.',},
    {'name': 'Web (Browser)', 'name_esp': 'Web (Navegador)', 'is_active': False, 'description': 'Juegos que se juegan directamente en un navegador web.',},
    {'name': 'Cloud Gaming', 'name_esp': 'Juegos en la Nube', 'is_active': False, 'description': 'Servicios que permiten jugar videojuegos transmitidos desde servidores remotos.',},
    {'name': 'Arcade', 'name_esp': 'Arcade', 'is_active': False, 'description': 'Máquinas de videojuegos comerciales que se encuentran en lugares públicos.',},
    {'name': 'Nintendo 3DS', 'name_esp': 'Nintendo 3DS', 'is_active': False, 'description': 'Una consola portátil de Nintendo con pantalla 3D estereoscópica (descontinuada, pero aún activa para algunos usuarios).',},
    {'name': 'PlayStation Vita', 'name_esp': 'PlayStation Vita', 'is_active': False, 'description': 'Una consola portátil de Sony (descontinuada, pero aún activa para algunos usuarios).',},
    {'name': 'Retro Consoles', 'name_esp': 'Consolas Retro', 'is_active': False, 'description': 'Consolas de videojuegos más antiguas que aún tienen una base de jugadores y coleccionistas.',},
]

default_renpy_prefix = [
    {'name': 'VN', 'name_esp': 'VN', 'is_active': True, 'description': 'Novela Visual.',},
    {'name': 'Collection', 'name_esp': 'Collección', 'is_active': True, 'description': 'Colección de Juegos.',},
]

default_renpy_censored = [
    {'name': 'Yes', 'name_esp': 'Sí', 'description':'Completamente censurado.', 'is_active': True,},
    {'name': 'No', 'name_esp': 'No', 'description':'No Contiene nada de censura.', 'is_active': True,},
    {'name': 'Partial', 'name_esp': 'Parcial', 'description':'Censura Parcial.', 'is_active': True,},
]
