default_otaku_genres =[
    {'name':'Unknown', 'name_esp':'Desconocido', 'explicit':False, 'is_active':True, 'description':'Género para trabajos cuyo género principal no está claro o no se ha especificado.',},
    {'name':'Action', 'name_esp':'Acción', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en secuencias de lucha, persecuciones, violencia y emoción trepidante.',},
    {'name':'Adventure', 'name_esp':'Aventura', 'explicit':False, 'is_active':True, 'description':'Relatos que involucran viajes, exploración, búsqueda de tesoros, peligros y descubrimientos emocionantes.',},
    {'name':'Avant Garde', 'name_esp':'Vanguardista', 'explicit':False, 'is_active':True, 'description':'Trabajos experimentales que desafían las convenciones narrativas y estilísticas tradicionales.',},
    {'name':'Award Winning', 'name_esp':'Premiado', 'explicit':False, 'is_active':True, 'description':'Género para trabajos que han recibido algún tipo de premio o reconocimiento significativo.',},
    {'name':'Boys Love', 'name_esp':'Amor entre chicos', 'explicit':False, 'is_active':True, 'description':'Historias románticas o sexuales que se centran en las relaciones entre personajes masculinos.',},
    {'name':'Comedy', 'name_esp':'Comedia', 'explicit':False, 'is_active':True, 'description':'Relatos cuyo objetivo principal es provocar la risa y el humor en la audiencia.',},
    {'name':'Drama', 'name_esp':'Drama', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en las emociones, conflictos internos y relaciones intensas entre personajes.',},
    {'name':'Fantasy', 'name_esp':'Fantasía', 'explicit':False, 'is_active':True, 'description':'Relatos que incorporan elementos mágicos, criaturas míticas, mundos imaginarios y sucesos sobrenaturales.',},
    {'name':'Girls Love', 'name_esp':'Amor entre chicas', 'explicit':False, 'is_active':True, 'description':'Historias románticas o sexuales que se centran en las relaciones entre personajes femeninos.',},
    {'name':'Gourmet', 'name_esp':'Gastronómico', 'explicit':False, 'is_active':True, 'description':'Relatos que se centran en la comida, la cocina, la degustación y la apreciación de los alimentos.',},
    {'name':'Horror', 'name_esp':'Terror', 'explicit':False, 'is_active':True, 'description':'Historias diseñadas para asustar, inquietar o provocar miedo en la audiencia, a menudo con elementos sobrenaturales o violentos.',},
    {'name':'Mystery', 'name_esp':'Misterio', 'explicit':False, 'is_active':True, 'description':'Relatos que giran en torno a la resolución de un enigma, crimen o suceso inexplicable, manteniendo la intriga hasta el final.',},
    {'name':'Romance', 'name_esp':'Romance', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en el desarrollo de relaciones amorosas y sentimentales entre personajes.',},
    {'name':'Sci-Fi', 'name_esp':'Ciencia Ficción', 'explicit':False, 'is_active':True, 'description':'Relatos que exploran conceptos científicos y tecnológicos, viajes espaciales, futuros distópicos o utópicos, vida extraterrestre, etc.',},
    {'name':'Slice of Life', 'name_esp':'Vida Cotidiana', 'explicit':False, 'is_active':True, 'description':'Historias que presentan la vida diaria y las experiencias cotidianas de los personajes de una manera realista y sin grandes tramas.',},
    {'name':'Sports', 'name_esp':'Deportes', 'explicit':False, 'is_active':True, 'description':'Relatos que se centran en actividades deportivas, competiciones, el desarrollo de atletas y el espíritu deportivo.',},
    {'name':'Supernatural', 'name_esp':'Sobrenatural', 'explicit':False, 'is_active':True, 'description':'Historias que incorporan elementos que van más allá de la comprensión científica o las leyes de la naturaleza, como fantasmas, demonios, magia, etc.',},
    {'name':'Suspense', 'name_esp':'Suspenso', 'explicit':False, 'is_active':True, 'description':'Relatos que buscan mantener a la audiencia en un estado de incertidumbre, anticipación y tensión sobre lo que va a suceder.',},
    {'name':'Ecchi', 'name_esp':'Ecchi', 'explicit':True, 'is_active':True, 'description':'Género con contenido sugerente o ligeramente sexual con la intención de ser humorístico o pícaro, sin llegar a la representación explícita.',},
    {'name':'Erotica', 'name_esp':'Erótica', 'explicit':True, 'is_active':True, 'description':'Género con contenido sexual explícito destinado a la excitación.',},
    {'name':'Hentai', 'name_esp':'Hentai', 'explicit':True, 'is_active':True, 'description':'Término japonés para pornografía animada o manga con contenido sexual explícito.',},
]

default_otaku_themes = [
    {'name':'Unknown', 'name_esp':'Desconocido', 'explicit':False, 'is_active':True, 'description':'Tema para trabajos cuyo tema principal no está claro o no se ha especificado.',},
    {'name':'Adult Cast', 'name_esp':'Elenco Adulto', 'explicit':False, 'is_active':True, 'description':'Historias donde la mayoría de los personajes principales son adultos.',},
    {'name':'Anthropomorphic', 'name_esp':'Antropomórfico', 'explicit':False, 'is_active':True, 'description':'Historias con animales u otros seres no humanos que poseen características humanas como el habla, la inteligencia o la vestimenta.',},
    {'name':'CGDCT', 'name_esp':'Chicas Haciendo Cosas Cotidianas', 'explicit':False, 'is_active':True, 'description':'Un subgénero que se centra en las interacciones lindas y a menudo humorísticas de un grupo de chicas en sus actividades diarias.',},
    {'name':'Childcare', 'name_esp':'Cuidado Infantil', 'explicit':False, 'is_active':True, 'description':'Historias que giran en torno al cuidado de niños pequeños.',},
    {'name':'Combat Sports', 'name_esp':'Deportes de Combate', 'explicit':False, 'is_active':True, 'description':'Historias centradas en deportes donde el objetivo principal es el combate físico, como el boxeo, la lucha libre o las artes marciales mixtas.',},
    {'name':'Crossdressing', 'name_esp':'Transvestismo', 'explicit':False, 'is_active':True, 'description':'Historias donde uno o más personajes se visten y actúan como el sexo opuesto.',},
    {'name':'Delinquents', 'name_esp':'Delincuentes', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en jóvenes que se involucran en actividades ilegales o problemáticas.',},
    {'name':'Detective', 'name_esp':'Detectives', 'explicit':False, 'is_active':True, 'description':'Historias donde uno o más personajes son detectives que investigan crímenes o misterios.',},
    {'name':'Educational', 'name_esp':'Educativo', 'explicit':False, 'is_active':True, 'description':'Historias diseñadas para enseñar o informar sobre un tema específico.',},
    {'name':'Gag Humor', 'name_esp':'Humor de Gags', 'explicit':False, 'is_active':True, 'description':'Comedia que se basa en situaciones absurdas, payasadas y chistes visuales.',},
    {'name':'Gore', 'name_esp':'Gore', 'explicit':False, 'is_active':True, 'description':'Contenido que representa violencia gráfica extrema y derramamiento de sangre.',},
    {'name':'Harem', 'name_esp':'Harem', 'explicit':False, 'is_active':True, 'description':'Un personaje principal (generalmente masculino) está rodeado de tres o más intereses amorosos (generalmente femeninos).',},
    {'name':'High Stakes Game', 'name_esp':'Juego de Alta Apuesta', 'explicit':False, 'is_active':True, 'description':'Historias centradas en juegos o competiciones donde las consecuencias de perder son severas.',},
    {'name':'Historical', 'name_esp':'Histórico', 'explicit':False, 'is_active':True, 'description':'Historias ambientadas en el pasado, a menudo incorporando eventos o figuras históricas reales.',},
    {'name':'Idols (Female)', 'name_esp':'Idols (Femeninas)', 'explicit':False, 'is_active':True, 'description':'Historias centradas en grupos o individuos femeninos que son ídolos del entretenimiento.',},
    {'name':'Idols (Male)', 'name_esp':'Idols (Masculinas)', 'explicit':False, 'is_active':True, 'description':'Historias centradas en grupos o individuos masculinos que son ídolos del entretenimiento.',},
    {'name':'Isekai', 'name_esp':'Isekai', 'explicit':False, 'is_active':True, 'description':'Historias donde el protagonista es transportado o reencarna en otro mundo.',},
    {'name':'Iyashikei', 'name_esp':'Iyashikei', 'explicit':False, 'is_active':True, 'description':'Un subgénero cuyo objetivo principal es tener un efecto curativo y relajante en la audiencia, a menudo centrándose en la naturaleza y la tranquilidad.',},
    {'name':'Love Polygon', 'name_esp':'Polígono Amoroso', 'explicit':False, 'is_active':True, 'description':'Una situación romántica compleja que involucra a tres o más personas con sentimientos románticos entrelazados.',},
    {'name':'Love States Quo', 'name_esp':'Estatus Quo del Amor', 'explicit':False, 'is_active':True, 'description':'Historias donde la relación romántica principal ya está establecida y la trama se centra en mantenerla o explorar dinámicas dentro de ella.',},
    {'name':'Magical Sex Shift', 'name_esp':'Cambio Mágico de Sexo', 'explicit':False, 'is_active':True, 'description':'Historias donde uno o más personajes cambian de sexo debido a magia u otros medios sobrenaturales.',},
    {'name':'Mahou Shoujo', 'name_esp':'Mahou Shoujo', 'explicit':False, 'is_active':True, 'description':'Un subgénero que presenta a chicas jóvenes que tienen poderes mágicos y los usan para luchar contra el mal.',},
    {'name':'Martial Arts', 'name_esp':'Artes Marciales', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en diversas formas de combate cuerpo a cuerpo y la filosofía que las rodea.',},
    {'name':'Mecha', 'name_esp':'Mecha', 'explicit':False, 'is_active':True, 'description':'Historias que presentan robots o máquinas gigantes controladas por humanos.',},
    {'name':'Medical', 'name_esp':'Médico', 'explicit':False, 'is_active':True, 'description':'Historias ambientadas en entornos médicos, centradas en médicos, pacientes y la práctica de la medicina.',},
    {'name':'Military', 'name_esp':'Militar', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en conflictos armados, la vida militar y las estrategias de guerra.',},
    {'name':'Music', 'name_esp':'Música', 'explicit':False, 'is_active':True, 'description':'Historias donde la música juega un papel central, ya sea como tema principal o como un elemento importante en la trama y el desarrollo de los personajes.',},
    {'name':'Mythology', 'name_esp':'Mitología', 'explicit':False, 'is_active':True, 'description':'Historias que se basan en mitos y leyendas de diversas culturas.',},
    {'name':'Organized Crime', 'name_esp':'Crimen Organizado', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en grupos criminales organizados, sus actividades y sus miembros.',},
    {'name':'Otaku Culture', 'name_esp':'Cultura Otaku', 'explicit':False, 'is_active':True, 'description':'Historias que exploran o se centran en la cultura de los fanáticos del anime, manga y videojuegos.',},
    {'name':'Parody', 'name_esp':'Parodia', 'explicit':False, 'is_active':True, 'description':'Historias que imitan de forma cómica otras obras, géneros o estilos.',},
    {'name':'Performing Arts', 'name_esp':'Artes Escénicas', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en disciplinas como el teatro, la danza, la ópera o el circo.',},
    {'name':'Pets', 'name_esp':'Mascotas', 'explicit':False, 'is_active':True, 'description':'Historias donde los animales domésticos juegan un papel importante.',},
    {'name':'Psychological', 'name_esp':'Psicológico', 'explicit':False, 'is_active':True, 'description':'Historias que exploran la mente de los personajes, sus motivaciones internas, sus miedos y sus conflictos mentales.',},
    {'name':'Racing', 'name_esp':'Carreras', 'explicit':False, 'is_active':True, 'description':'Historias centradas en competiciones de velocidad, ya sean de coches, motos, u otros vehículos.',},
    {'name':'Reincarnation', 'name_esp':'Reencarnación', 'explicit':False, 'is_active':True, 'description':'Historias donde un personaje muere y renace en un nuevo cuerpo o mundo.',},
    {'name':'Reverse Harem', 'name_esp':'Harem Invertido', 'explicit':False, 'is_active':True, 'description':'Una protagonista femenina está rodeada de tres o más intereses amorosos masculinos.',},
    {'name':'Samurai', 'name_esp':'Samuráis', 'explicit':False, 'is_active':True, 'description':'Historias ambientadas en el Japón feudal y centradas en la vida y las acciones de los samuráis.',},
    {'name':'School', 'name_esp':'Escuela', 'explicit':False, 'is_active':True, 'description':'Historias ambientadas principalmente en un entorno escolar, centradas en las vidas de los estudiantes y sus relaciones.',},
    {'name':'Showbiz', 'name_esp':'Entretenimiento', 'explicit':False, 'is_active':True, 'description':'Historias que se desarrollan en el mundo del espectáculo, como la actuación, el cine, la televisión, etc.',},
    {'name':'Space', 'name_esp':'Espacio', 'explicit':False, 'is_active':True, 'description':'Historias ambientadas en el espacio exterior, a menudo involucrando viajes interestelares, exploración de planetas y encuentros con civilizaciones alienígenas.',},
    {'name':'Strategy Game', 'name_esp':'Juego de Estrategia', 'explicit':False, 'is_active':True, 'description':'Historias donde la planificación táctica y la estrategia son elementos centrales de la trama.',},
    {'name':'Super Power', 'name_esp':'Superpoderes', 'explicit':False, 'is_active':True, 'description':'Historias donde uno o más personajes poseen habilidades que van más allá de las capacidades humanas normales.',},
    {'name':'Survival', 'name_esp':'Supervivencia', 'explicit':False, 'is_active':True, 'description':'Historias donde los personajes luchan por sobrevivir en un entorno hostil.',},
    {'name':'Team Sports', 'name_esp':'Deportes en Equipo', 'explicit':False, 'is_active':True, 'description':'Historias centradas en deportes donde los individuos compiten como parte de un equipo.',},
    {'name':'Time Travel', 'name_esp':'Viajes en el Tiempo', 'explicit':False, 'is_active':True, 'description':'Historias donde los personajes pueden viajar a diferentes puntos en el tiempo.',},
    {'name':'Urban Fantasy', 'name_esp':'Fantasía Urbana', 'explicit':False, 'is_active':True, 'description':'Historias de fantasía ambientadas en un entorno urbano moderno.',},
    {'name':'Vampire', 'name_esp':'Vampiros', 'explicit':False, 'is_active':True, 'description':'Historias que presentan vampiros como personajes centrales o elementos importantes de la trama.',},
    {'name':'Video Game', 'name_esp':'Videojuego', 'explicit':False, 'is_active':True, 'description':'Historias que se desarrollan dentro de un mundo de videojuegos o que involucran personajes que están atrapados o interactúan con videojuegos.',},
    {'name':'Villainess', 'name_esp':'Villana', 'explicit':False, 'is_active':True, 'description':'Historias donde la protagonista es una villana o una antagonista que a menudo busca redimirse o cambiar su destino.',},
    {'name':'Visual Arts', 'name_esp':'Artes Visuales', 'explicit':False, 'is_active':True, 'description':'Historias que se centran en la creación o apreciación de diversas formas de arte visual.',},
    {'name':'Workplace', 'name_esp':'Lugar de Trabajo', 'explicit':False, 'is_active':True, 'description':'Historias ambientadas principalmente en un entorno profesional o de oficina, centradas en las vidas y relaciones de los empleados.',},
]

default_otaku_demographics = [
    {'name': 'Unknown', 'name_esp': 'Desconocido', 'explicit': False, 'is_active': True, 'description': 'Demografía para trabajos cuyo público objetivo no está claro o no se ha especificado.',},
    {'name': 'Shounen', 'name_esp': 'Shōnen', 'explicit': False, 'is_active': True, 'description': 'Dirigido principalmente a un público masculino joven. Suele presentar acción, aventuras y personajes masculinos protagonistas.',},
    {'name': 'Shoujo', 'name_esp': 'Shōjo', 'explicit': False, 'is_active': True, 'description': 'Dirigido principalmente a un público femenino joven. Se centra en relaciones románticas y emociones.',},
    {'name': 'Seinen', 'name_esp': 'Seinen', 'explicit': False, 'is_active': True, 'description': 'Dirigido a un público adulto masculino. Puede abordar temas más maduros y complejos.',},
    {'name': 'Josei', 'name_esp': 'Josei', 'explicit': False, 'is_active': True, 'description': 'Dirigido a un público adulto femenino. Explora temas de la vida cotidiana y relaciones.',},
    {'name': 'Kids', 'name_esp': 'Infantil', 'explicit': False, 'is_active': True, 'description': 'Dirigido a niños pequeños.',},
    {'name': 'Kodomomuke', 'name_esp': 'Kodomomuke', 'explicit': False, 'is_active': True, 'description': 'Dirigido a niños muy pequeños.',},
    {'name': 'Young Adult', 'name_esp': 'Joven Adulto', 'explicit': False, 'is_active': True, 'description': 'Dirigido a adolescentes mayores y jóvenes adultos.',},
    {'name': 'Family', 'name_esp': 'Familiar', 'explicit': False, 'is_active': True, 'description': 'Dirigido a un público amplio de todas las edades.',},
]

default_otaku_types = [
    {'name': 'Unknown', 'name_esp': 'Desconocido', 'is_active': True, 'description': 'Tipo de título desconocido.',},
    {'name': 'Doujinshi', 'name_esp': 'Doujinshi', 'is_active': True, 'description': 'Obra creada por fanáticos basada en personajes o universos existentes.',},
    {'name': 'Light Novel', 'name_esp': 'Novela Ligera', 'is_active': True, 'description': 'Novela con ilustraciones, popular en Japón y dirigida a un público joven.',},
    {'name': 'Manga', 'name_esp': 'Manga', 'is_active': True, 'description': 'Historia serializada en formato de cómic japonés.',},
    {'name': 'Manhua', 'name_esp': 'Manhua', 'is_active': True, 'description': 'Cómic chino, similar al manga japonés y al manhwa surcoreano.',},
    {'name': 'Manhwa', 'name_esp': 'Manhwa', 'is_active': True, 'description': 'Cómic surcoreano, similar al manga japonés.',},
    {'name': 'Movie', 'name_esp': 'Película', 'is_active': True, 'description': 'Largometraje cinematográfico.',},
    {'name': 'Music', 'name_esp': 'Música', 'is_active': True, 'description': 'Videos musicales o contenido relacionado con la música.',},
    {'name': 'Novel', 'name_esp': 'Novela', 'is_active': True, 'description': 'Historia narrativa en forma de prosa.',},
    {'name': 'ONA', 'name_esp': 'ONA', 'is_active': True, 'description': 'Original Net Animation (Animación en Red Original).',},
    {'name': 'One-Shot', 'name_esp': 'One-Shot', 'is_active': True, 'description': 'Historia corta que se desarrolla en un solo capítulo o volumen.',},
    {'name': 'OVA', 'name_esp': 'OVA', 'is_active': True, 'description': 'Original Video Animation (Animación en Video Original).',},
    {'name': 'Special', 'name_esp': 'Especial', 'is_active': True, 'description': 'Episodios o producciones especiales.',},
    {'name': 'TV', 'name_esp': 'TV', 'is_active': True, 'description': 'Transmisión en televisión.',},
    {'name': 'TV Special', 'name_esp': 'Especial de TV', 'is_active': True, 'description': 'Un especial del Anime de transmisión en televisión.',},
    {'name': 'CM', 'name_esp': 'AC', 'is_active': True, 'description': 'Anuncio Comercial',},
    {'name': 'PV', 'name_esp': 'VP', 'is_active': True, 'description': 'Video Promocional',},
]

default_otaku_ratings = [
    {'acronym': 'UNK', 'name': 'Unknown', 'name_esp': 'Desconocido', 'is_active': True, 'description': 'Clasificación desconocida o no especificada.',},
    {'acronym': 'G', 'name': 'All Ages', 'name_esp': 'Todas las Edades', 'is_active': True, 'description': 'Contenido apto para todas las edades.',},
    {'acronym': 'PG', 'name': 'Children', 'name_esp': 'Niños', 'is_active': True, 'description': 'Contenido apto para niños.',},
    {'acronym': 'PG-13', 'name': 'Teens 13 or older', 'name_esp': 'Adolescentes de 13 años o más', 'is_active': True, 'description': 'Contenido apto para adolescentes de 13 años o más.',},
    {'acronym': 'R-17+', 'name': 'Violence & Profanity', 'name_esp': 'Violencia & Profanidad', 'is_active': True, 'description': 'Contenido recomendado para personas de 17 años o más debido a la presencia de violencia y lenguaje fuerte.',},
    {'acronym': 'R+', 'name': 'Mild Nudity', 'name_esp': 'Desnudez Moderada', 'is_active': True, 'description': 'Contenido que puede incluir desnudez moderada.',},
    {'acronym': 'Rx', 'name': 'Hentai', 'name_esp': 'Hentai', 'is_active': True, 'description': 'Contenido hentai para adultos. Restringido a mayores de edad.',},
]

default_otaku_seasons =[
    {'name': 'Unknown', 'name_esp': 'Desconocido', 'is_active': True, 'description': 'Se utiliza para indicar que la temporada de lanzamiento de un anime es desconocida o no está especificada.',},
    {'name': 'Fall', 'name_esp': 'Otoño', 'is_active': True, 'description': 'Generalmente abarca los meses de octubre, noviembre y diciembre. Es una de las temporadas más fuertes para nuevos lanzamientos de anime.',},
    {'name': 'Spring', 'name_esp': 'Primavera', 'is_active': True, 'description': 'Generalmente abarca los meses de abril, mayo y junio. Es otra temporada importante para el estreno de nuevas series.',},
    {'name': 'Winter', 'name_esp': 'Invierno', 'is_active': True, 'description': 'Generalmente abarca los meses de enero, febrero y marzo. Suele tener menos estrenos que Primavera y Otoño, pero aún presenta títulos interesantes.',},
    {'name': 'Summer', 'name_esp': 'Verano', 'is_active': True, 'description': 'Generalmente abarca los meses de julio, agosto y septiembre. También es una temporada con muchos estrenos de anime.',},
]

default_otaku_status = [
    {'name': 'Unknown', 'name_esp': 'Desconocido', 'description': 'Estado desconocido o no especificado.', 'is_active': True},
    {'name': 'Not yet aired', 'name_esp': 'Aún no ha sido emitido', 'description': 'La serie o título aún no ha sido emitido y se espera su lanzamiento en el futuro.', 'is_active': True},
    {'name': 'Currently Airing', 'name_esp': 'En Emisión', 'description': 'La serie o título se encuentra actualmente en emisión.', 'is_active': True},
    {'name': 'Finished Airing', 'name_esp': 'Finalizado', 'description': 'La serie o título ha finalizado su emisión.', 'is_active': True},
    {'name': 'Not yet published', 'name_esp': 'No publicada aún', 'description': 'La obra aún no ha sido publicada.', 'is_active': True},
    {'name': 'Publishing', 'name_esp': 'Publicándose', 'description': 'La obra se encuentra actualmente en publicación.', 'is_active': True},
    {'name': 'Finished', 'name_esp': 'Finalizada', 'description': 'La obra ha finalizado su publicación.', 'is_active': True},
    {'name': 'On Hiatus', 'name_esp': 'En Pausa', 'description': 'La obra se encuentra en pausa temporal.', 'is_active': True},
    {'name': 'Discontinued', 'name_esp': 'Descontinuado', 'description': 'La obra ha sido descatalogada o interrumpida de manera permanente.', 'is_active': True},
]

default_otaku_sources = [
    {'name': 'Unknown', 'name_esp': 'Desconocido', 'description': 'Tipo de fuente desconocido.', 'is_active': True},
    {'name': '4-Koma Manga', 'name_esp': 'Manga 4-koma', 'description': 'Adaptado de un manga 4-koma.', 'is_active': True},
    {'name': 'Book', 'name_esp': 'Libro', 'description': 'Adaptado de un libro.', 'is_active': True},
    {'name': 'Card Game', 'name_esp': 'Juego de Cartas', 'description': 'Adaptado de un juego de cartas.', 'is_active': True},
    {'name': 'Game', 'name_esp': 'Videojuego', 'description': 'Adaptado de un videojuego.', 'is_active': True},
    {'name': 'Light Novel', 'name_esp': 'Novela Ligera', 'description': 'Adaptado de una novela ligera.', 'is_active': True},
    {'name': 'Manga', 'name_esp': 'Manga', 'description': 'Adaptado de un manga.', 'is_active': True},
    {'name': 'Mixed Media', 'name_esp': 'Medios Mixtos', 'description': 'Proyecto adaptado de múltiples fuentes de medios diferentes.', 'is_active': True},
    {'name': 'Music', 'name_esp': 'Música', 'description': 'Adaptado de contenido musical.', 'is_active': True},
    {'name': 'Novel', 'name_esp': 'Novela', 'description': 'Adaptado de una novela.', 'is_active': True},
    {'name': 'Original', 'name_esp': 'Original', 'description': 'Fuente original del título. No adaptada de ningún otro medio.', 'is_active': True},
    {'name': 'Other', 'name_esp': 'Otro', 'description': 'Fuente de origen no especificada o categorizada.', 'is_active': True},
    {'name': 'Picture Book', 'name_esp': 'Libro de Imágenes', 'description': 'Adaptado de un libro de imágenes.', 'is_active': True},
    {'name': 'Radio', 'name_esp': 'Radio', 'description': 'Proveniente de dramas o programas de radio narrativos. Estos suelen ser adaptaciones de historias contadas originalmente en audio.', 'is_active': True},
    {'name': 'Visual Novel', 'name_esp': 'Novela Visual', 'description': 'Adaptado de una novela visual.', 'is_active': True},
    {'name': 'Web Manga', 'name_esp': 'Manga en Línea', 'description': 'Adaptado de un manga en línea.', 'is_active': True},
    {'name': 'Web Novel', 'name_esp': 'Novela en Línea', 'description': 'Adaptado de una novela en línea.', 'is_active': True},
]

default_otaku_relations_types = [
    {'name': 'Adaptation', 'name_esp': 'Adaptación', 'description': 'Basado en otra obra, normalmente manga, novelas ligeras o juegos.', 'is_active': True},
    {'name': 'Alternative Setting', 'name_esp': 'Entorno Alternativo', 'description': 'Una historia que reimagina los personajes y la premisa en un universo o línea temporal diferente.', 'is_active': True},
    {'name': 'Based On', 'name_esp': 'Basado En', 'description': 'Utilizado para el material de origen.', 'is_active': True},
    {'name': 'Compilation', 'name_esp': 'Compilación', 'description': 'Similar a un resumen, pero puede implicar una reedición o contenido adicional.', 'is_active': True},
    {'name': 'Original Story', 'name_esp': 'Historia Original', 'description': 'Indica que el anime o manga no está basado en una obra preexistente.', 'is_active': True},
    {'name': 'Other', 'name_esp': 'Otros', 'description': 'Un tipo de relación menos común o específica.', 'is_active': True},
    {'name': 'Prequel', 'name_esp': 'Precuela', 'description': 'Una historia que tiene lugar antes de los acontecimientos de un anime, pelicula o manga anterior.', 'is_active': True},
    {'name': 'Same Setting', 'name_esp': 'Mismo Entorno', 'description': 'tienen lugar en el mismo mundo pero pueden no ser secuelas o precuelas directas.', 'is_active': True},
    {'name': 'Sequel', 'name_esp': 'Secuela', 'description': 'Continuación directa de una serie de anime, película o manga anterior.', 'is_active': True},
    {'name': 'Side Story', 'name_esp': 'Historia Paralela', 'description': 'Historia que transcurre en el mismo universo que el anime, la película o el manga principal, pero que se centra en personajes o acontecimientos diferentes.', 'is_active': True},
    {'name': 'Spin-Off', 'name_esp': 'Derivada', 'description': 'Una nueva serie que se ramifica, a menudo centrándose en un personaje o elemento específico.', 'is_active': True},
    {'name': 'Summary', 'name_esp': 'Resumen', 'description': 'Una colección que recapitula los acontecimientos de una serie.', 'is_active': True},
]

default_otaku_roles = [
    # Roles Personajes
    {'name': 'Main', 'name_esp': 'Principal', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'El personaje central o protagonista de la historia.'},
    {'name': 'Supporting', 'name_esp': 'Secundario', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que no es el principal pero que juega un papel importante en la historia.'},
    {'name': 'Antagonist', 'name_esp': 'Antagonista', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'El personaje o fuerza que se opone al protagonista.'},
    {'name': 'Main Supporting', 'name_esp': 'Secundario Principal', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje secundario con una presencia e importancia significativa en la trama.'},
    {'name': 'Love Interest', 'name_esp': 'Interés Amoroso', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje con el que el protagonista o un personaje principal tiene una relación romántica o potencial.'},
    {'name': 'Rival','name_esp': 'Rival', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que compite con el protagonista.'},
    {'name': 'Mentor', 'name_esp': 'Mentor', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que guía y aconseja al protagonista.'},
    {'name': 'Sensei', 'name_esp': 'Sensei', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un maestro o instructor.'},
    {'name': 'Villain', 'name_esp': 'Villano', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje malvado o malintencionado.'},
    {'name': 'Ally', 'name_esp': 'Aliado', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que apoya y ayuda al protagonista.'},
    {'name': 'Friend', 'name_esp': 'Amigo', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje con una relación de amistad con el protagonista.'},
    {'name': 'Childhood Friend', 'name_esp': 'Amigo de la infancia', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un amigo del protagonista desde la infancia.'},
    {'name': 'Guardian', 'name_esp': 'Guardián', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que protege o cuida a otro.'},
    {'name': 'King', 'name_esp': 'Rey', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un monarca masculino.'},
    {'name': 'Queen', 'name_esp': 'Reina', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Una monarca femenina.'},
    {'name': 'Prince', 'name_esp': 'Príncipe', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un hijo de un rey o reina.'},
    {'name': 'Princess', 'name_esp': 'Princesa', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Una hija de un rey o reina.'},
    {'name': 'Leader', 'name_esp': 'Líder', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que dirige un grupo u organización.'},
    {'name': 'Member', 'name_esp': 'Miembro', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que forma parte de un grupo o equipo.'},
    {'name': 'Lone Wolf', 'name_esp': 'Lobo Solitario', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje que prefiere trabajar o actuar solo.'},
    {'name': 'Foil', 'name_esp': 'Contraste', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje cuyas cualidades contrastan con las de otro personaje, resaltando así sus rasgos.'},
    {'name': 'Comic Relief', 'name_esp': 'Alivio cómico', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'Un personaje cuyo propósito principal es proporcionar humor.'},
    {'name': 'Narrator', 'name_esp': 'Narrador', 'role_staff': False, 'role_chara': True, 'role_manga': False, 'is_active': True, 'description': 'El personaje o la voz que cuenta la historia.'},
    ### Staff Animación
    {'name': 'Producer', 'name_esp': 'Productor', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Responsable de la supervisión general y la financiación del proyecto de animación.'},
    {'name': 'Assistant Producer', 'name_esp': 'Ayudante de producción', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Asiste al productor en diversas tareas de producción.'},
    {'name': 'Director', 'name_esp': 'Director', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Responsable de la visión artística general y la dirección de la animación.'},
    {'name': 'Episode Director', 'name_esp': 'Director de episodios', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Dirige la producción de episodios individuales de una serie de anime.'},
    {'name': 'Script', 'name_esp': 'Guión', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Responsable de escribir el guión de la animación.'},
    {'name': 'Storyboard', 'name_esp': 'Guión gráfico', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea una secuencia visual de la animación, plano por plano.'},
    {'name': 'Sound Director', 'name_esp': 'Director de sonido', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Supervisa todos los aspectos del sonido en la animación.'},
    {'name': 'Series Composition', 'name_esp': 'Composición de la serie', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Responsable de la estructura narrativa general y el flujo de la serie.'},
    {'name': 'Theme Song Lyrics', 'name_esp': 'Letra de la canción', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Escribe la letra de las canciones temáticas de la animación.'},
    {'name': 'Theme Song Arrangement', 'name_esp': 'Arreglo de la canción', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea el arreglo musical de las canciones temáticas.'},
    {'name': 'Theme Song Composition', 'name_esp': 'Composición de la canción', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea la melodía y la estructura musical de las canciones temáticas.'},
    {'name': 'Music', 'name_esp': 'Música', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Compone la banda sonora original de la animación.'},
    {'name': 'Inserted Song Performance', 'name_esp': 'Interpretación de Canción Insertada', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Interpreta canciones que se insertan dentro de la animación.'},
    {'name': 'Theme Song Performance', 'name_esp': 'Interpretación de la canción', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Interpreta las canciones temáticas de la animación (opening y ending).'},
    {'name': 'Key Animation', 'name_esp': 'Animación clave', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Dibuja los fotogramas clave que definen el movimiento principal de los personajes y objetos.'},
    {'name': 'ADR Director', 'name_esp': 'Director ADR', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Dirige la grabación de las voces para el doblaje en otros idiomas.'},
    {'name': 'Animation Directo', 'name_esp': 'Director de animación', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Supervisa la calidad y la consistencia de la animación.'},
    {'name': 'Special Effects', 'name_esp': 'Efectos especiales', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea efectos visuales que no son animación de personajes o fondos.'},
    {'name': 'Background Art', 'name_esp': 'Arte de fondo', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea los fondos y los entornos donde se desarrolla la acción.'},
    {'name': 'Art Director', 'name_esp': 'Director artístico', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Responsable del estilo visual general de la animación.'},
    {'name': 'In-Between Animation', 'name_esp': 'Animación intermedia', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Dibuja los fotogramas intermedios para suavizar el movimiento entre los fotogramas clave.'},
    {'name': 'Character Design', 'name_esp': 'Diseño de personajes', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea la apariencia visual de los personajes.'},
    {'name': 'Layout', 'name_esp': 'Maquetación', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Determina la composición de cada plano y la posición de los personajes y objetos.'},
    {'name': 'Chief Animation Director', 'name_esp': 'Director jefe de animación', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Supervisa la calidad del dibujo y la consistencia de los personajes en toda la producción.'},
    {'name': 'Assistant Animation Director', 'name_esp': 'Asistente de dirección de animación', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Asiste al director jefe de animación en sus tareas.'},
    {'name': 'Sound Effects', 'name_esp': 'Efectos de sonido', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea y edita los sonidos que no son diálogo ni música.'},
    {'name': 'Dialogue Editing', 'name_esp': 'Edición de diálogos', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Edita y sincroniza las grabaciones de diálogo.'},
    {'name': 'Color Design', 'name_esp': 'Diseño de color', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Determina la paleta de colores para los personajes, fondos y objetos.'},
    {'name': 'Director of Photography', 'name_esp': 'Director de fotografía', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Responsable de la iluminación y el aspecto visual de la animación.'},
    {'name': '2nd Key Animation', 'name_esp': 'Animación clave 2ª', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Dibuja fotogramas clave adicionales para complementar el trabajo del animador clave principal.'},
    {'name': 'Digital Paint', 'name_esp': 'Pintura digital', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Aplica color digitalmente a los dibujos de animación.'},
    {'name': 'Editing', 'name_esp': 'Edición', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Ensambla los diferentes elementos de la animación en la secuencia final.'},
    {'name': 'Mechanical Design', 'name_esp': 'Diseño mecánico', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Diseña los robots, vehículos y otros elementos mecánicos.'},
    {'name': 'Original Creator', 'name_esp': 'Creador original', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'La persona que concibió la idea original de la obra.'},
    {'name': 'Planning', 'name_esp': 'Planificación', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Participa en la fase inicial de planificación y conceptualización del proyecto.'},
    {'name': 'Original Character Design', 'name_esp': 'Diseño de personajes originales', 'role_staff': True, 'role_chara': False, 'role_manga': False, 'is_active': True, 'description': 'Crea los diseños de personajes que no están basados en una obra preexistente.'},
    ### Manga
    {'name': 'Art','name_esp': 'Arte', 'role_staff': False, 'role_chara': False, 'role_manga': True, 'is_active': True, 'description': 'Responsable de dibujar las ilustraciones y los paneles del manga.'},
    {'name': 'Story','name_esp': 'Historia', 'role_staff': False, 'role_chara': False, 'role_manga': True, 'is_active': True, 'description': 'Responsable de escribir la trama y el guión del manga.'},
    {'name': 'Art & Story','name_esp': 'Arte e Historia', 'role_staff': False, 'role_chara': False, 'role_manga': True, 'is_active': True, 'description': 'Responsable tanto del dibujo como de la escritura de la historia del manga.'},
]